GoogleCloudPlatform/vertex-ai-samples

notebooks/official/workbench/ads_targetting/training-multi-class-classification-model-for-ads-targeting-usecase.ipynb
=> fix: boilerplate reduction 84: NumPy array to a Tensor

notebooks/official/training/xgboost_data_parallel_training_on_cpu_using_dask.ipynb
=> fix: boilerplate reduction 82 : custom job not created

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_jax_vision_transformer.ipynb
<br>
Adding a notebook for JAX based ViT-B16 model finetuning and prediction.
<br><br><br>
=> Add ViT JAX notebook.

notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb
=> feat: boilerplate reduction 60 - DAG failed

notebooks/official/migration/sdk-automl-image-classification-batch-online.ipynb
=> fix: boilerplate reduction 99

notebooks/official/explainable_ai/sdk_custom_tabular_regression_batch_explain.ipynb
=> fix: check if passes #5

notebooks/official/pipelines/pipelines_intro_kfp.ipynb
=> fix: check if passes 8

community-content/CODEOWNERS, community-content/vertex_vision_model_garden/model_oss/diffusers/dockerfile/serve.Dockerfile, community-content/vertex_vision_model_garden/model_oss/diffusers/dockerfile/train.Dockerfile, community-content/vertex_vision_model_garden/model_oss/diffusers/handler.py, community-content/vertex_vision_model_garden/model_oss/diffusers/train.sh
<br>
Updates to the vision diffusers.
<br><br><br>
<br>
<br> …
=> Updates to the vision diffusers.

notebooks/official/pipelines/multicontender_vs_champion_deployment_method.ipynb
=> fix: check if passes 9

notebooks/official/pipelines/multicontender_vs_champion_deployment_method.ipynb, notebooks/official/tabnet/get_started_with_tabnet.ipynb
=> Check passes 10

notebooks/official/automl/automl-text-classification.ipynb
=> fix: check if passes 7

notebooks/official/migration/sdk-automl-text-classification-batch-prediction.ipynb
<br>
Reduce boilerplate in official notebook
<br><br><br>
<br>
<br> …
=> fix: boilerplate reduction 100

notebooks/official/model_monitoring/get_started_with_model_monitoring_setup.ipynb
=> fix: check if passes 11

notebooks/official/migration/sdk-automl-image-object-detection-batch-online.ipynb
<br>
Apply boilerplate reduction to official
<br><br><br>
<br>
<br> …
=> fix: boilerplate reduction 104

notebooks/official/migration/sdk-automl-text-entity-extraction-batch-prediction.ipynb
=> fix: boilerplate reduction 107

notebooks/official/migration/sdk-automl-video-classification-batch-prediction.ipynb
<br>
Apply boilerplate reduction on official notebook
<br><br><br>
<br>
<br> …
=> fix: boilerplate reduction 108

notebooks/official/migration/sdk-custom-scikit-learn-prebuilt-container.ipynb
=> fix: boilerplate reduction 110

notebooks/official/migration/sdk-custom-image-classification-prebuilt-container.ipynb
=> fix: boilerplate reduction 109

notebooks/official/migration/sdk-automl-text-classification-batch-prediction.ipynb
=> fix: boilerplate 103

notebooks/official/migration/sdk-custom-xgboost-prebuilt-container.ipynb
=> fix: boilerplate reduction 111

notebooks/community/model_garden/model_garden_mediapipe_image_classification.ipynb
This PR fixes some wording in the MediaPipe notebook.
=> Small content updates for ImageClassification notebook

notebooks/official/migration/sdk-automl-tabular-binary-classification-online-prediction.ipynb
<br>
Apply bolierplate reduction to official notebook
<br><br><br>
<br>
<br> …
=> fix: boilerplate reduction 106

notebooks/official/tabnet/tabnet_vertex_tutorial.ipynb
=> fix: boilerplate reduction 71 - model path

notebooks/official/model_monitoring/model_monitoring.ipynb
=> fix: boilerplate reduction 49 - import protobuf

notebooks/official/custom/SDK_FBProphet_Forecasting_Online.ipynb
=> fix: boilerplate reduction 19 - >24hrs

notebooks/official/custom/SDK_Custom_Container_Prediction.ipynb
=> fix: boilerplate reduction 18 - > 24hrs

notebooks/community/model_garden/model_garden_pytorch_sam.ipynb
- run endpoint/model deployment in separate cell and results visualization in another.
- add show_predictions function to show overlayed masks.
<br>
<br><br><br>
<br>
2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main …
=> Cleanup SAM segmentation notebook

notebooks/official/workbench/predictive_maintainance/predictive_maintenance_usecase.ipynb
=> fix: check if passes 15

notebooks/official/workbench/spark/spark_ml.ipynb
=> fix: check if passes 16

notebooks/community/bigquery_ml/bq_ml_with_vision_translation_nlp.ipynb
<br>
Remove cell directing users to fill out form for allowlist; product is no longer behind allowlist.
<br><br><br>
<br>
<br> …
=> Remove allowlist note

.cloud-build/execute_changed_notebooks_helper.py
per Ivan suggested, change greedy=True to greedy=False
<br>
Trying to reduce QUOTA errors (currently 11)
<br><br><br>
<br>
<br> …
=> update: lower rate limit

notebooks/official/prediction/pytorch_image_classification_with_prebuilt_serving_containers.ipynb
=> Check if passes 17

notebooks/official/prediction/pytorch_train_deploy_models_with_prebuilt_containers.ipynb
=> debug: check if passes 18

notebooks/official/tensorboard/tensorboard_vertex_ai_pipelines_integration.ipynb
=> debug: check if passes 19

notebooks/official/workbench/inventory-prediction/inventory_prediction.ipynb
<br>
Check if CI/CD passes
<br><br><br>
<br>
<br> …
=> debug: check if passes 22

notebooks/community/model_garden/model_garden_pytorch_sam.ipynb
=> SAM notebook final qa.

notebooks/official/tensorboard/tensorboard_hyperparameter_tuning_with_hparams.ipynb
=> debug: check if passes 25

notebooks/official/model_registry/bqml_vertexai_model_registry.ipynb
=> debug: check if passes 27

.github/workflows/linter/run_linter.sh
<br>
Fix lint in CI/CD not compatiable with Docker version
<br><br><br>
<br>
<br> …
=> set pyupgrade to use Python 3.10 for consistency with Docker version

notebooks/official/reduction_server/pytorch_distributed_training_reduction_server.ipynb
=> debug: check if passes 29

notebooks/community/model_garden/model_garden_pytorch_sam.ipynb
=> Add missing pycocotools import to SAM notebook

.github/workflows/linter/run_linter.sh
<br>
Debug CI/CD lint issue
<br><br><br>
<br>
<br> …
=> next try at resolving lint issue

notebooks/official/pipelines/lightweight_functions_component_io_kfp.ipynb
<br>
Debug lint failure
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vert …
=> debug: lint

notebooks/community/model_garden/model_garden_pytorch_blip2.ipynb, notebooks/community/model_garden/model_garden_pytorch_blip_image_captioning.ipynb, notebooks/community/model_garden/model_garden_pytorch_blip_vqa.ipynb, notebooks/community/model_garden/model_garden_pytorch_clip.ipynb, notebooks/community/model_garden/model_garden_pytorch_flan_t5_xxl.ipynb, notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb, notebooks/community/model_garden/model_garden_pytorch_layoutml_document_qa.ipynb, notebooks/community/model_garden/model_garden_pytorch_owlvit.ipynb, notebooks/community/model_garden/model_garden_pytorch_vilt_vqa.ipynb, notebooks/community/model_garden/model_garden_pytorch_vit_gpt2_image_captioning.ipynb
**REQUIRED:** Add restart kernel to pytorch notebooks
=> Add restart kernel to pytorch notebooks

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
[Remove bad parameters for local stable diffusion.](https://github.com/GoogleCloudPlatform/vertex-ai-samples/commit/97e701ac423681fabcc34903fa46e4c03fffaed7)
<br>
<br>
=> Remove bad parameters for local stable diffusion.

notebooks/community/model_garden/model_garden_keras_stable_diffusion.ipynb
**REQUIRED:** fix minor typos in keras model deployment
<br>
fix minor typos in keras model deployment
<br><br><br>
- [Y] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md …
=> fix minor typos in keras model deployment

.cloud-build/execute_changed_notebooks_cli.py, .cloud-build/execute_changed_notebooks_helper.py
<br>
Make the max number of notebooks tested in parallel a cmdline arg
<br><br><br>
<br>
<br> …
=> feat: make rate limit a cmdarg

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_2_1.ipynb
<br>
Add the text2video-zero notebook.
This notebook demonstrates text-to-video zero-shot OSS checkpoint serving on Vertex AI.
<br><br><br>
<br>
- [+] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/CODEOWNERS) file under the `Community Notebooks` section, pointing to the author or the author's team.
- [+] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
=> Add the stable diffusion 2.1 notebook

community-content/CODEOWNERS, community-content/vertex_vision_model_garden/model_oss/transformers/dockerfile/serve.Dockerfile, community-content/vertex_vision_model_garden/model_oss/transformers/handler.py, community-content/vertex_vision_model_garden/model_oss/util/image_format_converter.py
Add transformer serve files.
<br>
<br><br><br>
<br>
<br>
=> Add transformers serve files.

.cloud-build/execute_changed_notebooks_cli.py, .cloud-build/execute_changed_notebooks_helper.py
<br>
Fixed docstring typo
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/ve …
=> fix help msg

.cloud-build/notebook-execution-test-cloudbuild.yaml
<br>
Updated cloud build YAML file to include arg for maximum number of concurrent notebooks
<br><br><br>
<br>
<br> …
=> feat: add arg for max concurrent notebooks

community-content/vertex_vision_model_garden/model_oss/diffusers/dockerfile/serve.Dockerfile, community-content/vertex_vision_model_garden/model_oss/diffusers/dockerfile/train.Dockerfile, community-content/vertex_vision_model_garden/model_oss/diffusers/handler.py, community-content/vertex_vision_model_garden/model_oss/util/fileutils.py, community-content/vertex_vision_model_garden/model_oss/video_util/video_format_converter.py
Install entire diffusers repository rather than diffusers package
=> Install entire diffusers repository rather than diffusers package

notebooks/community/model_garden/model_garden_mediapipe_image_classification.ipynb, notebooks/community/model_garden/model_garden_mediapipe_object_detection.ipynb
This updates some of the phrasing in the MediaPipe notebooks and fixes an error with the split rate.
=> Update wording in MediaPipe notebooks

community-content/vertex_vision_model_garden/.pylintrc
Add pylintrc to model_oss
<br>
<br><br><br>
<br>
<br>
=> Add pylintrc to model_oss

notebooks/community/model_garden/model_garden_pytorch_peft.ipynb
**REQUIRED:** minor updates for peft notebooks with BERT supports
<br>
minor updates for peft notebooks with BERT supports
<br><br><br>
- [Y] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/ …
=> minor updates for peft notebooks with BERT supports

notebooks/official/model_evaluation/custom_tabular_classification_model_evaluation.ipynb
<br>
Debug error: ValueError: Please install the 'db-dtypes' package to use this function.
<br><br><br>
<br>
<br> …
=> debug: regression failure

notebooks/community/model_garden/model_garden_tfvision_image_object_detection.ipynb
Support Yolov7 in OSS Tfvision notebook
<br><br><br>
<br>
<br>
=> Support Yolov7 in OSS Tfvision notebook

notebooks/community/model_garden/model_garden_proprietary_image_classification.ipynb, notebooks/community/model_garden/model_garden_proprietary_image_object_detection.ipynb
<br>
Update deploy machine information. 
Deployed model does not support dedicated deployment resources. The machine_type, accelerator_type and accelerator_count,autoscaling_target_accelerator_duty_cycle,autoscaling_target_cpu_utilization parameters are ignored.
<br>
<br>
=> Update deploy machine information.

notebooks/official/pipelines/kfp2_pipeline.ipynb
=> fix: branding

notebooks/official/experiments/comparing_pipeline_runs.ipynb
<br>
Fix positional parameters
<br><br><br>
<br>
<br> …
=> fix: positional params

notebooks/official/tensorboard/tensorboard_custom_training_with_custom_container.ipynb
<br>
Fix lint and AR issue
<br><br><br>
<br>
<br> …
=> fix: AR issue

notebooks/official/workbench/ads_targetting/training-multi-class-classification-model-for-ads-targeting-usecase.ipynb
<br>
Fix numpy type error
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/ve …
=> fix: numpy type

notebooks/official/tabular_workflows/wide_and_deep_on_vertex_pipelines.ipynb
<br>
Pin the version of GCPC < 2.0
<br><br><br>
<br>
<br> …
=> fix: pin gcpc

notebooks/official/training/multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb
<br>
Fix AR repo not found
<br><br><br>
<br>
<br> …
=> fix: AR not found

notebooks/official/custom/SDK_Custom_Container_Prediction.ipynb
<br>
Attempt fix for issue 2108
<br><br><br>
<br>
<br> …
=> fix: pip install

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_movinet_clip_classification.ipynb
This notebook covers the training and serving of the open source MoViNet model on clip classification.
<br>
<br>
=> Add #ModelGarden MoViNet Video Clip Classification Notebook

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_falcon_instruct_peft.ipynb
**REQUIRED:** Add a separate notebook for falcon instruct peft to be more easy to understand popular falcon models.
<br>
Add a separate notebook for falcon instruct peft to be more easy to understand popular falcon models.
<br><br><br>
- [Y] Passes all the required formatting and linting checks. You can …
=> add a separate notebook for falcon instruct peft to be more easy to understand popular falcon models

notebooks/official/training/pytorch_gcs_data_training.ipynb
<br>
Fix CI/CD testing issue
<br><br><br>
<br>
<br> …
=> fix: torch install

notebooks/official/prediction/custom_batch_prediction_feature_filter.ipynb
<br>
Fix missing install of db-dtypes
<br><br><br>
<br>
<br> …
=> fix: install db-dtypes

notebooks/official/pipelines/metrics_viz_run_compare_kfp.ipynb
<br>
Fix regression failure in notebook
<br><br><br>
<br>
<br> …
=> fix: scikit-learn version

notebooks/official/workbench/sentiment_analysis/Sentiment_Analysis.ipynb
<br>
Check if CI/CD passes
<br><br><br>
<br>
<br> …
=> debug: check if passes 20 - 'float' has no len()

notebooks/official/pipelines/custom_tabular_train_batch_pred_bq_pipeline.ipynb
<br>
Committing changes after running the linter test.
<br><br><br>
<br>
<br> …
=> ran linter test

notebooks/community/model_garden/model_garden_pytorch_dolly_v2.ipynb
revert change to docker URI
<br>
<br><br><br>
<br>
<br>
=> revert change to docker URI

notebooks/community/model_garden/model_garden_pytorch_sam.ipynb
Revert URI back to vertex-ai-restricted
<br>
<br><br><br>
<br>
<br>
=> Revert URI back to vertex-ai-restricted

notebooks/official/datasets/get_started_bq_datasets.ipynb
<br>
Fix reported issue 2121
<br><br><br>
<br>
<br> …
=> fix: issue 2121

notebooks/official/training/distributed_hyperparameter_tuning.ipynb
<br>
Fix reported issue
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vert …
=> fix: issue 1898

notebooks/official/pipelines/custom_tabular_train_batch_pred_bq_pipeline.ipynb
<br>
Apply boilerplate reduction to official
<br><br><br>
<br>
<br> …
=> feat: boiler plate reduction 54 - bigquery-public-data:ml_datasets.census_adult_income: not exist

notebooks/community/model_garden/model_garden_proprietary_image_object_detection.ipynb
<br>
Update documentation about only 2 GPUs are supported now.
<br><br><br>
<br>
=> Update documentation about only 2 GPUs are supported now.

community-content/CODEOWNERS, community-content/vertex_vision_model_garden/model_oss/data_converter/common_lib.py, community-content/vertex_vision_model_garden/model_oss/data_converter/convert_coco_label_map_iod.py, community-content/vertex_vision_model_garden/model_oss/data_converter/convert_imagenet_label_map.py, community-content/vertex_vision_model_garden/model_oss/data_converter/data_converter_icn_lib.py, community-content/vertex_vision_model_garden/model_oss/data_converter/data_converter_iod_lib.py, community-content/vertex_vision_model_garden/model_oss/data_converter/data_converter_isg_lib.py, community-content/vertex_vision_model_garden/model_oss/data_converter/data_converter_main.py, community-content/vertex_vision_model_garden/model_oss/data_converter/data_converter_vcn_lib.py, community-content/vertex_vision_model_garden/model_oss/data_converter/dockerfile/base.Dockerfile, community-content/vertex_vision_model_garden/model_oss/data_converter/dockerfile/run.Dockerfile, community-content/vertex_vision_model_garden/model_oss/movinet/dockerfile/base.Dockerfile, community-content/vertex_vision_model_garden/model_oss/movinet/dockerfile/model_export.Dockerfile, community-content/vertex_vision_model_garden/model_oss/movinet/dockerfile/serve.Dockerfile, community-content/vertex_vision_model_garden/model_oss/movinet/dockerfile/train.Dockerfile, community-content/vertex_vision_model_garden/model_oss/movinet/serving/serving_main.py, community-content/vertex_vision_model_garden/model_oss/movinet/serving/video_serving_lib.py, community-content/vertex_vision_model_garden/model_oss/movinet/train.py, community-content/vertex_vision_model_garden/model_oss/pic2word/handler.py, community-content/vertex_vision_model_garden/model_oss/util/commons.py, community-content/vertex_vision_model_garden/model_oss/util/constants.py, community-content/vertex_vision_model_garden/model_oss/util/fileutils.py, community-content/vertex_vision_model_garden/model_oss/util/hypertune_utils.py
Add data converter and movinet code to model garden
=> Add data converter and movinet code to model garden

community-content/CODEOWNERS, community-content/vertex_vision_model_garden/model_oss/open_clip/dockerfile/serve.Dockerfile, community-content/vertex_vision_model_garden/model_oss/open_clip/dockerfile/train.Dockerfile, community-content/vertex_vision_model_garden/model_oss/open_clip/handler.py
Add train/serve files for OpenCLIP.
<br>
<br><br><br>
<br>
<br>
=> Add train/serve files for OpenCLIP

notebooks/community/model_garden/model_garden_pipeline_templates_bert.ipynb
<br>
Updated to official standards and tested in WorkBench
<br><br><br>
<br>
<br> …
=> fix: official standard

notebooks/official/custom/get_started_with_vertex_endpoint_and_shared_vm.ipynb
<br>
Replace references to internal links with external doc links
<br><br><br>
<br>
<br> …
=> fix: replace internal links

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_open_clip.ipynb
**REQUIRED:** Add OpenCLIP notebook.
<br>
<br><br><br>
=> Add OpenCLIP notebook

notebooks/official/bigquery_ml/bqml-online-prediction.ipynb
<br>
The dataset used in this notebook has been removed from the public datasets. So, the necessary preprocessing steps are included to create the dataset from the publicly available source dataset. Additionally, changes related to the notebook template have been added.
<br><br><br>
<br> …
=> Adds preprocessing steps from the original dataset

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_jax_fvlm.ipynb
<br>
Add F-VLM notebook.
<br><br><br>
- [ x] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
=> Add F-VLM notebook.

notebooks/official/tabular_workflows/tabnet_on_vertex_pipelines.ipynb
<br>
This PR commits the following updates to the `notebooks/official/tabular_workflows/tabnet_on_vertex_pipelines.ipynb` file:
- updates content and its structure according to the template
- fixes grammatical errors
- removes duplicate parameters
- reduces the max_steps parameter to 100
<br><br><br>
<br>
2. If you are opening a PR for `Community …
=> Reduces the max_steps parameter + Textual content updates and fixes

notebooks/official/matching_engine/sdk_matching_engine_create_multimodal_embeddings.ipynb
Removed Memorystore reference since it isn't used.
=> fix: Removed Memorystore from sdk_matching_engine_create_multimodal_embeddings.ipynb

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
**REQUIRED:** Add a notebook for llama2 serving and finetuning with peft, and analyze with vertex text moderation API.
<br>
Add a notebook for llama2 serving and finetuning with peft, and analyze with vertex text moderation API
<br><br><br>
- [Y] Passes all the required formatting and linting checks. You …
=> Add a notebook for llama2 serving and finetuning with peft, and analyze with vertex text moderation API

notebooks/community/model_garden/model_garden_tfvision_image_object_detection.ipynb
Fix YOLOv7 config link
<br><br><br>
<br>
<br>
=> Fix YOLOv7 config link

notebooks/official/workbench/fraud_detection/fraud-detection-model.ipynb
<br>
This PR updates the `notebooks/official/workbench/fraud_detection/fraud-detection-model.ipynb` notebook and fixes the following from PR #1959 
- Updates sklearn SDK version to 1.2 to match with the latest prediction container version for the same. Also, the version mismatch is causing for a model registry create request timeout.
- Updates the pie chart creation step which is taking too long given the size the dataframe and the groupby process.
- Updates the random-forest model configuration to use parallel jobs for training.
- Adds relevant links and textual descriptions wherever needed/missed earlier.
- Section …
=> Reduction 88

notebooks/community/model_garden/model_garden_pytorch_falcon_instruct_peft.ipynb
Add local inference for Falcon Instruct.
<br><br><br>
<br>
<br>
=> Add local inference for Falcon Instruct.

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_xl_1_0.ipynb
<br>
Add the notebook for Stable Diffusion XL models.
<br><br><br>
=> Mg stable diffusion xl

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_keras_yolov8.ipynb
Add Keras YOLOv8 notebook.
<br><br><br>
<br>
<br>
=> Add Keras YOLOv8 notebook.

notebooks/official/model_monitoring/batch_prediction_model_monitoring.ipynb
<br>
This PR adds the following changes to the `notebooks/official/model_monitoring/batch_prediction_model_monitoring.ipynb` notebook and fixes the issues facing on PR #1871 :
- replace INPUT_GS_PATH with TRAINING_DATASET while copying data in GCS
- removes future tense
- clean up step for batch job
- moves the learn more section above the clean up section
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this …
=> Fixes the issues from PR#1871

notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
**REQUIRED:** Polish llama2 notebooks.
<br>
Polish llama2 notebooks
<br><br><br>
- [Y] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
<br>
=> Polish llama2 notebooks

notebooks/official/workbench/inventory-prediction/inventory_prediction.ipynb
<br>
This PR adds the following changes to the `notebooks/official/workbench/inventory-prediction/inventory_prediction.ipynb` notebook:
- fixes the sklearn versions 
- rewording the section titles and structural updates based on the notebook template
<br><br><br>
<br> …
=> Fixes the 400 model server issue

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_movinet_action_recognition.ipynb
Add Model Garden MoViNet action recognition notebook.
<br>
=> Add Model Garden MoViNet action recognition notebook

notebooks/community/model_garden/model_garden_pytorch_falcon_instruct_peft.ipynb, notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb, notebooks/community/model_garden/model_garden_pytorch_peft.ipynb
Add PEFT files for serving and training
<br>
<br>
=> Add PEFT train/serve files

notebooks/official/CODEOWNERS, notebooks/official/automl/automl_forecasting_on_vertex_pipelines.ipynb
=> Add notebook for Tabular Workflow for Forecasting

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_starcoder.ipynb
=> Add Model Garden StarCoder notebook.

community-content/vertex_vision_model_garden/model_oss/vot/dockerfile/serve.Dockerfile, community-content/vertex_vision_model_garden/model_oss/vot/handler.py, community-content/vertex_vision_model_garden/model_oss/vot/visualization_utils.py
<br>
Open source Bytetrack multi object tracking container to model garden.
<br><br><br>
<br>
<br> …
=> Open source Bytetrack multi object tracking container to model garden.

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_codellama.ipynb, notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
=> Add code-llama notebook

notebooks/community/model_garden/model_garden_pytorch_openllama_peft.ipynb
Add language model evaluation to OpenLLaMA + PEFT notebook.
<br>
=> Add language model evaluation to OpenLLaMA + PEFT notebook.

notebooks/community/model_garden/model_garden_movinet_action_recognition.ipynb, notebooks/community/model_garden/model_garden_movinet_clip_classification.ipynb
Revise Model Garden MoViNet notebooks according to dogfood feedbacks.
<br>
<br>
=> Revise Model Garden MoViNet notebooks

notebooks/official/pipelines/google_cloud_pipeline_components_dataproc_tabular.ipynb
<br>
This PR includes the following changes to the `notebooks/official/pipelines/google_cloud_pipeline_components_dataproc_tabular.ipynb` notebook and fixes the PR #1917 :
- Updates the mamba installation step and adds libmamba as solver
- Adds clean up step for removing experiment and local folders
- Adds a gcloud components update step for testing env (for creating artifact registry repo)
- Updates the services needed to be enabled under Before you begin section
<br><br><br> …
=> Fixes the build failure

notebooks/community/model_garden/model_garden_pytorch_falcon_instruct_peft.ipynb
Add language model evaluation to Falcon Instruct + PEFT notebook.
<br>
=> Add language model evaluation to Falcon Instruct + PEFT notebook.

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_mediapipe_face_stylizer.ipynb
This is the FaceStylizer notebook for MediaPipe.
=> Add Face Stylizer notebook

community-content/vertex_vision_model_garden/model_oss/timm/dockerfile/serve.Dockerfile, community-content/vertex_vision_model_garden/model_oss/timm/dockerfile/train.Dockerfile, community-content/vertex_vision_model_garden/model_oss/timm/handler.py
<br>
Manually release oss TIMM source code and dockerfiles to model garden
<br><br><br>
<br>
<br> …
=> Manually release oss TIMM source code and dockerfiles to model garden.

notebooks/community/model_garden/model_garden_pytorch_openllama_peft.ipynb
<br>
Update open-llama notebook by making vLLM the default serving option.
<br><br><br>
<br>
<br> …
=> Update open-llama notebook by making vLLM the default serving option.

notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
**REQUIRED:** Minor updatesfor LLaMA2 notebooks with clear instructions
<br>
Minor updatesfor LLaMA2 notebooks with clear instructions
<br><br><br>
- [Y] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-s …
=> Minor updatesfor LLaMA2 notebooks with clear instructions

notebooks/community/model_garden/model_garden_jax_fvlm.ipynb
<br>
Add F-VLM model training with TPU example in addition to the existing serving.
<br><br><br>
=> Add F-VLM training.

community-content/vertex_vision_model_garden/model_oss/vllm/dockerfile/serve.Dockerfile, community-content/vertex_vision_model_garden/model_oss/vllm/vllm.patch
<br>
Manually release oss vLLM source code and dockerfiles to model garden.
<br><br><br>
<br>
<br> …
=> Manually release oss vLLM source code and dockerfiles to model garden.

notebooks/official/custom/get_started_with_vertex_endpoint_and_shared_vm.ipynb
fix: investigate a weekly regression error "500 Internal error encountered" (b/300747956)
Remove a hardcoded debug code cell from the notebook.
=> fix: investigate a weekly regression error - remove a hardcoded debug code cell

notebooks/official/generative_ai/batch_eval_llm.ipynb
<br>
Updates post Cloud Next
<br><br><br>
<br>
<br> …
=> update: post-Next

notebooks/official/CODEOWNERS, notebooks/official/generative_ai/text_embedding_new_api.ipynb
<br>
Add embedding new API colab to the official folder.
<br><br><br>
<br>
<br> …
=> Add embedding new API colab to the official folder.

notebooks/official/prediction/llm_streaming_prediction.ipynb
<br>
Add streaming prediction notebook
<br><br><br>
<br>
<br> …
=> feat: streaming prediction

notebooks/community/model_garden/model_garden_pytorch_openllama_peft.ipynb
<br>
Make vLLM the default serving option for open llama peft<br><br><br>
<br>
<br> …
=> Make vLLM the default serving option for open llama peft

notebooks/official/sdk/sdk2_bigframes_tensorflow.ipynb
<br>
Official sample notebook for SDK 2.0 Bigframes Tensorflow Integration
<br><br><br>
=> Add SDK 2.0 Bigframes Tensorflow sample notebook

notebooks/official/training/sdk2_remote_hyperparameter_tuning.ipynb
<br>
Add notebook for official
<br><br><br>
<br>
<br> …
=> feat: SDK2 remote tuning

notebooks/official/training/sdk2_remote_training.ipynb
<br>
new notebook for official
<br><br><br>
<br>
<br> …
=> feat: SDK2 remote training

notebooks/official/model_registry/bqml_vertexai_model_registry.ipynb
<br>
Fix CI/CD failure
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/verte …
=> fix: CI/CD failure

notebooks/official/model_monitoring/batch_prediction_model_monitoring.ipynb
<br>
Fine tune and verify it works
<br><br><br>
<br>
<br> …
=> debug: verify works

notebooks/official/sdk/sdk2_bigframes_pytorch.ipynb, notebooks/official/sdk/sdk2_bigframes_sklearn.ipynb, notebooks/official/sdk/sdk2_bigframes_tensorflow.ipynb
<br>
Minor changes for wording in bigframes sklearn and bigframes pytorch notebooks to make wording consistent
<br><br><br>
=> Make SDK 2.0 bigframes notebook wording consistent

notebooks/official/experiments/build_model_experimentation_lineage_with_prebuild_code.ipynb
=> Update pre-built to prebuilt

community-content/vertex_vision_model_garden/model_oss/detectron2/dockerfile/serving.Dockerfile, community-content/vertex_vision_model_garden/model_oss/detectron2/dockerfile/train.Dockerfile, community-content/vertex_vision_model_garden/model_oss/detectron2/handler.py, community-content/vertex_vision_model_garden/model_oss/detectron2/trainer_utils.py
<br>
Open source detectron2 handler and trainer scripts and dockerfiles.
<br><br><br>
<br>
<br> …
=> Open source detectron2 handler and trainer scripts and dockerfiles.

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_nllb.ipynb, notebooks/official/experiments/build_model_experimentation_lineage_with_prebuild_code.ipynb
<br>
Add a notebook example for the NLLB model in model garden
<br><br><br>
<br>
<br> …
=> Add a notebook example for the NLLB model in model garden

notebooks/community/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
=> feat: add BigFrames gen-ai notebook for a use case about drug

notebooks/official/pipelines/pipelines_intro_kfp.ipynb
=> port: KFP2

community-content/vertex_vision_model_garden/model_oss/jax_vision_transformer/dockerfile/jax_vit_model_conversion.Dockerfile, community-content/vertex_vision_model_garden/model_oss/jax_vision_transformer/dockerfile/train_vit_gpu.Dockerfile, community-content/vertex_vision_model_garden/model_oss/jax_vision_transformer/vit_config_without_data.py
<br>
Open source jax vision transformer to model garden.
<br><br><br>
<br>
<br> …
=> Open source jax vision transformer to model garden.

notebooks/community/generative_ai/bq_dataframes_llm_code_generation.ipynb
=> feat: add BigFrames llm code notebooks in generative_ai 

notebooks/official/pipelines/get_started_with_hpt_pipeline_components.ipynb
<br>
cannot port at present to 2.x
<br><br><br>
<br>
<br> …
=> fix: notice

notebooks/official/pipelines/challenger_vs_blessed_deployment_method.ipynb
=> kfp: notice

notebooks/community/model_garden/model_garden_pytorch_biogpt_serve.ipynb.txt
<br>
Add BioGPT to Vertex AI Model Garden.
<br><br><br>
<br>
<br> …
=> Add BioGPT to Vertex AI Model Garden.

notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings_vertex.ipynb
<br>
fix to pass CI/CD
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/verte …
=> fix: remove redis and rebrand

notebooks/official/matching_engine/sdk_matching_engine_create_multimodal_embeddings.ipynb
=> fix: rebrand/clean

notebooks/community/matching_engine/matching_engine_for_indexing.ipynb
=> fix: rebrand

notebooks/community/model_garden/model_garden_pytorch_codellama.ipynb, notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb, notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb, notebooks/community/model_garden/model_garden_pytorch_openllama_peft.ipynb
**REQUIRED:** Add streaming to model garden llm notebooks
=> Add streaming to model garden llm notebooks

notebooks/official/tensorboard/tensorboard_vertex_ai_pipelines_integration.ipynb
=> debug: CI/CD failure

notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb
**REQUIRED:** Upgrade deps version for Mistral model
=> Upgrade deps version for Mistral model

notebooks/official/feature_store/feature_store_streaming_ingestion_sdk.ipynb, notebooks/official/feature_store/sdk-feature-store.ipynb
chore: rebranding to Vertex AI Feature Store (Legacy)
Feature Store rebranding to "Vertex AI Feature Store (Legacy)" and a few editorial fixes.
=> Miscellaneous editorial fixes and rebranding to "Vertex AI Feature Store (Legacy)"

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_biomedclip.ipynb
Add #ModelGarden BiomedCLIP notebook.
<br>
<br>
=> Add #ModelGarden BiomedCLIP notebook.

notebooks/community/model_garden/model_garden_pytorch_dolly_v2.ipynb
Add model evaluation to Dolly V2 notebook.
<br>
<br>
=> Add model evaluation to Dolly V2 notebook.

notebooks/community/model_garden/model_garden_pytorch_falcon_instruct_peft.ipynb, notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb, notebooks/community/model_garden/model_garden_pytorch_openllama_peft.ipynb, notebooks/community/model_garden/model_garden_pytorch_peft.ipynb
Add custom dataset support to #ModelGarden PEFT notebooks
<br>
This is an update to existing notebooks.
<br><br><br>
<br>
<br>
=> Add custom dataset support to #ModelGarden PEFT notebooks

notebooks/community/model_garden/model_garden_mediapipe_image_generation.ipynb
Update MediaPipe Image Generator notebook with latest changes
- [x ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
=> Update MediaPipe Image Generator notebook with latest changes

notebooks/official/tensorboard/tensorboard_custom_training_with_prebuilt_container.ipynb
=> CI/CD: debug fail

notebooks/official/experiments/get_started_with_custom_training_autologging_local_script.ipynb
=> Debug CI/CD failure

notebooks/notebook_template_review.py
<br>
Make handling notebook title more robust.
<br><br><br>
<br>
<br> …
=> fix: handling H1 heading

notebooks/official/generative_ai/vertex_sdk_llm_snippets.ipynb
=> fix: missing learn more about

notebooks/community/CODEOWNERS
<br>
Fix CODEOWNERS change due to merge conflict.<br><br><br>
=> Fix CODEOWNERS change due to merge conflict.

notebooks/official/generative_ai/rlhf_tune_llm.ipynb
=> fix: add missing learn about

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_imagebind.ipynb
=> Add ImageBind notebook.

.cloud-build/execute_changed_notebooks_helper.py, .cloud-build/notebook-execution-test-cloudbuild.yaml, .cloud-build/utils/NotebookProcessors.py, notebooks/official/matching_engine/sdk_matching_engine_for_indexing.ipynb
=> rebrand and clean

notebooks/official/prediction/get_started_with_vertex_private_endpoints.ipynb
=> migrate to official

notebooks/community/model_garden/model_garden_pytorch_imagebind.ipynb
Update deployment recommendations in ImageBind notebook.
<br>
=> Update deployment recommendations in ImageBind notebook.

notebooks/official/automl/automl_forecasting_bqml_arima_plus_comparison.ipynb
=> fix CI/CD failure

.cloud-build/web-index/do_not_index.txt
<br>
notebooks that do not yet have a webdoc page should not be in webdoc index
<br><br><br>
<br>
<br> …
=> clean: not index notebooks w/o webdoc page

.cloud-build/web-index/do_not_index.txt
=> fix: filename only not path

notebooks/community/model_garden/model_garden_pytorch_vicuna.ipynb
Force local inference to GPU, fix section name. 
<br>
<br><br><br>
<br>
<br>
=> Minor updates to Vicuna notebook.

notebooks/community/model_garden/model_garden_pytorch_nllb.ipynb
<br>
Pin the transformer-serve version in the NLLB notebook
<br><br><br>
<br>
<br> …
=> Pin the transformer-serve version in the NLLB notebook

.cloud-build/web-index/notebook-index-cloudbuild.yaml
=> feat: add option for files not to index

.cloud-build/execute_changed_notebooks_helper.py
=> feat: select notebook if failed on last run

.cloud-build/run_first.csv
=> add more notebooks to list

notebooks/official/experiments/get_started_with_vertex_experiments.ipynb
=> fix CI/CD error

.cloud-build/execute_changed_notebooks_helper.py
<br>
Work to support a future dashboard
<br><br><br>
<br>
<br> …
=> feat: record last date of fail

notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings.ipynb
=> fix: clean and rebrand - permission

notebooks/notebook_template.ipynb
Address user feedback.
Remove unnecessary comments from the notebook template.
=> chore: remove unnecessary comments from the template

notebooks/community/model_garden/model_garden_pytorch_vicuna.ipynb
Fix VLLM format string.
<br>
<br><br><br>
<br>
<br>
=> Fix VLLM format string.

notebooks/official/generative_ai/text_embedding_new_api.ipynb
<br>
Change model version from latest to stable.
<br><br><br>
<br>
<br> …
=> Change model version from latest to stable.

notebooks/official/bigquery_ml/get_started_with_bqml_training.ipynb
=> fix: unreliable service

.cloud-build/run_first.csv
=> fix: timeouts

notebooks/community/model_garden/model_garden_pytorch_biogpt_serve.ipynb
<br>
Update BioGPT serve docker URI in notebook.
<br><br><br>
<br>
<br> …
=> Update BioGPT serve docker URI in notebook.

.cloud-build/notebook-execution-test-cloudbuild.yaml
=> feat: add arg for run first file

.cloud-build/execute_changed_notebooks_helper.py
=> fix: last date ran

.cloud-build/web-index/do_not_index.txt, notebooks/notebook_template_review.py
=> fix: skipping in indexer

.cloud-build/run_first.csv
=> fix: timeout

.cloud-build/execute_changed_notebooks_cli.py
=> fix: protect harness from system wide execution failure

notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
Add hyperparameter tuning instructions to llama2 PEFT notebook
<br>
This is an update to an existing notebook.
=> Add hyperparameter tuning instructions to llama2 PEFT notebook

.cloud-build/execute_changed_notebooks_helper.py
=> feat: detect error from log

.cloud-build/execute_changed_notebooks_helper.py
=> debug: saving results

.cloud-build/utils/build_results_viewer.py
=> fix: read from local file

notebooks/official/feature_store/online_feature_serving_and_fetching_bigquery_data_with_feature_store_optimized.ipynb
=> Rephrase optimized notebook to address previous comment

.cloud-build/execute_changed_notebooks_cli.py, .cloud-build/execute_changed_notebooks_helper.py
=> fix: bug in selection algo for age and max notebooks

notebooks/official/generative_ai/rlhf_tune_llm.ipynb
<br>
Fix for reported issue
<br><br><br>
<br>
<br> …
=> fix: missing link

notebooks/official/vertex_ai_sdk/remote_training_bigframes_tensorflow.ipynb
<br>
tensorflow-io is now installed automatically on the remote training job.
<br><br><br>
=> [Vertex AI SDK] Remove bigframes tf-io installation on user side

.cloud-build/execute_changed_notebooks_cli.py
=> fix syntax error

notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings_vertex.ipynb
=> pin to fix CI/CD failure

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_2_1.ipynb
…ker.
<br>
Update stable diffusion 2.1 notebook to use the optimized serving docker
<br><br><br>
<br>
<br> …
=> Update stable diffusion 2.1 notebook to use the optimized serving docker

notebooks/community/CODEOWNERS, notebooks/community/vision/image_warehouse_sdk.ipynb
Add a notebook for image warehouse
<br>
<br><br><br>
- [ Y ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks). …
=> create a notebook for image warehouse

.cloud-build/utils/build_results_viewer.py
=> feat: finish round1 of dirty dashboard

.cloud-build/execute_changed_notebooks_helper.py
=> add log url

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
<br>
Temporarily pin the  docker to 20231112_0948_RC00.
<br><br><br>
<br>
<br> …
=> Temporarily pin the  docker to 20231112_0948_RC00.

notebooks/community/vision/image_warehouse_sdk.ipynb
<br>
1. remove the step in the authentication cell which is not relevant to warehouse product.
2. Use ipywidgets instead of colab.widgets so that it can run in Jupyter
<br><br><br>
3. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
- [ Y] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md# …
=> fix: fix image rending for running in Jupyter

notebooks/official/experiments/build_model_experimentation_lineage_with_prebuild_code.ipynb
=> Update CI/CD debug

.cloud-build/cleanup/resource_cleanup_manager.py
<br>
per review session with Eric Dong
<br><br><br>
<br>
<br> …
=> documented what to do for FS 2.x cleanup

notebooks/community/vision/video_warehouse_sdk.ipynb
<br>
improve the auth section to make it more aligned with the template
<br><br><br>
- [Y ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
<br>
=> improve to make it more aligned with the template

notebooks/community/model_garden/model_garden_pytorch_peft.ipynb
This is an update to an existing notebook: Update serving container version for sequence classification models.
<br>
=> Update serving container version for sequence classification models.

notebooks/official/feature_store/online_feature_serving_and_vector_retrieval_bigquery_data_with_feature_store.ipynb
<br>
-  Removes known issues section and updates disclaimer.
<br><br><br>
=> Update vector notebook to remove disclaimer

.cloud-build/utils/build_results_viewer.py
=> feat: auto find latest build results

notebooks/official/feature_store/online_feature_serving_and_fetching_bigquery_data_with_feature_store_optimized.ipynb
<br>
-  Removes known issues section and updates disclaimer.
<br><br><br>
=> Updates disclaimer for optimized notebook

notebooks/official/feature_store/online_feature_serving_and_fetching_bigquery_data_with_feature_store_bigtable.ipynb
<br>
-  Removes known issues section and updates disclaimer.
<br><br><br>
=> Use publicly available SDK version over github version 

notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings.ipynb
=> Update CI/CD fix

.cloud-build/cleanup/cleanup.py, .cloud-build/cleanup/resource_cleanup_manager.py
=> feat: stub and document reaper support for FS 2.x

.cloud-build/execute_changed_notebooks_helper.py
=> fix: detect other types of quota and internal errors

.cloud-build/cleanup/resource_cleanup_manager.py
=> fix: cleanup for FS 2.x

.cloud-build/execute_changed_notebooks_helper.py
=> fix: typo in results vs result

.cloud-build/execute_changed_notebooks_helper.py
=> fix: detecting internal

notebooks/community/model_garden/model_garden_jax_dito.ipynb
<br>
Support DITO custom categories
<br>
=> Support DITO custom categories

notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
Add quantization to llama2 notebook
<br>
<br><br><br>
<br>
<br>
=> Add quantization to llama2 notebook

.cloud-build/execute_changed_notebooks_cli.py, .cloud-build/execute_changed_notebooks_helper.py, .cloud-build/utils/NotebookProcessors.py
=> in-progress: SDK whl replacement

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_openllama_7b_finetune_tutorial.md
<br>
Add openllama-7b fine tuning benchmark report.
<br><br><br>
<br>
<br> …
=> Add openllama-7b fine tuning benchmark report.

notebooks/notebook_template_review.py
=> fix: backticks

.cloud-build/cleanup/cleanup.py
=> fix: online FS

community-content/vertex_vision_model_garden/benchmarking_reports/pytorch_openllama_hyperparameter_tuning_benchmark_report.md
Add OpenLLaMA hyperparameter tuning benchmark report (Model Garden)
<br>
=> Add OpenLLaMA hyperparameter tuning benchmark report

notebooks/community/model_garden/model_garden_pytorch_codellama.ipynb, notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb
This updates existing notebooks: Add evaluation for CodeLLaMA and fix typos for CodeLLaMA and Mistral.
<br>
=> Add evaluation for CodeLLaMA and fix typos for CodeLLaMA and Mistral.

community-content/vertex_model_garden/benchmarking_reports/pytorch_openllama_hyperparameter_tuning_benchmark_report.md, community-content/vertex_model_garden/benchmarking_reports/stable_diffusion_v1-5_benchmarking_report.md
**REQUIRED:** use the vertex_model_garden links instead of vertex_vision_model_garden
<br>
use the vertex_model_garden links instead of vertex_vision_model_garden
<br><br><br>
- [Y] Make sure your main `Content Directory Name` is descriptive, informative, and includes some of the key products and attributes of your content, so that it is differentiable from other content
- [Y] The main content directory has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/CODEOWNERS) file under the …
=> use the vertex_model_garden links instead of vertex_vision_model_garden

notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb, notebooks/community/model_garden/model_garden_pytorch_llama2_quantization.ipynb
Add cache_examples_on_gpu flag to GPTQ.
<br>
<br><br><br>
<br>
<br>
=> Add cache_examples_on_gpu flag to GPTQ.

notebooks/community/model_garden/model_garden_pytorch_detectron2.ipynb
<br>
Use open source detectron2 docker.<br><br><br>
=> Use open source detectron2 docker.

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_xl_1_0.ipynb, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_xl_lcm.ipynb
<br>
Add a new notebook for sdxl LCM
<br><br><br>
<br>
<br> …
=> Add a new notebook for sdxl LCM

notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb
This is an update to an existing notebook: Add Mixtral 8x7B to Mistral notebook.
<br>
=> Add Mixtral 8x7B to Mistral notebook.

notebooks/official/generative_ai/vertex_sdk_llm_snippets.ipynb
Fix b/316197647
Bad link to PaLM API.
=> Fix: bad link to PaLM

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_wizard_coder.ipynb
Add #ModelGarden wizard coder notebook
<br>
=> Add #ModelGarden wizard coder notebook

notebooks/official/training/multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb
<br>
Update workbook title to mention Vertex AI
<br><br><br>
<br>
<br> …
=> Update workbook title to mention Vertex AI

notebooks/official/custom/custom_training_tensorboard_profiler.ipynb
Updated Profiler, Vertex AI TensorBoard Profiler, and TensorBoard Profiler instances to Cloud Profiler within text cells to reflect correct naming.
=> Fix: update name to cloud profiler

notebooks/official/training/get_started_with_vertex_distributed_training.ipynb
Lowercase instances of "Distributed Training"
=> Fix: lowercase distributed training

notebooks/community/pipelines/google_cloud_pipeline_components_ready_to_go_text_classification_pipeline.ipynb
Fix a Python line in google_cloud_pipeline_components_ready_to_go_text_classification_pipeline.ipynb, with other minor fixes and rewording to specify that older pipeline components library is neeeded
<br>
2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/ …
=> Fix ready_to_go text classification pipeline notebook

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_wizard_lm.ipynb
Add #ModelGarden Wizard LM notebook
<br>
=> Add #ModelGarden Wizard LM notebook

notebooks/official/pipelines/get_started_with_hpt_pipeline_components.ipynb
Lowercase "hyperparameter tuning" within text cells
=> Fix: lowercase hyperparameter tuning within text cells

notebooks/community/model_garden/model_garden_pytorch_stable_video_diffusion_img2vid_xt.ipynb
=> notebook for stable video diffusion img2vid xt

notebooks/community/model_garden/model_garden_pytorch_zipnerf.ipynb
<br>
Added individual download links for mipnerf360 dataset.
<br><br><br>
<br>
<br> …
=> Added individual download links for mipnerf360 dataset.

notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb
This is an update to an existing notebook: Update Mixtral vLLM container and support OpenAI vLLM server.
<br>
=> Update Mixtral vLLM container and support OpenAI vLLM server.

community-content/vertex_pipeline_kfpv2/README.md, community-content/vertex_pipeline_kfpv2/create-endpoint.py, community-content/vertex_pipeline_kfpv2/deploy-model.py, community-content/vertex_pipeline_kfpv2/train-model.py
--- PR SUMMARY ---
Upload 3 examples of kfp v2. Here are create endpoint, train model and deploy model.
=> Upload examples of kfp v2

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_autogluon.ipynb
<br>
Adding AutoGluon notebook for Vertex AI Model Garden.
<br><br><br>
- [x ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
=> Add AutoGluon notebook.

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb
<br>
Update/optimize the serving efficiency of the image-inpainting model.
<br><br><br>
<br>
<br> …
=> Update/optimize the serving efficiency of the image-inpainting model.

notebooks/official/generative_ai/distillation.ipynb
<br>
Add a new notebook to support vertex distillation.
<br><br><br>
<br>
<br>
=> <feat>: add sample notebook for vertex distillation

notebooks/official/custom/sdk-custom-image-classification-batch.ipynb
Small edit - first time making a change to a github sample.
=> Small edit - first time making a change to a github sample.

community-content/vertex_model_garden/model_oss/peft/handler.py
=> Add Peft additional parameters

notebooks/notebook_template_review.py, notebooks/official/experiments/get_started_with_vertex_experiments_autologging.ipynb
Dealing with numerous text edits. Does not impact code
=> Dealing with numerous text edits. Does not impact code

notebooks/community/model_garden/model_garden_jax_stable_diffusion_xl.ipynb
<br>
Add a notebook with example on deploying SDXL model on TPU v5e
<br><br><br>
<br>
<br> …
=> Add a notebook with example on deploying SDXL model on TPU v5e

notebooks/official/pipelines/get_started_with_hpt_pipeline_components.ipynb
Fixed typos and rewrote some sentences to make them clearer. Be sure to check that I didn't change the meaning or intent. No code impacted
=> Fixed typos and rewrote some sentences to make them clearer. Be sure to check that I didn't change the meaning or intent. No code impacted

community-content/CODEOWNERS, community-content/vertex_model_garden/model_oss/autogluon/dockerfile/autogluon_serve.Dockerfile, community-content/vertex_model_garden/model_oss/autogluon/dockerfile/autogluon_train.Dockerfile, community-content/vertex_model_garden/model_oss/autogluon/serve.py, community-content/vertex_model_garden/model_oss/autogluon/train.py
<br>
Add AutoGluon source files.
<br><br><br>
- [ x] Make sure your main `Content Directory Name` is descriptive, informative, and includes some of the key products and attributes of your content, so that it is differentiable from other content
- [ x] The main content directory has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/CODEOWNERS) file under the `Community Content` section, pointing to the author or the author's team.
- [ x] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
=> Autogluon source

notebooks/official/CODEOWNERS, notebooks/official/tabular_workflows/automl_forecasting_bqml_arima_plus_comparison.ipynb, notebooks/official/tabular_workflows/bqml_arima_plus.ipynb, notebooks/official/tabular_workflows/prophet_on_vertex_pipelines.ipynb
<br>
Moves the ARIMA notebook back under official and updates it and the Prophet notebook's GCPC version. Removes the comparison with Vertex Forecasting section to make the ARIMA notebook more stable.
<br><br><br>
=> Update Prophet and ARIMA notebook GCPC versions

notebooks/official/tensorboard/tensorboard_vertex_ai_pipelines_integration.ipynb
Change url for viewing TensorBoard data.
=> Change url for viewing TensorBoard data.

notebooks/official/automl/sdk_automl_video_classification_batch.ipynb
Numerous edits to "Vertex AI SDK: AutoML training video classification model for batch prediction". Does not impact code.
=> Numerous edits to "Vertex AI SDK: AutoML training video classification model for batch prediction". Does not impact code.

notebooks/community/model_garden/model_garden_pytorch_codellama.ipynb
<br>
Increase default max-num-batched-tokens to 16385 for larger models.
<br><br><br>
<br>
=> Increase default max-num-batched-tokens to 16385 for larger models.

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_upscaler.ipynb
Fix upscaler notebook
<br>
<br><br><br>
<br>
<br>
=> Fix upscaler notebook

notebooks/official/experiments/delete_outdated_tensorboard_experiments.ipynb
Made edits to "Delete Outdated Experiments in Vertex AI TensorBoard". Updated URL(s). Code not impacted
=> Made edits to "Delete Outdated Experiments in Vertex AI TensorBoard". Updated URL(s).

notebooks/official/experiments/get_started_with_custom_training_autologging_local_script.ipynb
Made edits to "Vertex AI Experiments: Custom training autologging - Local script" and added link to relevant documentation. No impact on code
=> Made edits to "Vertex AI Experiments: Custom training autologging - Local script" and added link to relevant documentation. No impact on code

community-content/vertex_model_garden/model_oss/cloudnerf/configs/360.gin, community-content/vertex_model_garden/model_oss/cloudnerf/configs/360_glo.gin, community-content/vertex_model_garden/model_oss/cloudnerf/configs/accelerate_config.yaml, community-content/vertex_model_garden/model_oss/cloudnerf/dockerfile/pytorch_cloudnerf_base.Dockerfile, community-content/vertex_model_garden/model_oss/cloudnerf/dockerfile/pytorch_cloudnerf_calibrate.Dockerfile, community-content/vertex_model_garden/model_oss/cloudnerf/dockerfile/pytorch_cloudnerf_render.Dockerfile, community-content/vertex_model_garden/model_oss/cloudnerf/dockerfile/pytorch_cloudnerf_train.Dockerfile, community-content/vertex_model_garden/model_oss/cloudnerf/local_colmap_and_resize.sh, community-content/vertex_model_garden/model_oss/cloudnerf/render.sh, community-content/vertex_model_garden/model_oss/cloudnerf/requirements.txt, community-content/vertex_model_garden/model_oss/cloudnerf/train.sh
<br>
Open source pytorch zipnerf model garden dockers.
<br><br><br>
<br>
<br> …
=> Open source pytorch zipnerf model garden dockers.

notebooks/official/tensorboard/tensorboard_custom_training_with_custom_container.ipynb
Made edits to "Vertex AI TensorBoard custom training with custom container". Fixed typos and cleaned up content. No impact on code
=> Made edits to "Vertex AI TensorBoard custom training with custom container". Fixed typos and cleaned up content. No impact on code

notebooks/official/tensorboard/tensorboard_custom_training_with_prebuilt_container.ipynb
Edited "Vertex AI TensorBoard custom training with prebuilt container" No impact on code.
=> Edited "Vertex AI TensorBoard custom training with prebuilt container" No impact on code.

notebooks/community/model_garden/model_garden_pytorch_llama2_quantization.ipynb
Update quantization docker for LLaMA2
<br>
<br><br><br>
<br>
<br>
=> Update quantization docker for LLaMA2

notebooks/official/CODEOWNERS, notebooks/official/ray_on_vertex_ai/get_started_with_pytorch_rov.ipynb
<br>
This tutorial demostrates how to use Ray on Vertex AI SDK and Vertex AI SDK for training and serving an PyTorch image classification model.
<br><br><br>
=> feat: ray on vertex - torch sample

notebooks/community/CODEOWNERS, notebooks/community/model_garden/model_garden_pytorch_mistral_peft_tuning.ipynb, notebooks/community/model_garden/model_garden_pytorch_mixtral_peft_tuning.ipynb
Add mistral and mixtral model PEFT fine-tuning notebooks
<br>
=> Add mistral and mixtral model PEFT fine-tuning notebooks

notebooks/community/model_garden/model_garden_gemma_deployment_on_vertex.ipynb, notebooks/community/model_garden/model_garden_gemma_finetuning_on_vertex.ipynb
This CL updates existing notebooks: Update Gemma deployment and finetuning notebook descriptions.
<br>
=> Update Gemma deployment and finetuning notebook descriptions.

notebooks/official/tensorboard/tensorboard_custom_training_with_custom_container.ipynb
Changed "Vertex AI training" to "Vertex AI Training"
=> Changed "Vertex AI training" to "Vertex AI Training"

notebooks/official/matching_engine/sdk_matching_engine_for_indexing.ipynb
Edited "Create Vertex AI Vector Search index". Updated a URL to avoid a redirect. No impact on code
=> Edited "Create Vertex AI Vector Search index". Updated a URL to avoid a redirect. No impact on code

notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings_vertex.ipynb
Edited "Using Vertex AI Vector Search and Vertex AI embeddings for text for StackOverflow Questions" Fixed one URL to remove redirect.
=> Edited "Using Vertex AI Vector Search and Vertex AI embeddings for text for StackOverflow Questions" Fixed one URL to remove redirect.

notebooks/official/automl/automl-text-classification.ipynb
Edited "Vertex AI: Create, train, and deploy an AutoML text classification model" Updated URLS.
=> Edited "Vertex AI: Create, train, and deploy an AutoML text classification model" Updated URLS.

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_finetuning_dreambooth_1_5.ipynb, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_finetuning_dreambooth_lora_1_5.ipynb, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_finetuning_lora_1_5.ipynb
=> Add 3 SD 1.5 finetuning notebooks.

notebooks/official/tensorboard/tensorboard_custom_training_with_prebuilt_container.ipynb
Changed "Vertex AI training" to "Vertex AI Training
=> Changed "Vertex AI training" to "Vertex AI Training

notebooks/official/matching_engine/sdk_matching_engine_create_multimodal_embeddings.ipynb
Edit "Using Vertex AI Multimodal Embeddings and Vector Search". Updated links to point to new directory /vector-search/. No impact on code
=> Edit "Using Vertex AI Multimodal Embeddings and Vector Search". Updated links to point to new directory /vector-search/. No impact on code

notebooks/official/automl/sdk_automl_video_classification_batch.ipynb, notebooks/official/tensorboard/tensorboard_custom_training_with_prebuilt_container.ipynb
Changed "Vertex AI training" to "Vertex AI Training"
=> Vertex-ai-training-typo-3

notebooks/official/pipelines/custom_model_training_and_batch_prediction.ipynb
Added missing link and made other edits to "Custom training with pre-built Google Cloud Pipeline Components". No impact on code
=> Added missing link and made other edits to "Custom training with pre-built Google Cloud Pipeline Components". No impact on code

notebooks/official/automl/automl_forecasting_on_vertex_pipelines.ipynb
Edited "Tabular Workflow for Forecasting". No impact on code.
=> Edited "Tabular Workflow for Forecasting". No impact on code.

community-content/vertex_model_garden/model_oss/pic2word/dockerfile/serve.Dockerfile, community-content/vertex_model_garden/model_oss/pic2word/handler.py, notebooks/community/model_garden/model_garden_pytorch_pic2word.ipynb
<br>
Update Pic2Word notebook
1. Streamline and combine steps for ease of use
2. Update the prediction request format
<br><br><br>
<br>
3. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
<br>
=> refactor: Simplify Pic2Word notebook steps

notebooks/community/model_garden/model_garden_camp_zipnerf.ipynb
<br>
Add camp zipnerf jax implementation to model garden.
<br><br><br>
<br>
<br> …
=> Add camp zipnerf jax implementation to model garden.

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_xl_1_0.ipynb
…rience.
<br>
Rewrite the SDXL - vertex serving notebook for the low-code user experience.
<br><br><br>
<br>
<br> …
=> Rewrite the SDXL - vertex serving notebook for the low-code user experience.

community-content/vertex_model_garden/model_oss/vllm/dockerfile/serve.Dockerfile, community-content/vertex_model_garden/model_oss/vllm/vllm.patch, community-content/vertex_model_garden/model_oss/vllm/vllm_startup_prober.sh
This PR updates existing code for the vLLM docker.
<br>
=> Update vLLM dockerfile.

community-content/CODEOWNERS, community-content/vertex_model_garden/model_oss/vllm/vllm.patch
Fix corrupted vllm.patch file due to merge conflicts not be resolved correctly
Sorry that some of the automatically merged changes were incorrect and I pushed the changes without realizing this. In this PR, I manually copied the file from the source of truth.
=> Fix corrupted vllm.patch file due to merge conflicts not be resolved correctly

notebooks/official/CODEOWNERS, notebooks/official/feature_store/vertex_ai_feature_store_feature_view_service_agents.ipynb
<br>
Adds a Python notebook tutorial demonstrating an end to end Vertex AI Feature Store workflow that enables FeatureView Service Agents.
<br><br><br>
<br>
<br>
3. If …
=> Vertex AI Feature Store Notebook, Feature View Service Agent

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_gradio.ipynb
=> Some minor fixed to the `stable-diffusion-gradio` notebook.

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_gradio.ipynb, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_xl_1_0.ipynb
=> Fix the deployment error of the `SDXL-REFINER` model in the notebook.

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_gradio.ipynb, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_xl_1_0.ipynb
=> Update the logic of cleaning up the GCS bucket_uri in the sdxl notebook.

notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb
This PR updates an existing notebook: Update config and add Mistral v0.2 in Mistral/Mixtral notebook.
<br>
=> Update config and add Mistral v0.2 in Mistral/Mixtral notebook.

notebooks/community/CODEOWNERS, notebooks/community/vision/video_warehouse_curl.ipynb
<br>
Add a colab of examples to issue curl commands to Video Warehouse.
<br><br><br>
- [Y ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
<br>
=> feat: add curl colab for video warehouse

notebooks/community/model_garden/model_garden_pytorch_pic2word.ipynb
This PR updates an existing notebook: Update docker link for pic2word serving.
<br>
=> Update docker link for pic2word serving.

notebooks/official/generative_ai/text_embedding_new_api.ipynb
<br>
Elastic Text-Embedding demo for Google Cloud Next '24 (Apr. 9-11, 2024).
<br><br><br>
=> feat: Elastic Text-Embedding demo.

notebooks/community/model_garden/model_garden_pytorch_llama2_peft_hyperparameter_tuning.ipynb
This is an update to an existing notebook.
=> Update Model Garden Llama2 HPT notebook to low-code version

notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb, notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_custom.ipynb, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_upscaler.ipynb
=> Update notebooks to no-code/low-code

notebooks/notebook_template.ipynb
Update notebook template
- Add information about enabling Vertex AI API, and setting up a project
=> chore: Update template

notebooks/official/generative_ai/text_embedding_new_api.ipynb
<br>
Elastic Text-Embedding demo for Google Cloud Next '24 (Apr. 9-11, 2024).
<br><br><br>
=> feat: Elastic Text-Embedding Model demo.

notebooks/community/model_garden/model_garden_pytorch_gemma_peft_finetuning_hf.ipynb, notebooks/community/model_garden/model_garden_pytorch_llama2_peft_finetuning.ipynb, notebooks/community/model_garden/model_garden_pytorch_llama2_peft_hyperparameter_tuning.ipynb
This is a minor update to existing notebooks.
=> Fix malformed Colab URLs in model garden notebooks

notebooks/official/ray_on_vertex_ai/get_started_with_pytorch_rov.ipynb
Made edits to Ivan's notebook. No impact on code
=> Ray on vertex ai

notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
Reverts GoogleCloudPlatform/vertex-ai-samples#2847
=> Revert "Add Claude 3 Opus model"

notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
<br>
add Claude 3 Opus model
<br><br><br>
<br>
<br> …
=> add Claude 3 Opus model

notebooks/community/model_garden/model_garden_codegemma_deployment_on_vertex.ipynb
=> Fix CodeGemma model ID

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb, notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_xl_lora.ipynb
=> No-code/low-code notebook: Fix links 

notebooks/community/model_garden/model_garden_pytorch_mixtral_peft_tuning.ipynb
Fix Mixtral model id naming
<br>
<br><br><br>
<br>
<br>
=> Fix Mixtral model id naming

notebooks/community/model_garden/model_garden_pytorch_llama3_finetuning.ipynb
Fix GCS path in Llama 3 finetuning notebook.
<br>
=> Fix GCS path in Llama 3 finetuning notebook.

notebooks/official/feature_store/online_feature_serving_and_vector_retrieval_bigquery_data_with_feature_store.ipynb
Update feature store vector search notebook use latest features.
- Use multi region BigQuery dataset as test data.
- Use latest vertex SDK.
- Fix typo.
<br>
<br><br><br>
=> refactor: update feature store vector search notebook use latest features.

notebooks/community/model_garden/model_garden_gemma_fine_tuning_batch_deployment_on_rov.ipynb
<br>
This notebook demonstrates how to use Ray on Vertex AI for fine-tuning and serving Gemma on Vertex AI.
<br><br><br>
=> feat: tuning and serving Gemma on Ray on Vertex AI in Model Garden

notebooks/official/feature_store/online_feature_serving_and_fetching_bigquery_data_with_feature_store_bigtable.ipynb
<br>
This PR updates documentation to reflect the expanded regional availability of Vertex AI Feature Store, as outlined in the official Google Cloud documentation: https://cloud.google.com/vertex-ai/docs/general/locations. Added the newly supported regions to the documentation. Tested region us-east4 in Colab without encountering any issues.
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory …
=> Update Feature Store Region Availability Information

notebooks/community/model_garden/model_garden_huggingface_local_inference.ipynb
Initialize history and sync repos.
=> Sync GitHub repo

notebooks/community/model_garden/model_garden_gemma_finetuning_on_vertex.ipynb
Fix typo in Gemma finetuning notebook.
=> Fix typo in Gemma finetuning notebook.

notebooks/official/model_evaluation/model_based_llm_evaluation/autosxs_check_alignment_against_human_preference_data.ipynb, notebooks/official/model_evaluation/model_based_llm_evaluation/autosxs_llm_evaluation_for_summarization_task.ipynb
<br>
How that AutoSxS is GA, we no longer need to pin the GCPC version. GA products do not make breaking changes.
<br><br><br>
=> Import AutoSxS pipeline from GCPC v1 directory

notebooks/community/model_garden/model_garden_gemma_finetuning_on_vertex.ipynb
Fix Gemma finetuning notebook typo again.
=> Fix Gemma finetuning notebook typo again.

notebooks/official/feature_store/online_feature_serving_and_vector_retrieval_bigquery_data_with_feature_store.ipynb
=> fix: use renamed create_feature_view() function in embedding notebook

notebooks/official/generative_ai/tuned_text-embeddings.ipynb
=> feat: Getting Tuned Text-Embeddings tutorial.

notebooks/official/model_monitoring_v2/model_monitoring_for_custom_model_batch_prediction_job.ipynb, notebooks/official/model_monitoring_v2/model_monitoring_for_custom_model_online_prediction.ipynb, notebooks/official/model_monitoring_v2/model_monitoring_for_model_outside_vertex.ipynb
Add three notebooks to model_monitoring_v2:
- model_monitoring_for_custom_model_batch_prediction_job.ipynb
- model_monitoring_for_model_outside_vertex.ipynb
- model_monitoring_for_custom_model_online_prediction.ipynb
<br>
feat: Add model_monitoring_v2 notebooks
<br><br><br>
<br>
<br> …
=> feat: Add model_monitoring_v2 notebooks

notebooks/official/feature_store/online_feature_serving_and_vector_retrieval_bigquery_data_with_feature_store.ipynb
=> fix: update embedding column type to float

notebooks/community/model_garden/model_garden_gemma_fine_tuning_batch_deployment_on_rov.ipynb
Modify the Colab Enterprise link in the notebook so that it imports correctly in the environment.
=> fix: update colab enterprise link

community-content/CODEOWNERS, community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
=> Add common util functions for notebooks.

notebooks/official/model_monitoring_v2/model_monitoring_for_custom_model_batch_prediction_job.ipynb, notebooks/official/model_monitoring_v2/model_monitoring_for_custom_model_online_prediction.ipynb, notebooks/official/model_monitoring_v2/model_monitoring_for_model_outside_vertex.ipynb
<br>
chore: Refactor the instructions in model_monitoring_v2 notebooks
<br><br><br>
<br>
<br> …
=> chore: Refactor the instructions in model_monitoring_v2 notebooks

notebooks/official/generative_ai/tuned_text-embeddings.ipynb
**REQUIRED:** Fix a comment on Vertex AI Workbench
<br>Fix: b/343815651<br><br><br>
=> fix: Comment on Vertex AI workbench.

notebooks/official/feature_store/vertex_ai_feature_store_feature_view_service_agents.ipynb
<br>
3. Removed the before you begin section as per the new template
4. Grouped Vertex AI SDK initiation with Google cloud project setup steps
5. Included colab enterprise link 
6. Used generalized code for "colab only" cells
<br><br><br>
<br>
=> refactor(egen): Refactored the code as per template guidelines

notebooks/official/feature_store/online_feature_serving_and_fetching_bigquery_data_with_feature_store_optimized.ipynb
<br>
2. Adds link for colab enterprise.
3. Removes the usage of future tense(will) according to the guidelines.
<br><br><br>
<br>
=> refactor, chore(egen): Removes boilerplate, heading fixes, and other corrections from template

notebooks/notebook_template.ipynb, notebooks/official/experiments/build_model_experimentation_lineage_with_prebuild_code.ipynb
- "Getting Stared" -> "Get started"
-  Added "Python" to "Vertex AI SDK" 
All to be in compliance with the style guide and product guidelines, respectively
=> Template vertex ai

notebooks/official/generative_ai/text_embedding_new_api.ipynb
<br>
3. Removed the before you begin section as per the new template
4. Grouped Vertex AI SDK initiation with Google cloud project setup steps
5. Included colab enterprise link 
6. Used generalized code for "colab only" cells
<br><br><br>
<br>
=> refactor(egen): Refactored text embedding new api code according to the template guidelines

notebooks/official/training/pytorch_gcs_data_training.ipynb
<br>
The `pytorch_gcs_data_training.ipynb` notebook doesn't utilize accelerators while training though there are constants defined for that purpose. This PR enables the code to use the defined accelerators. 
Additionally, this PR includes the following updates:
1. Replaces K80 with T4.
2. Adds Colab Enterprise link.
3. Removes IS_TESTING condition from the cleaning up section.
4. Removes unused imports.
5. Replaces GCS with Cloud Storage.
6. Other minor fixes based on the template writing guidelines.
<br><br><br> …
=> refactor, chore, fix(egen): GPU usage fixes, template & markdown fixes

notebooks/official/generative_ai/text_embedding_api_semantic_search_with_scann.ipynb
<br>
3. Removed version for google-cloud-aiplatform import 
4. Included colab enterprise link and generalized code for "colab only" cells
<br><br><br>
<br>
=> refactor(egen): Refactored Text embedding api semantic search with scann code according to template guidelines

notebooks/notebook_template.ipynb
**REQUIRED:** 
We received multiple feedback from google team and based on that we updated notebook template.
<br>
Updated notebook template. As this is just notebook template hence we didn't executed code.
<br><br><br>
<br>
<br> …
=> Updated notebook template

notebooks/official/feature_store/online_feature_serving_and_vector_retrieval_bigquery_data_with_feature_store.ipynb
Refactors the notebook according to the notebook template (removes boilerplate elements, renames REGION with LOCATION and re-structures the sections).
Adds link for colab enterprise.
Removes the usage of future tense(will) according to the guidelines.
Adds code(commented) for bq dataset deletion in the cleanup section.
=> refactor(egen): Removes boilerplate, heading fixes, and other corrections from template

notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
Refactors the notebook according to the notebook template (renames REGION with LOCATION and re-structures the sections).
Adds link for colab enterprise.
Adds text explanations for required cells
Updates the link for claude documentation
=> refactor, chore(egen): Claude documentation link update, Text explanations for required cells and other corrections from template

notebooks/official/matching_engine/sdk_matching_engine_for_indexing.ipynb
<br>
1. Restructures the sections according to the template. Updates the Colab related markdown and cells accordingly.
2. Reduces the usage of future tense.
3. Adds the collapsed license comment.
4. removes IS_TESTING parameter in cleaning up section.
5. Converts Dataset object to a list while passing the object to the Vector search endpoint and fixes the prediction issue.
<br><br><br>
<br>
=> chore, fix(egen): restructuring from template, markdown corrections & dataset object fix

notebooks/official/custom/sdk-custom-image-classification-online.ipynb
**REQUIRED:** 
Fixing below issues in notebook:
- Updated template of notebook based on new template of notebook
- Tested code and its working fine
- Unable to execute notebook end to end on google colab as its crashing (not related to code but due to colab related issue).
<br>
Changed notebook to updated template of notebook. Additionally, thoroughly checked notebook.
<br><br><br>
<br>
2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex- …
=> refactor, chore(egen): Removes boilerplate, heading fixes, and other corrections from template 

notebooks/official/model_evaluation/model_based_llm_evaluation/autosxs_check_alignment_against_human_preference_data.ipynb
<br>
3. Included --quite argument in the pip install dependencies.
4. Removed IS_TESTING env variable
5. Included colab enterprise link and generalized code for "colab only" cells
<br><br><br>
<br>
=> refactor(egen): Refactored the Autosxs check alignment against human preference data code as per template guidelines

notebooks/official/training/distributed_hyperparameter_tuning.ipynb
Refactored all the cells according to the template notebook, replaces tf2-gpu.2-5 with tf2-gpu.2-6
<br>
4. tf2-gpu.2-5 doesnt exist in the gcr repo, hence replaced with tf2-gpu.2-6
5. Removed IS_TESTING env variable
6. Included deletion of gcr image in Cleaning up code
<br><br><br>
<br>
=> fix, refactor(egen): Replaced tf2-gpu.2-5 with tf2-gpu.2-6, Refactored the code as per template guidelines

notebooks/official/model_evaluation/model_based_llm_evaluation/autosxs_llm_evaluation_for_summarization_task.ipynb
<br>
3. Included --quite argument in the pip install dependencies.
4. Removed IS_TESTING env variable
5. Included colab enterprise link and generalized code for "colab only" cells
<br><br><br>
<br>
=> refactor(egen): Refactored the Autosxs llm evaluation for summarization task code as per template guidelines

notebooks/official/prediction/custom_batch_prediction_feature_filter.ipynb
<br>
3. Removed import os - unused
4. Included colab enterprise link 
5. Used generalized code for "colab only" cells
<br><br><br>
<br>
=> refactor(egen): Refactored custom batch prediction feature filter code according to template guidelines

notebooks/official/custom/get_started_vertex_training_xgboost.ipynb
The following changes are made in the notebook:
- Fixes argument passed in pip install
- updates packages
- removes boilerplate code
- adds link to colab enterprise
- updates usage of 'will' appropriately
<br><br><br>
<br>
<br> …
=> refactor, fix, chore(Egen): changes and refactors the get_started_vertex_training_xgboost.ipynb notebook

notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb
<br>
3. Removed import os - unused
4. Included --quite argument in the pip install dependencies.
5. Removed IS_TESTING env variable
6. Included colab enterprise link and generalized code for "colab only" cells
<br><br><br>
<br>
=> refactor(egen): Refactored the Custom tabular bq managed dataset code as per template guidelines 

notebooks/official/custom/SDK_Custom_Container_Prediction.ipynb
<br>
The notebook's optional docker run (local) step fails when executed in the Vertex AI Workbench. Removing sudo from the command has fixed the issue. Along with the command update, this PR includes:
1. Adds Colab Enterprise link 
2. Rewords some sentences to match the guidelines
3. Rewords some headings as per the content and fixes their styles as per the hierarchy
4. Removes IS_TESTING from the cleaning up section
5. Adds clean up step for locally created files
<br><br><br>
<br>
=> chore, fix, feat(egen): follows template + fix docker run + adds clean up

notebooks/official/matching_engine/sdk_matching_engine_create_multimodal_embeddings.ipynb
1. Restructures the sections according to the template. Updates the Colab related markdown and cells accordingly.
2. Reduces the usage of future tense.
3. Updates license comment.
4. removes IS_TESTING parameter in cleaning up section
5. removes boilerplate
<br><br><br>
<br>
<br>
3. If you are …
=> chore, refactor(Egen): restructure from template, remove boilerplate, and fix notebook

notebooks/official/training/hyperparameter_tuning_xgboost.ipynb
<br>
The notebook `hyperparameter_tuning_xgboost.ipynb` consists of some elaborate explanations and steps which can be simplified.
1. Restructures the notebook according to the template.
2. Simplifies elaborative/unnecessary steps and content.
3. Replaces K80 with T4.
4. Reduces the disk space from 200 to 100 (to set a minimum).
5. Removes future tenses and simplifies wording.
6. Adds colab enterprise link.
7. Simplifies the section headings
8. Removes redundant code/explanations.
9. Adds clean up step for locally generated files.
10. Removes -q in the installation step (--quiet is already available).
11. Replaces REGION with LOCATION.
<br><br><br>
1. If you are opening a PR for …
=> refactor, chore, feat(egen): contracts content, steps & template based fixes

notebooks/official/training/multi_node_ddp_nccl_vertex_training_with_custom_container.ipynb
<br>
The notebook `multi_node_ddp_nccl_vertex_training_with_custom_container.ipynb` uses K80 accelerator which is deprecated now., and follows the old template structure.
1. Replace K80 with T4 GPUs.
2. Adds additional explanation at a few places.
3. Removes future tense.
4. Re-structures the notebook according to the new template.
5. Moves the setup related steps to the beginning.
6. Removes IS_TESTING from cleaning up section.
7. Adds steps to remove locally generated files in the cleaning up section.
8. Capitalizes the constants to run the training job.
<br><br><br> …
=> chore, refactor, fix, feat(egen): template structure+K80GPU+contract words+clean up

README.md
=> Update README.md 4

community-content/vertex_cpr_samples/README.md, community-content/vertex_cpr_samples/torch/predictor_transformers.py
This sample uses the aiplatform SDK and torch library to implement transformers predictor.
=> Upload torch transformers predictor sample

notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
<br>
Add new model Claude 3.5 Sonnet and update regions for other models
<br><br><br>
<br>
<br> …
=> Add new model Claude 3.5 Sonnet and update regions for other models

notebooks/official/generative_ai/tuned_text-embeddings.ipynb
feat: Use pipeline_job_name from a tuning result.
<br>
=> feat: Use pipeline_job_name from a tuning result.

notebooks/community/model_garden/model_garden_keras_stable_diffusion.ipynb
<br>
Switch existing notebook to use a different port (8501 was reserved somehow and caused deployment errors).
<br><br><br>
<br>
<br>
=> Update the server port in model_garden_keras_stable_diffusion.ipynb

notebooks/official/prediction/get_started_with_nvidia_triton_serving.ipynb
2. Adds link for colab enterprise.
3. Removes the usage of future tense(will) according to the guidelines.
4. Adds note before executing the image deployment cell in colab.
5. Updates broken links in markdown cells.
=> refactor, chore(egen): Fix broken links in Markdown cells, corrections from template.

notebooks/official/training/get_started_with_vertex_distributed_training.ipynb
<br>
The notebook `get_started_with_vertex_distributed_training.ipynb` uses K80 GPUs that are now deprecated., and uses gcr.io repo while pushing the training image. The TF 2.5 image being used to train using the custom container method is now deprecated.
1. Replace K80 GPUs with T4 GPUs.
2. Upgrades TF 2.5 to TF 2.8.
3. Adds steps to enable Artifact Registry service, create a repo and configure local docker for pushing.
4. Separates the Colab specific docker steps.
5. Restructures some sections according to the flow and rewords some titles.
6. Reduces the accelerator count to avoid the resource unavailability/allocation rejections.
7. Removes future tense and adds contractions wherever possible.
8. Add clean up steps for Artifact Registry …
=> fix, chore, refactor, feat(egen): Replaces K80 to T4, gcr with Artifact Registry etc.

notebooks/official/model_registry/get_started_with_model_registry.ipynb
1. K80 replaced with T4 GPU.
2. Refactors the notebook according to the notebook template (removes boilerplate elements, renames REGION with LOCATION and re-structures the sections).
3. Removes the usage of future tense(will) according to the guidelines.
4. Update notebook to use TensorFlow 2.15.1 due to specific model dependencies.
5. Adds condition to set hardware accelerators while testing.
=> refactor, chore(egen): Replaces K80 with T4 GPUs, corrections from template.

community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
<br>
Support A100-80GB for checking quota
<br><br><br>
=> Support A100-80GB for checking quota

README.md
=> Update README.md 5

notebooks/official/experiments/get_started_with_vertex_experiments.ipynb
<br>
3. Included colab enterprise link and generalized code for "colab only" cells
4. Removed os.getenv("IS_TESTING") while cleanup bucket
5. Updated the URLs with latest paths
<br><br><br>
<br>
=> refactor, chore(egen): Refactored code according to template guidelines

notebooks/official/training/multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb
<br>
2. Renamed REGION as LOCATION.
3. Corrects some sentences and structure according to the template.
4. Added code for removing local generated files while executing code.
5. Added code for removing artifact repository.
6. Removed reference to Tensorboard billing since it is not true anymore.
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow …
=> refactore, chore (egen): Refactored code according to the notebook template

notebooks/official/vector_search/sdk_vector_search_create_stack_overflow_embeddings_vertex.ipynb
Following changes are made to the notebook:
- removers boiler plate
- fixes error in loading data to np
<br>
<br>
=> refactor,fix,chore: fixes error and refactors sdk_vector_search_create_stack_overflow_embeddings_vertex notebook according to template

notebooks/community/model_garden/model_garden_pytorch_llama3_finetuning.ipynb
<br>
Update training docker tag<br><br><br>
<br>
=> Update training docker tag

README.md
Add more examples:
- pipelines
- explainable ai
- feature store
=> Update README.md 6

notebooks/official/sdk/SDK_AutoML_Video_Classification.ipynb
2. Adds link for colab enterprise.
3. Removes the usage of future tense(will) according to the guidelines.
=> refactor(egen): Removes boilerplate, heading fixes, corrections from template.

notebooks/official/explainable_ai/sdk_custom_tabular_regression_batch_explain.ipynb
1. Fixes the TF version to 2.15.1.
2. Adds Colab Enterprise link and other structural changes from the new template.
3. Changes REGION variable name to LOCATION.
4. Replaces K80 GPU with T4 GPU (as K80 is deprecated).
5. Removes IS_TESTING from the cleaning up section.
6. Adds comments for cells needed.
7. Modifies code while saving data to input csv file for prediction.
8. Removes the usage of future tense.
9. Replaces aip with aiplatform.
10. Contracts words like is not, do not, You are, etc.
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this …
=> refactor, chore, fix(egen): replace K80 with T4, template fixes

notebooks/official/explainable_ai/sdk_automl_tabular_classification_online_explain.ipynb
3. Changes dag variable name to job
4. Removes os.getenv("IS_TESTING") and import os from the cleanup section.
5. Adds job.delete() to delete training job in the cleanup section. 
6. Removes code highlight when used at places other than code or variables. 
7. Adds comments for cells needed.
8. Removes the usage of future tense.
9. Replaces aip with aiplatform.
10. Contracts words like is not, do not, You are, etc.
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/ma …
=> refactor, chore(egen): Refactored code according to template guidelines, added code to delete job in cleanup section

notebooks/official/model_monitoring/get_started_with_model_monitoring_custom.ipynb
<br>
This PR includes the following updates to the `get_started_with_model_monitoring_custom.ipynb` notebook:
- Replace K80 with T4
- Move steps for deleting the endpoints to cleaning up section
- Adds Colab steps from the new template
- Fix/reword sentences to explain some steps in a better and simpler way
- Spelling/typo corrections
- Remove unnecessary code highlights (``)
- Add Colab Enterprise link and other steps from the new template
- Remove future tense
- Contract words like is not, do not etc.
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory …
=> chore, refactor(egen): follows new template, removes IS_TESTING, spell corrections

notebooks/official/pipelines/control_flow_kfp.ipynb
2. Changes file extension from .json to .yaml in the cleanup section for deleting locally generated resources.
3. Changes REGION variable name to LOCATION.
5. Removes import os and IS_TESTING from the cleaning up section.
6. Adds comments for cells needed.
7. Removes the usage of future tense.
8. Replaces aip with aiplatform.
9. Contracts words like is not, do not, You are, etc.
=> chore, refactor(egen) : changes file extension from .json to .yaml, refactored code as per template guidelines

notebooks/official/pipelines/google_cloud_pipeline_components_automl_images.ipynb
1. Fixes VertexAI image dataset creation by updating the gcs_source link.
2. Includes pipeline job deletion step in cleanup section.
3. Refactors the notebook according to the notebook template (removes boilerplate elements, renames REGION with LOCATION and re-structures the sections).
4. Removes the usage of future tense(will) according to the guidelines.
=> fix, refactor(egen):  fixes data import issue, includes pipeline job deletion, corrections from template.

notebooks/official/CODEOWNERS, notebooks/official/feature_store/vertex_ai_feature_store_iam_policy.ipynb
<br>
Add vertex_ai_feature_store_iam_policy notebook. This provides a tutorial on how to configure IAM Policy for Feature Store online serving resources.
<br><br><br>
<br>
2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) …
=> Add vertex_ai_feature_store_iam_policy notebook.

notebooks/official/ray_on_vertex_ai/get_started_with_pytorch_rov.ipynb
<br>
This PR is an update of the torch sample on Ray on Vertex AI. 
<br><br><br>
=> fix: update the torch sample on Ray on Vertex AI

notebooks/official/generative_ai/tuned_text-embeddings.ipynb
<br>
Add `learning_rate_multiplier` and `output_dimensionality` parameters to the text embedding tuning notebook. These parameters are released to GA this week.
Also make notebook setup more similar to the template.
<br><br><br>
<br> …
=> Add `learning_rate_multiplier` and `output_dimensionality` parameters to the text embedding tuning notebook.

notebooks/official/explainable_ai/sdk_custom_tabular_regression_online_explain_get_metadata.ipynb
1. Changes REGION to LOCATION
2. Adds code to delete locally generated files in clean up section
3. Adds job.delete() in clean up section
4. Hardcodes tensorflow version to 2.15.1
5. Removes os.getenv('IS_TESTING') in cleanup section
6. Removes  os.getenv('IS_TESTING') condition from pip install section
7. Replaces NVIDIA_TESLA_K80 with NVIDIA_TESLA_T4
8. Moves imports to one cell
9. Adds collab enterprise logo
10. Makes structural changes according to the new notebook template
11. Removes future tense
12. Contracts words like is not to is'nt
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tre …
=> Fix, chore, refactor(Egen) : hardcodes tensorflow dependency to 2.15.1, K80 to T4, refactors code as per notebook template guidelines

notebooks/official/tensorboard/tensorboard_custom_training_with_custom_container.ipynb
2. Removes the usage of future tense(will) according to the guidelines.
3. Minor spelling mistake corrections.
=> refactor(egen): Corrections from template.

notebooks/official/experiments/get_started_with_vertex_experiments_autologging.ipynb
The PR includes the following changes:
- Adds colab enterprise
- Renames REGION to LOCATION
- Fixes version for compatibility
- Fixes types of the input and model arguments as they were causing error
- Removes boilerplate code and reformats according to template
<br>
<br> …
=> chore, fix, refactor(egen): fixes get_started_with_vertex_experiments_autologging notebook

notebooks/official/experiments/delete_outdated_tensorboard_experiments.ipynb
following changes are part of the PR
- restructure according to template
<br>
<br>
=> Egen fix/delete outdated tensorboard experiments

notebooks/official/migration/sdk-automl-text-sentiment-analysis-batch-prediction.ipynb
This PR, adds a note to the deprecated notebooks and performs linter test.
=> chore(egen): Adds note to the deprecated notebook 

notebooks/official/automl/automl-text-classification.ipynb
This PR, Adds a note to the deprecated notebook and performs linter test.
=> chore(egen): Adds note to the deprecated notebook

notebooks/official/automl/sdk_automl_text_sentiment_analysis_online.ipynb
This PR, adds a note to the deprecated notebooks and performs linter test.
=> chore(egen) : Adds the note to the deprecation of the notebook and performs linter test

notebooks/official/experiments/comparing_pipeline_runs.ipynb, notebooks/official/model_monitoring/get_started_with_model_monitoring_automl.ipynb
2. Adds link for Colab enterprise.
3. Fixes import error.
=> refactor, chore, fix(egen): Documentation link update, package version updates, fixes import errors 

README.md
Update README.md
- Add more products and services
=> Update README.md (7)

notebooks/official/experiments/build_model_experimentation_lineage_with_prebuild_code.ipynb
- edits according to template
<br>
<br>
=> refactor, chore(egen): edits build_model_experimentation_lineage_with_prebuild_code notebook

notebooks/official/pipelines/google_cloud_pipeline_components_automl_text.ipynb
1. Adds a note to the deprecated notebook 
2. performs linter test.
=> chore(egen) : added note to deprecated notebook and performed linter test

notebooks/official/migration/sdk-automl-text-entity-extraction-batch-prediction.ipynb
1. Adds the details of the deprecation of the notebook
=> chore(egen):Added the note for deprecation of notebook and performed linter test

notebooks/official/pipelines/google_cloud_pipeline_components_bqml_text.ipynb
3. Changes the tensorflow version to 2.13.1 from 2.8.0.
4. Changes the tensorflow-hub version to 0.16.0 from 0.12.0.
5. Changes the versions of apache_beam[gcp] to 2.47.0 from 2.36.0, bs4 to 0.0.2 from 0.0.1 and tensorflow to 2.13.1 from 2.8.0 in requiremets.txt and setup.py files.
6. Removes IS_TESTING from the cleaning up section.
7. Adds comments for cells needed.
8. Contracts words You are etc.
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/off …
=> chore,refactor(egen): minor updates to google cloud pipeline components bqml text motebook

notebooks/official/feature_store_legacy/feature_store_streaming_ingestion_sdk.ipynb
3. Replaces np.NaN with np.nan.
4. Contracts words like You are, do not, it is etc.
5. Changes future tense sentences to present tense.
6. Changes to second person sentences.
=> chore,refactor(egen): minor changes to feature store streaming ingestion sdk notebook

notebooks/official/model_evaluation/automl_video_classification_model_evaluation.ipynb
1. changed REGION to LOCATION
2. removed os.getenv in cleanup section
3. removed os module
4. performed linter test
5. followed template guidelines
- [] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
=> refactor(egen): Automl video classification model evalution

notebooks/official/pipelines/google_cloud_pipeline_components_model_upload_predict_evaluate.ipynb
- Removes boiler plate
- makes changes as per the template
- adds package versions for dealing with version conflicts 
<br>
<br>
=> refactor, chore, fix(egen): edits google_cloud_pipeline_components_model_upload_predict_evaluate.ipynb notebook

notebooks/official/migration/sdk-automl-tabular-binary-classification-online-prediction.ipynb
This PR includes 
1.changed variable REGION to LOCATION
2.added  pandas in installation section
3.removed UUID code and os module
4.performed linter test
5.followed template guidelines
6.added code to remove locally generated files
=> refactor,chore(egen) : refactored code according to template guidelines

notebooks/official/feature_store_legacy/sdk-feature-store.ipynb
3. Adds cleanup code for cloud storage bucket.
4. Adds comments for cells needed.
=> chore,refactor(egen): minor changes to sdk feature store notebook

notebooks/community/model_garden/model_garden_camp_zipnerf_gradio.ipynb
<br>
[Vertex AI MG Team] Remove corp link in NeRF gradio application.
<br><br><br>
<br>
<br> …
=> [Vertex AI MG Team] Remove corp link in NeRF gradio application.

community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
<br>
Add a function to resize an image to common utils
<br><br><br>
=> feat: add a fn to resize an image

notebooks/official/prediction/sdk_private_endpoint.ipynb
This PR adds the following deprecation note to the notebook.
"This notebook has been deprecated."
=> chore(egen) : Adds deprecation note to the notebook

notebooks/official/tensorboard/tensorboard_custom_training_with_prebuilt_container.ipynb
1. Fixes source distribution name.
2. Cleans up the intermediates files created.
3. Refactors the notebook according to the notebook template (removes boilerplate elements, renames REGION with LOCATION and re-structures the sections).
4. Adds link for Colab enterprise.
5. Removes the usage of future tense(will) according to the guidelines.
=> refactor, chore(egen): Removes boilerplate, heading fixes, corrections from template.

notebooks/official/pipelines/multicontender_vs_champion_deployment_method.ipynb
<br>
This PR makes the following updates to the `multicontender_vs_champion_deloyment_method.ipynb` notebook:
- Change REGION to LOCATION
- Remove IS_TESTING condition at cleaning step
- Add Colab enterprise link
- Add Colab specific steps and other updates according to the new notebook template
- Remove future tense
- Contract words (like do not --> don't etc.)
- Fix the position of a sub-section (for "Save the model artifacts")
- Replace K80 with T4 in the text about GPUs
- Fix the typo "modesl"
- Moves the clean up step for yaml file to the last section
- Removes unnecessary code highlights (using "``")
- Handles the cases for Vertex AI resources
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under …
=> chore(egen): follows new template, fixes typos, K80-->T4, REGION-->LOCATION etc.

notebooks/official/reduction_server/pytorch_distributed_training_reduction_server.ipynb
- Adds colab enterprise
- changes region to location
- fixes issue with load_dataset
- formats according to the template
<br>
<br>
=> chore, refactor, fix(egen):  formats and fixes pytorch_distributed_training_reduction_server.ipynb

notebooks/official/pipelines/rapid_prototyping_bqml_automl.ipynb
<br>
This PR includes the following updates to the `notebooks/official/pipelines/rapid_prototyping_bqml_automl.ipynb` notebook:
- budget_milli_node_hours are specified to reduce the training time.
- removes IS_TESTING condition in the cleanup step.
- replaces REGION with LOCATION.
- replaces dsl.Condition (is deprecated) with dsl.If.
- addd a clean up step for the locally generated pipeline package file.
- adds link for Colab enterprise.
- removes future tense (will).
- contracts words (do not, you are etc.).
- image links are no longer accessible and hence are removed
- fixes typos (aboyt, election).
- removes the usage of "we".
<br><br><br> …
=> chore, refactor, feat(egen): Follows new template, markdown fixes, refactors

notebooks/community/exploratory_data_analysis/eda_with_r_and_bigquery.ipynb
<br>
Updating the exploratory data analysis with R notebook to be used in the Cloud Architecture Center with a new dataset used for analysis and various other changes from reviewers.
<br><br><br>
<br>
2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main …
=> Updating dataset and other changes from review

notebooks/official/migration/sdk-custom-image-classification-prebuilt-container.ipynb
1. Hardcodes TF version to 2.15.1
2. Adds code to delete locally generated files
3. Deletes function to generate UUID and replaces UUID with unique
4. Changes REGION to LOCATION
5. Changes aip to aiplatform
6. Includes Colab restart kernal and authentication as per template guidelines
7. Adds collab enterprise logo
8. Makes structural changes according to the new notebook template
9. Removes the use of future tense
10. Contracts words like it is to it's and do not to don't etc 
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory …
=>  refacto, chore (egen): refactors code as per template guidelines, hardcodes TF version to 2.15.1,deletes locally generated files

notebooks/official/tensorboard/tensorboard_hyperparameter_tuning_with_hparams.ipynb
<br>
This PR includes the following updates to the `tensorboard/tensorboard_hyperparameter_tuning_with_hparams.ipynb` notebook:
- replace REGION with LOCATION
- add code to remove the resources (tensorboard, experiment, logs file)
- remove unnecessary code (for cleaning up the storage bucket)
- simplify the display-name variables
- follow the new template structure
- reorganize the sections according to the flow of the tutorial
- remove future tense
- simplify some sentences in the explanation for tensorboard instances
- move "what is Tensorboard" (informative section) to the beginning of the tutorial
<br><br><br> …
=> chore, refactor, feat(egen): follows new template, simplifies code, adds cleanup step

notebooks/official/datasets/get_started_bq_datasets.ipynb
- removes boiler plate and changes according to template
- changes version for dealing with compatibility error
<br>
<br>
=> refactor, fix, chore(egen): edits get_started_bq_datasets

notebooks/official/migration/sdk-custom-image-classification-custom-container.ipynb
3. Added opencv-python-headless and tensorflow==2.15.1 packages in installation step.
4. Added import os statement in set machine type configuaration cell.
5. Added cloud storage bucket and local files cleanup code.
6. Contracts words like You are, do not, it is etc.
=> chore,refactor(egen):  Added opencv-python-headless and tensorflow==2.15.1 packages and cleanup code for local files and cloud storage bucket

notebooks/official/workbench/sentiment_analysis/Sentiment_Analysis.ipynb
1.replaced variable REGION to LOCATION
2.imported required modules
3.added missed libraries in installation section
4.added colab enterprise link
5.added Colab authentication and kernal restart steps.
6.refactored notebook according to template guidelines
=> refactor(egen) : refactored notebook according to template guidelines nd added missed modules and libraries

notebooks/official/model_evaluation/model_based_llm_evaluation/autosxs_llm_evaluation_for_summarization_task.ipynb
=> Update notebook to use Gemini model instead of text-bison because text-bison will be deprecated.

notebooks/official/tabular_workflows/wide_and_deep_on_vertex_pipelines.ipynb
- makes changes according to the template
<br>
<br>
=> chore, refactor (egen): refactors wide_and_deep_on_vertex_pipelines.ipynb notebook

notebooks/official/automl/sdk_automl_video_action_recognition_batch.ipynb
- Rectifies verbiage
<br>
<br>
=> refactor, chore (egen): refactors sdk_automl_video_action_recognition_batch notebook

notebooks/official/workbench/fraud_detection/fraud-detection-model.ipynb
2. Adds link for colab enterprise.
3. Contracts words such as "is not" to "isn't".
=> Refactor(egen): Corrections from template

notebooks/official/workbench/gaming_churn_prediction/churn_prediction_for_game_developers.ipynb
2. Removes IS_TESTING from the cleaning up section.
3. Removes generate_uuid() function
4. Removes BUCKET_NAME variable and includes bucket name directly in BUCKET_URI variable
5. Changes REGION to LOCATION
6. Removes Table of contents
7. Contraction of words
8. Future to present tense
=>  refactor, chore(egen): removes import os, refactors as per new template guidelines

notebooks/official/migration/sdk-automl-video-classification-batch-prediction.ipynb
1. Includes tensorflow installation step in installation section.
2. Refactors the notebook according to the notebook template (removes boilerplate elements, renames REGION with LOCATION and re-structures the sections).
3. Adds link for Colab enterprise.
4. Removes the usage of future tense(will) according to the guidelines.
5. Changes sentence style to second person.
=> refactor, chore(egen): Tensorflow version fix, grammar corrections, other corrections from template

notebooks/official/workbench/demand_forecasting/forecasting-retail-demand.ipynb
1. Adds Colab authentication and kernal restart steps.
2. Adds colab enterprise logo with link.
3. Removes IS_TESTING condition.
4. Replace REGION with LOCATION.
5. Removed UUID code
6. added code to delete gcs bucket in cleanup section
=> refcator,chore(egen) : refactored code according to template guidelines

notebooks/official/ray_on_vertex_ai/spark_on_ray_on_vertex_ai.ipynb
<br>
A small update to an instruction in the notebook for retry block.
<br><br><br>
<br>
<br> …
=> Updated instruction for retry block in Spark on Ray on Vertex AI notebook

notebooks/official/pipelines/metrics_viz_run_compare_kfp.ipynb
2. Removes the usage of future tense(will) according to the guidelines.
3. Adds job deletion step in clean up section.
4. Adds link for Colab enterprise.
5. Adds new package install step in component section
6. Updates the existing installation package version
=> refactor, chore(egen): refactored the notebook according to the template, updated and added new package

notebooks/official/model_monitoring/get_started_with_model_monitoring_automl.ipynb
2. Removes the usage of future tense(will) according to the guidelines.
3. Adds model deletion steps in clean up section.
=> refactor(egen): template fixes, adds clean up steps

notebooks/official/automl/sdk_automl_video_classification_batch.ipynb
- Adds colab enterprise
- changes according to the template
<br>
<br>
=> chore, refactor(egen): updates and refactors sdk_automl_video_classification_batch notebook

notebooks/official/model_monitoring/get_started_with_model_monitoring_automl_image_online.ipynb
3. Modifies the import file.
4. Removes versions in the installation step.
5. Modifies code in online prediction using the SDK interface
6. Adds the clean up code for endpoint and training job 
7. Adds comments in cleanup code.
8. Contracts words like it is, you are, do not etc.
=> fix,chore,refactor(egen): minor fix and changes to the model monitoring automl image online notebook.

notebooks/official/migration/sdk-automl-object-tracking-batch-prediction.ipynb
- REGION changed to LOCATION
- Removes future tense
- formats according to the template
- removes Boilerplate code
<br>
<br>
=> refactor, chore: (egen):sdk-automl-object-tracking-batch-prediction

notebooks/official/model_evaluation/automl_tabular_regression_model_evaluation.ipynb
<br>
This PR includes the following updates to the `automl_tabular_regression_model_evaluation.ipynb` notebook:
1. Replace REGION with LOCATION.
2. Remove IS_TESTING condtion in the Cleaning up section.
3. Adds collab enterprise logo.
4. Made structural changes according to new notebook template.
5. Contraction of words (do not --> don't).
6. Some minor heading/sentence corrections.
<br><br><br>
<br>
=> chore(egen): Follows new template, removes IS_TESTING, REGION --> LOCATION

notebooks/community/model_garden/synthetic_data_generation_using_llama3_1.ipynb
Fix endpoint in synthetic_data_generation_using_llama3_1.ipynb
=> Fix endpoint in synthetic_data_generation_using_llama3_1.ipynb

notebooks/official/CODEOWNERS, notebooks/official/generative_ai/mistralai_intro.ipynb
<br>
Added the official colab notebook to get started with Mistral AI's 3 models
<br><br><br>
<br>
<br> …
=> feat: Official notebook for Mistral AI Release 07/24

notebooks/official/generative_ai/mistralai_intro.ipynb
<br>
Colab enterprise link fix
<br><br><br>
<br>
<br> …
=> fix: typo in Mistral AI Colab ent link

notebooks/official/automl/automl_image_classification_online_prediction.ipynb
2. Changed REGION variable name to LOCATION.
3. Modified the import file.
4. Added version for the tensorflow package in installation step.
5. Added comments in cleanup section.
6. Removed os.getenv("IS_TESTING") from the cleanup section.
7. Adds comments in cleanup section.
8. Contracts words like is not, do not, You are, does not, will not  etc.
9. Changes future tense sentences to present tense.
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory …
=> fix,chore,refactor(egen): minor changes to the automl_image_classification_online_prediction notebook.

notebooks/official/automl/sdk_automl_tabular_regression_batch_bq.ipynb
1. Changes REGION to LOCATION
2. Includes colab restart kernal and authentication as per template guidelines
3. Changes aiplatfrom import statement
4. Adds collab enterprise logo
5. Makes structural changes according to the new notebook template
6. Removes the use of future tense
7. Contraction of words
8. Adds code highlight
=> refactor, chore(egen):  Changes aiplatfrom import statement, refactors as per notebook template guidelines, linter performed

notebooks/community/model_garden/model_garden_llama_guard_deployment.ipynb, notebooks/community/model_garden/synthetic_data_generation_using_llama3_1.ipynb
Update Llama Guard and synthetic data generation notebooks.
<br>
=> Update Llama Guard and synthetic data generation notebooks.

notebooks/community/model_garden/model_garden_openai_api_llama3_1.ipynb, notebooks/community/model_garden/model_garden_rag.ipynb
Update OpenAI API Llama 3.1 and RAG notebooks.
<br>
=> Update OpenAI API Llama 3.1 and RAG notebooks.

notebooks/official/CODEOWNERS
<br>
I added wrong id in the CODEOWNERS file previously. Corrected it.
<br><br><br>
<br>
<br> …
=> Update github id in CODEOWNERS file

notebooks/official/automl/sdk_automl_video_object_tracking_batch.ipynb
- removes IS_TESTING
- edits as per template and authoring guide
<br>
<br>
=> refactor, chore (egen): refactors sdk_automl_video_object_tracking_batch.ipynb notebook

notebooks/official/automl/get_started_automl_training.ipynb
2. Changed REGION variable name to LOCATION.
3. Modifies the import file of flowers dataset.
4. Adds comments in cleanup section.
5. Removes os.getenv("IS_TESTING") from the cleanup section.
6. Contracts words like is not, do not, you are, does not, will not  etc.
7. Changes to second person sentences.
8. Changes future tense sentences to present tense.
=> fix,chore,refactor(egen): minor changes to the automl training notebook.

notebooks/official/workbench/chicago_taxi_fare_prediction/chicago_taxi_fare_prediction.ipynb
2. Removes the usage of future tense(will) according to the guidelines.
3. Adds link for Colab enterprise.
4. Adds new package install step in import section
5. Updates the existing installation package version
=> refactor, chore(egen): template fixes, update and add new package

community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
<br>
Support checking H100 quota<br><br><br>
=> Support checking H100 quota

notebooks/official/automl/automl-tabular-classification.ipynb
1.Replace REGION with LOCATION.
2.Removes IS_TESTING condition.
3.Adds colab enterprise logo with link.
4.Makes Heading changes according to template guidelines.
5.Fix unnecessary "``" code highlight usage.
6.Adds Colab authentication and kernal restart steps.
7.removed unnecessary code
=> refactor,chore(egen): refactored code as per template guidelines

notebooks/official/experiments/get_started_with_custom_training_autologging_local_script.ipynb
The following changes are part of the PR:
- Adds colab enterprise
- lint errors rectified
- restructure according to template including changes like "REGION" to "LOCATION"
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-sampl …
=> chore,refactor(egen): reformats get_started_with_custom_training_autologging_local_script.ipynb notebook

notebooks/community/model_garden/model_garden_video_object_tracking_serve.ipynb
… prior to prediction.
<br>
<br><br><br>
<br>
<br> …
=> [MG Model Team] Add environment variable for downscaling video frames prior to prediction.

notebooks/official/pipelines/lightweight_functions_component_io_kfp.ipynb
1.corrected colab enterprise link
=> refactor,chore(egen): added colab enterprise for lightweight_functions_component_io_kfp notebook

notebooks/official/explainable_ai/sdk_custom_tabular_regression_online_explain_get_metadata.ipynb
This PR changes method-1 to method-2, changes the license year back to 2021.
=>  typo fix in markdown

notebooks/official/sdk/SDK_Custom_Training_Python_Package_Managed_Text_Dataset_Tensorflow_Serving_Container.ipynb
- refactors code
- formats according to template
<br>
<br>
=> chore, refactor(egen): refactors the SDK_Custom_Training_Python_Package_Managed_Text_Dataset_Tensorflow_Serving_Container notebook

notebooks/official/training/tpuv5e_gemma_peft_finetuning_and_serving.ipynb
Following are the changes included in this PR:
- fixes according to template
- changes region to location
- edits future tense appropriately. 
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tr …
=> chore, refactor(egen): tpuv5e_gemma_peft_finetuning_and_serving notebook fix

notebooks/notebook_template_review.py
Moved a couple name/variable swaps up before "Vertex AI" so that it'll catch them.
=> Minor update to notebook_template_review.py

notebooks/official/automl/sdk_automl_video_action_recognition_batch.ipynb
Converted two bullets into paragraphs because the bullets messed with how the key tasks were rendered in our docs
=> Minor update to text in sdk_automl_video_action_recognition_batch.ipynb

notebooks/official/automl/sdk_automl_video_classification_batch.ipynb
Converted two bullets into paragraphs because the bullets messed with how the key tasks were rendered in our docs
=> Minor update to text in sdk_automl_video_classification_batch.ipynb

notebooks/official/explainable_ai/sdk_automl_tabular_binary_classification_batch_explain.ipynb
Converted two bullet points into paragraphs because the bullets messed with how the key tasks were imported into our docs.
=> Minor update to text in sdk_automl_tabular_binary_classification_batch_explain.ipynb

notebooks/community/model_garden/model_garden_rag.ipynb
<br>
Add Slack and Jira Source file uploads and 3P embedding model config example for corpus creation
<br><br><br>
- [X ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/CODEOWNERS) file under the `Community Notebooks` section, pointing to the author or the author's team.
- [ X] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
=> feat: Add Slack and Jira Source file uploads and 3P embedding model config example for corpus creation

notebooks/official/training/get_started_vertex_training_lightgbm.ipynb
<br>
The notebook `get_started_vertex_training_lightgbm.ipynb` fails at running the docker container steps and Colab steps. This PR includes the following fixes:
- Dockerfile steps are updated.
- Replaces Python 3.7 base image with Python 3.9.
- Replaces docker build and docker push steps for Colab with gcloud builds submit command.
- Adds Colab enterprise link and other changes related to the new template.
- Update the requirements file and installation step.
- Replace REGION with LOCATION.
- Add steps for deleting batch prediction job and local files.
- Removes future tense and contracts words wherever needed.
- Reorganizes the section structure and updates the titles accordingly.
- Removes some redundant portion of code and steps.
<br><br><br>
**REQUIRED:** Fill out the below …
=> fix, refactor, chore: Fix docker steps, Colab steps, follows new template etc.

community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
Add common functions related to image task
=> Add common functions related to image task

notebooks/official/automl/sdk_automl_image_object_detection_batch.ipynb
- add colab enterprise
- change REGION to LOCATION
- remove boilerplate
- make changes according to template
<br>
<br>
=> chore, refactor(egen): refactors sdk_automl_image_object_detection_batch.ipynb notebook

community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
feat: Add quota check for restricted image
=> feat: Add quota check for restricted image

notebooks/official/pipelines/google_cloud_pipeline_components_automl_text.ipynb, notebooks/official/pipelines/google_cloud_pipeline_components_bqml_text.ipynb, notebooks/official/pipelines/lightweight_functions_component_io_kfp.ipynb
Modified three notebooks to resolve title issues preventing the notebook template script from running successfully.
=> fix: title modifications

notebooks/official/tabnet/ai-explanations-tabnet-algorithm.ipynb
2. Updates deletion steps in clean up section.
=> refactor(egen): template fixes, updates clean up steps 

notebooks/official/generative_ai/text_embedding_new_api.ipynb
<br>
Add one preview model `text-embedding-preview-0815` in public notebook.
<br><br><br>
<br>
<br> …
=> feat: add text-embedding-preview-0815 model to notebook

notebooks/official/ray_on_vertex_ai/get_started_with_pytorch_rov.ipynb
- makes changes according to template and authoring guide
- package versions check
- end to end test
- lint
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/community-content) …
=> chore, refactor (egen): edits get_started_with_pytorch_rov notebook

notebooks/official/generative_ai/ai21labs_intro.ipynb
<br>
Removed Europe west 4 for Jamba-large for launch
<br><br><br>
<br>
<br> …
=> fix: remove euw4 for jamba large

notebooks/official/model_monitoring/get_started_with_model_monitoring_xgboost.ipynb
1. Currently the colab enterprise link of this notebook is failing, this pr fixes that.
=> fix(egen): fixed the colab enterprise link

notebooks/official/feature_store/online_feature_serving_and_fetching_bigquery_data_with_feature_store_optimized.ipynb
=> Optimized colab changes for PSC ga

community-content/vertex_pipeline_kfpv2/evaluate-model.py
* Upload a model evaluation example by kfp v2.
=> Upload a model evaluation example

notebooks/official/generative_ai/ai21labs_intro.ipynb
<br>
Jamba large in Europe west4
<br><br><br>
<br>
<br> …
=> feat: add support for ai21 / jamba-large in euw4

community-content/vertex_cpr_samples/xgboost/predictor_Classifier.py
This example uses aiplatform and xgboost to provide a classifier predictor.
=> Upload classifier predictor sample of xgboost

notebooks/official/bigquery_ml/README.md
<br>
Remove the link of the notebook that has been moved to the community.
I will remove the forgotten link in the following PR merge.
https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/2502
<br>
<br>
2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-sample …
=> docs: remove the link of the notebook that has been moved to the community.

community-content/CODEOWNERS, community-content/vertex_model_garden/model_oss/notebook_util/common_util.py, community-content/vertex_model_garden/model_oss/notebook_util/dataset_validation_util.py, community-content/vertex_model_garden/model_oss/peft/templates/README.md, community-content/vertex_model_garden/model_oss/peft/templates/alpaca.json, community-content/vertex_model_garden/model_oss/peft/templates/alpaca_short.json, community-content/vertex_model_garden/model_oss/peft/templates/gemma.json, community-content/vertex_model_garden/model_oss/peft/templates/llama3-text-bison.json, community-content/vertex_model_garden/model_oss/peft/templates/llama3.json, community-content/vertex_model_garden/model_oss/peft/templates/mistral.json, community-content/vertex_model_garden/model_oss/peft/templates/openai-chat.json, community-content/vertex_model_garden/model_oss/peft/templates/openai-completion.json, community-content/vertex_model_garden/model_oss/peft/templates/openassistant-guanaco.json, community-content/vertex_model_garden/model_oss/peft/templates/vertex-chat.json
Add vmg templates, dataset_validation_util and update common_util
=> Add vmg templates, dataset_validation_util and update common_util

notebooks/official/workbench/predictive_maintainance/predictive_maintenance_usecase.ipynb
Added a word to make a sentence parse correctly.
=> Fixed missing word in predictive_maintenance_usecase.ipynb

notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
<br>
Add new region for Claude Haiku and Sonnet 3.5. 
<br><br><br>
<br>
<br> …
=> Update region for Claude Haiku and Sonnet 3.5

community-content/vertex_cpr_samples/sklearn/predictor_Classifier.py
* Upload a classifier predictor sample using scikit-learn lib.
=> Upload classifier predictor sample of sklearn

community-content/vertex_pipeline_kfpv2/customjob.py
* This is a custom job example of kfp v2
=> Update a custom job example

notebooks/official/CODEOWNERS, notebooks/official/generative_ai/nvidia_nim_vertexai.ipynb
<br>
Updates to colab notebook descriptions and rename of notebook
<br><br><br>
<br>
<br> …
=> refactor: NVIDIA NIM verbiage updates, minor code updates

notebooks/official/feature_store/online_feature_serving_and_vector_retrieval_bigquery_data_with_feature_store.ipynb
<br>
add PSC example code in Feature Store embedding notebook
<br><br><br>
<br>
<br> …
=> fea: add PSC example code in Feature Store embedding notebook

notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
<br>
Claude model ordering in dropdown
<br><br><br>
<br>
<br> …
=> fix: Claude model ordering in dropdown

notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
<br>
Claude update titles, headers
<br><br><br>
<br>
<br> …
=> fix: Claude update titles, headers

notebooks/official/generative_ai/text_embeddings.ipynb
**REQUIRED:** Demonstrate how to get embeddings using text-embedding-005 model.
<br>
--- Make text-embedding-005 and CODE_RETRIEVAL_QUERY the default ---
<br><br><br>
=> feat: Getting embeddings using text-embedding-005.

notebooks/community/model_garden/model_garden_gemma2_finetuning_on_vertex.ipynb, notebooks/community/model_garden/model_garden_pytorch_llama3_1_finetuning.ipynb, notebooks/community/model_garden/model_garden_pytorch_mistral_peft_tuning.ipynb, notebooks/community/model_garden/model_garden_pytorch_mixtral_peft_tuning.ipynb
=> Fix pip dependency error

notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
<br>
Claude region update(euw1)
<br><br><br>
<br>
<br> …
=> feat: Claude region update(euw1)

community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
Add ability to copy specific model artifacts
=> Add ability to copy specific model artifacts

.github/dependabot.yml
Exclude model garden docker files from dependabot checks (b/379111057)
=> feat: exclude model garden dockerfiles from dependabot checks

notebooks/official/generative_ai/mistralai_intro.ipynb
<br>
Adding support for latest version of Mistral Large in the colab.
<br><br><br>
- [ x] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [ x] Follow the style and grammar rules outlined in the above notebook template.
- [ x] Verify the notebook …
=> feat: adding support for Mistral Large 24.11 part2

notebooks/official/model_monitoring_v2/model_monitoring_for_custom_model_batch_prediction_job.ipynb
Update the model file path for the model monitoring notebook. 
The original path is no longer available.
=> fix: Update the model file path

notebooks/community/migration/UJ7 AutoML for natural language with Vertex AI Text Entity Extraction.ipynb
Remove example output as they are out of date.
=> fix: Remove example output

notebooks/community/generative_ai/backoff_and_retry_for_LLMs.ipynb
Summary:  Added the blog post URL to the notebook and updated the colab URL. No changes to the code
<br><br>
=> Added blog post URL to notebook

notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
=> feat: Deprecate Model

community-content/vertex_model_garden/model_oss/notebook_util/common_util.py, community-content/vertex_model_garden/model_oss/notebook_util/dataset_validation_util.py
Update common util and dataset validation util
=> Update common util and dataset validation util

community-content/vertex_model_garden/model_oss/notebook_util/dataset_validation_util.py
Update template location in dataset validation
=> Update template location in dataset validation

notebooks/official/CODEOWNERS, notebooks/official/feature_store/vertex_ai_feature_store_update_feature_monitor_feature_group_iam_and_service_agent.ipynb
<br>
Add example Python notebook Update Feature Monitor Feature Group IAM and Service Agent.
<br><br><br>
=> Add notebook Update Feature Monitor Feature Group IAM and Service Agent

community-content/vertex_cpr_samples/sklearn/predictor_SGDClassifier.py
This example uses aiplatform and scikit-learn library to provide a SGD classifier.
=> Upload a SGD classifier predictor example

notebooks/official/generative_ai/mistralai_intro.ipynb
=> update mistral sdk

notebooks/official/prediction/get_started_with_psc_private_endpoint.ipynb
…ractises
<br>
<br><br><br>
<br>
<br> …
=> chore: prediction psc private endpoint, add service attachment best practises

notebooks/official/generative_ai/mistralai_intro.ipynb
=> mistral small name update

community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
=> Add polling fn to common util

notebooks/official/generative_ai/ai21labs_intro.ipynb, notebooks/official/generative_ai/cambai_intro.ipynb
=> launchpad notebooks

notebooks/official/generative_ai/ai21labs_intro.ipynb, notebooks/official/generative_ai/cambai_intro.ipynb
=> lint fixed

notebooks/official/generative_ai/anthropic_claude_intro.ipynb
=> marking opus 3 as deprecated
