GoogleCloudPlatform/vertex-ai-samples

notebooks/official/CODEOWNERS
notebooks/official/matching_engine/two-tower-model-introduction.ipynb

If you are opening a PR for `Notebooks` under the [official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/master/notebooks/official) folder, follow this mandatory checklist:
If you are opening a PR for `Notebooks` under the [community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/master/notebooks/community) folder:
If you are opening a PR for `Community Content`, and it will NOT be used on cloud.google.com/docs:
If you are opening a PR for `Community Content`, and it will be used on cloud.google.com/docs:

add two tower

---

community-content/pytorch_image_classification_distributed_data_parallel_training_with_vertex_sdk/multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb
community-content/pytorch_image_classification_distributed_data_parallel_training_with_vertex_sdk/multi_node_ddp_nccl_vertex_training_with_custom_container.ipynb
community-content/pytorch_image_classification_distributed_data_parallel_training_with_vertex_sdk/requirements.txt
community-content/pytorch_image_classification_distributed_data_parallel_training_with_vertex_sdk/trainer/Dockerfile
community-content/pytorch_image_classification_distributed_data_parallel_training_with_vertex_sdk/trainer/requirements.txt
community-content/pytorch_image_classification_distributed_data_parallel_training_with_vertex_sdk/trainer/task.py
community-content/pytorch_image_classification_distributed_data_parallel_training_with_vertex_sdk/trainer/utils.py

content: add pytorch-img-cls-multi-node-ddp-cust-cont

---

community-content/tf_keras_image_classification_distributed_multi_worker_with_vertex_sdk/multi_worker_vertex_training_on_cpu_with_custom_container.ipynb
community-content/tf_keras_image_classification_distributed_multi_worker_with_vertex_sdk/multi_worker_vertex_training_on_gpu_with_custom_container.ipynb
community-content/tf_keras_image_classification_distributed_multi_worker_with_vertex_sdk/requirements.txt
community-content/tf_keras_image_classification_distributed_multi_worker_with_vertex_sdk/trainer/cpu.Dockerfile
community-content/tf_keras_image_classification_distributed_multi_worker_with_vertex_sdk/trainer/distribution_utils.py
community-content/tf_keras_image_classification_distributed_multi_worker_with_vertex_sdk/trainer/gpu.Dockerfile
community-content/tf_keras_image_classification_distributed_multi_worker_with_vertex_sdk/trainer/requirements.txt
community-content/tf_keras_image_classification_distributed_multi_worker_with_vertex_sdk/trainer/task.py

content: add tf-keras-img-cls-dist-multi-worker-cpu-cust-cont

---

notebooks/official/explainable_ai/sdk_automl_tabular_binary_classification_batch_explain.ipynb
notebooks/official/explainable_ai/sdk_automl_tabular_classification_online_explain.ipynb
notebooks/official/explainable_ai/sdk_custom_image_classification_batch_explain.ipynb
notebooks/official/explainable_ai/sdk_custom_image_classification_online_explain.ipynb
notebooks/official/explainable_ai/sdk_custom_tabular_regression_batch_explain.ipynb
notebooks/official/explainable_ai/sdk_custom_tabular_regression_online_explain.ipynb

feat: XAI SDK notebooks

---

notebooks/official/pipelines/automl_tabular_classification_beans.ipynb
notebooks/official/pipelines/control_flow_kfp.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_images.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_tabular.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_text.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb
notebooks/official/pipelines/lightweight_functions_component_io_kfp.ipynb
notebooks/official/pipelines/metrics_viz_run_compare_kfp.ipynb
notebooks/official/pipelines/pipelines_intro_kfp.ipynb

feat: use Vertex Pipelines run() method

---

notebooks/official/explainable_ai/gapic-custom_image_classification_batch_explain.ipynb
notebooks/official/explainable_ai/gapic-custom_image_classification_online_explain.ipynb
notebooks/official/explainable_ai/gapic-custom_tabular_regression_batch_explain.ipynb
notebooks/official/explainable_ai/gapic-custom_tabular_regression_online_explain.ipynb

feat: gapic XAI beta -> v1

---

notebooks/official/feature_store/gapic-feature-store.ipynb

Remove timestamp in fs id, fix_node_count reduced to 1
TESTED=manual

Remove deprecated parameters, reduce node count

---

notebooks/official/migration/UJ10 Vertex SDK Custom Scikit-Learn with pre-built training container.ipynb
notebooks/official/migration/UJ11 Vertex SDK Hyperparameter Tuning.ipynb
notebooks/official/migration/UJ14 Vertex SDK AutoML Video Classification.ipynb
notebooks/official/migration/UJ15 Vertex SDK AutoML Object Tracking.ipynb
notebooks/official/migration/UJ9 Vertex SDK Custom XGBoost with pre-built training container.ipynb

feat: sdk migration 4

---

notebooks/official/migration/UJ1 Vertex SDK AutoML Image Classification.ipynb
notebooks/official/migration/UJ2,12 Vertex SDK Custom Image Classification with pre-built training container.ipynb
notebooks/official/migration/UJ3 Vertex SDK Custom Image Classification with custom training container.ipynb
notebooks/official/migration/UJ4 Vertex SDK AutoML Tabular Binary Classification.ipynb
notebooks/official/migration/UJ5 Vertex SDK AutoML Image Object Detection.ipynb
notebooks/official/migration/UJ6 Vertex SDK AutoML Text Classification.ipynb
notebooks/official/migration/UJ7 Vertex SDK AutoML Text Entity Extraction.ipynb
notebooks/official/migration/UJ8 Vertex SDK AutoML Text Sentiment Analysis.ipynb

feat: SDK migration final

---

notebooks/official/explainable_ai/sdk_custom_tabular_regression_online_explain_get_metadata.ipynb

feat: XAI get metadata

---

notebooks/community/CODEOWNERS
notebooks/community/model_monitoring/model_monitoring_feature_attribs.ipynb

updated MM notebook w/ feature attributions

---

notebooks/community/ml_ops/stage1/get_started_bq_datasets.ipynb

feat: ML Ops

---

notebooks/community/model_monitoring/model_monitoring_feature_attribs.ipynb

update title to s/Vertex/Vertex AI/

---

notebooks/official/model_monitoring/model_monitoring.ipynb

title change: s/Vertex/Vertex AI/

---

docs/contributing.md

Added code quality checks to contributing.md

---

notebooks/community/matching_engine/matching_engine_for_indexing.ipynb

Adding "/*" to the path to delete the content, otherwise the bucket is removed.

update on gsutil command

---

notebooks/official/pipelines/control_flow_kfp.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_images.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_tabular.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_text.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb
notebooks/official/pipelines/lightweight_functions_component_io_kfp.ipynb
notebooks/official/pipelines/metrics_viz_run_compare_kfp.ipynb
notebooks/official/pipelines/pipelines_intro_kfp.ipynb

fix: updates for 0.1.9

---

notebooks/official/pipelines/automl_tabular_classification_beans.ipynb
notebooks/official/pipelines/control_flow_kfp.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_images.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_tabular.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_text.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb
notebooks/official/pipelines/lightweight_functions_component_io_kfp.ipynb
notebooks/official/pipelines/metrics_viz_run_compare_kfp.ipynb
notebooks/official/pipelines/pipelines_intro_kfp.ipynb

fix: breaking changes

---

notebooks/notebook_template.ipynb

* Uses `BUCKET_URI` instead of `BUCKET_NAME` to better reflect `gs://...` contents of variable.
* Includes project parameter when creating bucket
* Includes bucket cleanup step at end

Updated notebook template with bucket changes

---

community-content/CODEOWNERS
community-content/sklearn_text_classification_from_script_using_vertex_sdk/README.md
community-content/sklearn_text_classification_from_script_using_vertex_sdk/create_job.ipynb
community-content/sklearn_text_classification_from_script_using_vertex_sdk/requirements.txt
community-content/sklearn_text_classification_from_script_using_vertex_sdk/task.py

Train and deploy end-to-end sklearn text classifier

---

notebooks/community/managed_notebooks/fraud_detection/fraud-detection-model.ipynb

Notebook fixes to work in Workbench

---

notebooks/community/ml_ops/stage1/mlops_data_management.ipynb
notebooks/community/ml_ops/stage2/mlops_experimentation.ipynb
notebooks/community/ml_ops/stage3/get_started_with_bq_tfdv_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_dataflow_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_kubeflow_pipelines.ipynb

feat: stage 3 notebooks

---

.cloud-build/test_folders.txt

#120 is failing due to existing notebooks failing. This change will temporarily reduce the number of folders checked, to enable this PR to be merged, which enables weekly regression tests. Then, we will address the issues with the notebooks and remove these exemptions.
If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/ …

Temporary CI change to exempt failed notebooks

---

.cloud-build/test_folders.txt

Reverts GoogleCloudPlatform/vertex-ai-samples#148

Revert "Temporary CI change to exempt failed notebooks"

---

notebooks/community/ml_ops/stage2/mlops_experimentation.ipynb
notebooks/community/ml_ops/stage3/get_started_with_automl_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_bq_tfdv_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_dataflow_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_kubeflow_pipelines.ipynb

feat: updates for stage3

---

notebooks/community/ml_ops/stage2/get_started_automl_training.ipynb
notebooks/community/ml_ops/stage2/get_started_bqml_training.ipynb
notebooks/community/ml_ops/stage2/mlops_experimentation.ipynb
notebooks/community/ml_ops/stage3/get_started_with_automl_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_bq_tfdv_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_dataflow_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_kubeflow_pipelines.ipynb

feat: get started BQML

---

.cloud-build/notebook-execution-test-cloudbuild-single.yaml
.cloud-build/notebook-execution-test-cloudbuild.yaml

This step upgrades pip prior to installing dependencies. This will ensure that the latest dependency logic is being used for testing.

build: Add step to upgrade pip

---

notebooks/community/ml_ops/stage2/get_started_automl_training.ipynb
notebooks/community/ml_ops/stage2/get_started_bqml_training.ipynb
notebooks/community/ml_ops/stage2/get_started_vertex_training.ipynb
notebooks/community/ml_ops/stage3/get_started_with_dataflow_pipeline_components.ipynb

feat: stage 3 friday updates

---

notebooks/official/pipelines/custom_model_training_and_batch_prediction.ipynb

Pipelines rui

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yaml
.github/workflows/linter/run_linter.sh

The CI is currently failing due to references to `master` branch.

ci: Update .github files for main branch conversion

---

.github/workflows/linter/requirements.txt

Updating linter dependencies based on conversation in #173

ci: Update linter dependencies

---

notebooks/community/CODEOWNERS
notebooks/community/neo4j/README.md
notebooks/community/neo4j/graph_paysim.ipynb

This is the fourth!!!! PR for the Neo4j and Vertex notebook @htappen and I have been working on.  We've been having CLA issues getting it submitted.
- [ X] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under the `# Community Notebooks` section, pointing to the author or the author's team.
- [ X] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).

Add Neo4j notebook

---

notebooks/community/ml_ops/stage2/mlops_experimentation.ipynb
notebooks/community/ml_ops/stage3/get_started_with_custom_training_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/mlops_formalization.ipynb

fix: MLops 3v4 update

---

notebooks/community/ml_ops/stage2/get_started_vertex_tensorboard.ipynb
notebooks/community/ml_ops/stage2/mlops_experimentation.ipynb
notebooks/community/ml_ops/stage3/mlops_formalization.ipynb

fix: friday update

---

notebooks/community/ml_ops/stage2/mlops_experimentation.ipynb
notebooks/community/ml_ops/stage3/mlops_formalization.ipynb

feat: updates

---

notebooks/community/ml_ops/stage2/get_started_vertex_feature_store.ipynb
notebooks/community/ml_ops/stage3/get_started_with_bqml_pipeline_components.ipynb
notebooks/community/ml_ops/stage4/get_started_with_google_artifact_registry.ipynb

feat: weekly updates

---

.cloud-build/notebook-execution-test-cloudbuild-single.yaml
.cloud-build/notebook-execution-test-cloudbuild.yaml

Added private pool to cloud build config

---

notebooks/official/ml_metadata/vertex-pipelines-ml-metadata.ipynb

Update the MLMD notebook to use the `submit()` method for pipeline jobs.

Update MLMD notebook to use pipeline submit() method

---

notebooks/official/matching_engine/intro-swivel.ipynb

Fix typo: Wikepedia --> Wikipedia

---

notebooks/community/ml_ops/stage2/get_started_vertex_feature_store.ipynb
notebooks/community/ml_ops/stage3/get_started_with_bqml_pipeline_components.ipynb
notebooks/community/ml_ops/stage4/get_started_with_google_artifact_registry.ipynb
notebooks/community/ml_ops/stage4/get_started_with_vertex_ml_metadata.ipynb

feat: add ml metadata notebook

---

community-content/alphafold_on_workbench/AlphaFold.ipynb

Clarifying instruction; One instruction is Please paste the sequence of your protein in the text box below, then run the remaining cells via Runtime > Run after, but there is no Runtime tab, only Run -> Run Selected Cell and All Below

Update Run After --> Run Selected Cell and All Below

---

community-content/alphafold_on_workbench/Dockerfile

Update Dockerfile to remove warning

---

notebooks/community/ml_ops/stage3/get_started_with_bqml_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_hpt_pipeline_components.ipynb

feat: add notebooks

---

.github/workflows/linter/run_linter.sh

Removed "--nbqa-mutate" as it is now unneeded.

Removed unneeded lines in linter

---

notebooks/community/managed_notebooks/pricing_optimization/pricing-optimization.ipynb

This PR contains notebook which demonstrates analysis of pricing optimization on [CDM Pricing Data](https://github.com/trifacta/trifacta-google-cloud/blob/main/design-pattern-pricing-optimization/CDM_Pricing_large_table.csv)

Pricingoptimization

---

notebooks/community/ml_ops/stage4/get_started_with_vertex_xai.ipynb

feat: XAI notebook

---

notebooks/community/ml_ops/stage4/get_started_with_vertex_xai.ipynb

feat: XAI with sklearn

---

README.md

This PR adds a section at the bottom of the README with a survey for users to provide in-depth feedback.

Add survey to README.md

---

notebooks/notebook_template.ipynb

Removed `globals` from cleanup

Cleaned up cleanup section

---

notebooks/community/ml_ops/stage3/mlops_formalization.ipynb
notebooks/official/pipelines/custom_model_training_and_batch_prediction.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_images.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_tabular.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_automl_text.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb

feat: update to v1

---

notebooks/official/pipelines/pipelines_intro_kfp.ipynb

test: fix for testing

---

notebooks/community/ml_ops/stage3/get_started_with_bqml_pipeline_components.ipynb

Use importer for the bqml

---

notebooks/community/ml_ops/stage3/get_started_with_hpt_pipeline_components.ipynb

update hp tuning sample to use importer

---

notebooks/community/managed_notebooks/inventory-prediction/inventory_prediction.ipynb

Revising text for branding, clarity, grammar/spelling

Inventory prediction update

---

notebooks/community/managed_notebooks/predictive_maintainance/Predictive_maintenance_usecase.ipynb

Updating text for branding, clarity, and spelling/grammar

Predictive maintenance update

---

notebooks/community/managed_notebooks/sentiment_analysis/Sentiment_Analysis.ipynb

updating text for branding, spelling/grammar, clarity

Sentiment analysis update

---

notebooks/community/matching_engine/matching_engine_for_indexing.ipynb

Switched to gs://cloud-samples-data/vertex-ai/matching_engine/glove-100-angular.hdf5

Matching Engine: Updated location for data

---

notebooks/community/ml_ops/stage2/get_started_bqml_training.ipynb

fix: bqml doc for exporting model

---

notebooks/community/ml_ops/stage3/get_started_with_automl_pipeline_components.ipynb

fix: automl eval component improvement

---

.github/workflows/ci.yaml

Only run when PR contains a notebook file

ci: Apply filter to format_and_lint_job

---

notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb

fix: v1 upgrades

---

notebooks/community/ml_ops/stage3/get_started_with_bqml_pipeline_components.ipynb
notebooks/community/ml_ops/stage3/get_started_with_hpt_pipeline_components.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb

fix: upgrades to v1

---

notebooks/community/ml_ops/stage1/get_started_dataflow.ipynb

fix: missing create dataset schema

---

notebooks/community/ml_ops/stage2/get_started_vertex_feature_store.ipynb

feat: add example of FS values from dataframe

---

notebooks/community/ml_ops/stage6/get_started_with_cpr.ipynb

feat: add CPR notebook

---

notebooks/community/ml_ops/stage6/get_started_with_cpr.ipynb

feat: more CPR

---

notebooks/official/feature_store/gapic-feature-store.ipynb

buganizer:  https://buganizer.corp.google.com/issues/216819898

Featurestore colab update

---

notebooks/community/ml_ops/stage2/get_started_vertex_vizier.ipynb

In this PR we are making minor changes to get_started_vertex_vizier notebook community version

Made small changes to Get started vertex vizier notebook

---

notebooks/official/migration/UJ15 Vertex SDK AutoML Object Tracking.ipynb
notebooks/official/migration/UJ2,12 Vertex SDK Custom Image Classification with pre-built training container.ipynb
notebooks/official/migration/UJ3 Vertex SDK Custom Image Classification with custom training container.ipynb
notebooks/official/migration/UJ5 Vertex SDK AutoML Image Object Detection.ipynb
notebooks/official/migration/UJ6 Vertex SDK AutoML Text Classification.ipynb
notebooks/official/migration/UJ7 Vertex SDK AutoML Text Entity Extraction.ipynb
notebooks/official/migration/UJ8 Vertex SDK AutoML Text Sentiment Analysis.ipynb
notebooks/official/migration/UJ9 Vertex SDK Custom XGBoost with pre-built training container.ipynb
notebooks/official/pipelines/metrics_viz_run_compare_kfp.ipynb

fix: replace os.environ with os.getenv - 2nd batch

---

notebooks/community/ml_ops/stage2/get_started_vertex_training_sklearn.ipynb

This PR contains a notebook that demonstrates how to use Vertex AI for E2E MLOps on Google Cloud in production. This tutorial covers stage 2 : experimentation: get started with Vertex Training for Scikit-Learn.
If you are opening a PR for Community Notebooks under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:

E2E ML on GCP: MLOps stage 2 : experimentation: get started with Vertex Training for Scikit-Learn

---

notebooks/community/ml_ops/stage2/get_started_automl_training.ipynb

update: for official

---

notebooks/community/ml_ops/stage2/get_started_automl_training.ipynb
notebooks/community/ml_ops/stage3/get_started_with_bqml_pipeline_components.ipynb

cleanup: delete created resources in the pipeline

---

notebooks/community/ml_ops/stage2/get_started_vertex_experiments.ipynb

Opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
Opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:

Updates the Mlops/stage2/ get-started-vertex-experiments notebook in the community folder

---

notebooks/official/pipelines/pipelines_intro_kfp.ipynb

fix: testing issues

---

notebooks/community/ml_ops/stage1/get_started_with_data_labeling.ipynb

feat: add data labeling notebook

---

notebooks/community/ml_ops/stage1/get_started_with_data_labeling.ipynb
notebooks/community/ml_ops/stage3/get_started_with_kubeflow_pipelines.ipynb

update: details on dsl.Condition

---

.cloud-build/test_folders.txt

In this PR, we added mlops folder to tested_folders file

added mlops folder to tested_folders file

---

notebooks/community/ml_ops/stage6/get_started_with_vertex_endpoints.ipynb

Ml ops 7v2

---

notebooks/community/ml_ops/stage3/get_started_with_dataproc_serverless_pipeline_components.ipynb

Fix typo in notebook heading.

---

notebooks/community/ml_ops/stage6/get_started_with_fastapi.ipynb
notebooks/community/ml_ops/stage6/get_started_with_tf_serving.ipynb

feat: add notebook for FastAPI server

---

notebooks/community/ml_ops/stage2/get_started_bqml_training.ipynb

feat: add BQML + MR example

---

notebooks/community/ml_ops/stage2/get_started_bqml_training.ipynb
notebooks/community/ml_ops/stage6/get_started_with_optimized_tfe_bert.ipynb

Ml ops 7v6

---

notebooks/community/ml_ops/stage1/get_started_with_data_labeling.ipynb

Made minor changes to get_started_with_data_labeling_2

Made minor changes to get_started_with_data_labeling_2

---

notebooks/community/ml_ops/stage3/get_started_with_bqml_pipeline_components.ipynb

Made minor changes to get_started_with_bqml_pipeline_components file

Made minor changes to get_started_with_bqml_pipeline_components file

---

notebooks/community/ml_ops/stage3/get_started_with_custom_training_pipeline_components.ipynb

Made minor changes to get_started_with_custom_training_pipeline_components file

Made minor changes to get_started_with_custom_training_pipeline_components file

---

notebooks/community/CODEOWNERS
notebooks/community/vertex_endpoints/optimized_tensorflow_runtime/benchmark.py
notebooks/community/vertex_endpoints/optimized_tensorflow_runtime/bert_optimized_online_prediction.ipynb
notebooks/community/vertex_endpoints/optimized_tensorflow_runtime/tabular_optimized_online_prediction.ipynb

Adding samples for Vertex AI Prediction optimized TensorFlow runtime

---

notebooks/community/hyperparameter_tuning/distributed-hyperparameter-tuning.ipynb

This PR contains a notebook that demonstrates how to run a hyperparameter tuning job with Vertex Training to discover optimal hyperparameter values for an ML model. To speed up the training process, MirroredStrategy from the tf.distribute module is used to distribute training across multiple GPUs on a single machine.

Refresh of Distributed Hyperparameter Tuning for Colab

---

notebooks/community/vertex_endpoints/optimized_tensorflow_runtime/bert_optimized_online_prediction.ipynb
notebooks/community/vertex_endpoints/optimized_tensorflow_runtime/tabular_optimized_online_prediction.ipynb

Minor updates basing on team feedback

---

notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb

fix: Issue 451, add db-dtypes to requirements

---

notebooks/official/pipelines/google_cloud_pipeline_components_model_upload_predict_evaluate.ipynb

feat: update model eval metrics for comparison

---

notebooks/official/pipelines/google_cloud_pipeline_components_model_upload_predict_evaluate.ipynb

fix: SaraRob installation updates

---

notebooks/community/ml_ops/stage6/get_started_with_tf_serving.ipynb

feat: add docker support in Colab

---

notebooks/community/ml_ops/stage2/get_started_vertex_training.ipynb
notebooks/community/ml_ops/stage6/get_started_with_tf_serving.ipynb

fix: notebook run in colab

---

notebooks/community/ml_ops/stage3/get_started_with_bq_tfdv_pipeline_components.ipynb

Added service account fetch code for colab in get_started_with_bq_tfdv_pipeline_components file

Added service account fetch code for colab in get_started_with_bq_tfdv_pipeline_components file

---

notebooks/community/ml_ops/stage3/get_started_with_bqml_pipeline_components.ipynb

Added service account fetch code for colab in get_started_with_bqml_pipeline_components file

Added service account fetch code for colab in get_started_with_bqml_pipeline_components file 

---

notebooks/community/ml_ops/stage3/get_started_with_custom_training_pipeline_components.ipynb

Added service account fetch code for colab in get_started_with_custom_training_pipeline_components file

Added service account fetch code for colab in get_started_with_custom_training_pipeline_components file

---

notebooks/community/ml_ops/stage3/get_started_with_rapid_prototyping_bqml_automl.ipynb

Added service account fetch code for colab in get_started_with_rapid_prototyping_bqml_automl file

Added service account fetch code for colab in get_started_with_rapid_prototyping_bqml_automl file

---

notebooks/community/ml_ops/stage2/get_started_with_visionapi_and_automl.ipynb

feat: vision api and automl

---

notebooks/community/ml_ops/stage2/get_started_with_visionapi_and_automl.ipynb
notebooks/community/ml_ops/stage3/get_started_with_machine_management.ipynb

feat: machine resource settings

---

notebooks/community/matching_engine/sdk_matching_engine_for_indexing.ipynb

Matching Engine Vertex SDK API is released. This is an update of the notebook.

fix: Updated matching engine dependency and fixed cases

---

notebooks/community/ml_ops/stage6/get_started_with_matching_engine_twotowers.ipynb

fix: two towers

---

notebooks/community/ml_ops/stage6/get_started_with_matching_engine_twotowers.ipynb

fix: typos in two towers

---

notebooks/community/ml_ops/stage4/get_started_with_google_artifact_registry.ipynb
notebooks/community/ml_ops/stage4/get_started_with_model_evaluation.ipynb
notebooks/community/ml_ops/stage4/get_started_with_vertex_ml_metadata.ipynb
notebooks/community/ml_ops/stage4/get_started_with_vertex_xai.ipynb

fix: DPE-style tuning

---

notebooks/notebook_template.ipynb

update: new template edition

---

notebooks/community/ml_ops/stage1/get_started_vertex_datasets.ipynb
notebooks/community/ml_ops/stage1/get_started_with_data_labeling.ipynb

fix: enable APIs stage1

---

notebooks/official/custom/sdk-custom-image-classification-batch.ipynb

upgrade: notebook to current standards

---

notebooks/official/ml_metadata/sdk-metric-parameter-tracking-for-locally-trained-models.ipynb

upgrade: current notebook standard

---

notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb

upgrade: current notebook standards

---

notebooks/official/README.md

update: add index

---

notebooks/official/automl/automl-text-classification.ipynb

upgrade: updated curated notebook to current standards

---

notebooks/community/CODEOWNERS
notebooks/community/neo4j/graph_paysim.ipynb

Update Neo4j notebook to use Neo4j Graph Data Science client for the upcoming Neo4j AuraDS & VertexAI blogpost.
If you are opening a PR for Community Notebooks under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/CODEOWNERS) file under the Community Notebooks section, pointing to the author or the author's team.
Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

feat: adding code owners and updating graph_paysim

---

notebooks/community/ml_ops/stage1/get_started_with_visionapi_and_vertex_datasets.ipynb

update: fine-tuning notebook

---

notebooks/official/experiments/comparing_local_trained_models.ipynb

A PR to release the official experiments notebook - CUJ1.

inardini - experiments cuj1 notebook release

---

.cloud-build/execute_changed_notebooks_helper.py
.cloud-build/execute_notebook_helper.py
.cloud-build/notebook-execution-test-cloudbuild-single.yaml
.cloud-build/notebook-execution-test-cloudbuild.yaml

Without a virtualenv, the container sometimes looks for dependency in incorrect areas.

Added a virtualenv to the notebook execution tests which should help with dependency issues

---

notebooks/official/CODEOWNERS
notebooks/official/experiments/comparing_pipeline_runs.ipynb

A PR to release the official experiments notebook - CUJ3.

inardini - experiments cuj3 notebook release

---

notebooks/community/ml_ops/stage4/get_started_with_vertex_ml_metadata_and_automl.ipynb

Fix: remove hardwired project number

---

notebooks/community/ml_ops/stage2/get_started_vertex_experiments.ipynb
notebooks/community/ml_ops/stage2/get_started_with_logging.ipynb

update: refine experiments notebook

---

notebooks/community/matching_engine/sdk_matching_engine_for_indexing.ipynb

Text tweaks and simplifications.

Tweaks to matching engine notebook

---

notebooks/community/ml_ops/stage3/get_started_with_automl_tabular_pipeline_workflow.ipynb
notebooks/community/ml_ops/stage3/get_started_with_model_registry.ipynb

feat: notebook for automl tabular workflow

---

notebooks/community/ml_ops/stage3/get_started_with_automl_tabular_pipeline_workflow.ipynb
notebooks/community/ml_ops/stage3/get_started_with_model_registry.ipynb

fix: bad link

---

notebooks/official/model_monitoring/model_monitoring.ipynb

avoid linter reformatting that breaks this notebook in colab

---

notebooks/community/CODEOWNERS
notebooks/community/gapic/custom/showcase_custom_image_classification_online_explain_example_based_api.ipynb

The notebook shows a simple example of how using Example-Based API with images

inardini - vertex explainable ai example based api example using sdk gapic

---

notebooks/community/model_monitoring/batch_prediction_model_monitoring.ipynb

add community notebook

---

.cloud-build/execute_changed_notebooks_helper.py
.cloud-build/execute_notebook_helper.py

Added better download instructions and a web link for direct download.

Added better download instructions

---

notebooks/community/prediction/custom_prediction_routines/SDK_Custom_Predict_SDK_Integration.ipynb
notebooks/community/prediction/custom_prediction_routines/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb
notebooks/community/prediction/custom_prediction_routines/SDK_Custom_Preprocess.ipynb
notebooks/community/prediction/custom_prediction_routines/SDK_Pytorch_Custom_Predict.ipynb
notebooks/community/prediction/custom_prediction_routines/SDK_Triton_PyTorch_Local_Prediction.ipynb

- Update interfaces
- Fix missing timestamp
- Rename some variables

Update CPR notebooks.

---

notebooks/community/ml_ops/stage6/get_started_automl_tabular_exported_deploy.ipynb

feat: notebook for importing automl tabular model

---

notebooks/community/ml_ops/stage2/get_started_vertex_hpt_xgboost.ipynb
notebooks/community/ml_ops/stage6/get_started_automl_tabular_exported_deploy.ipynb

feat: add notebook for non-TF HPT

---

notebooks/notebook_template.ipynb

feat: tune template

---

notebooks/community/ml_ops/stage1/get_started_bq_datasets.ipynb
notebooks/community/ml_ops/stage1/get_started_dataflow.ipynb
notebooks/community/ml_ops/stage1/get_started_vertex_datasets.ipynb
notebooks/community/ml_ops/stage1/get_started_with_data_labeling.ipynb
notebooks/community/ml_ops/stage1/get_started_with_visionapi_and_vertex_datasets.ipynb
notebooks/community/ml_ops/stage1/mlops_data_management.ipynb
notebooks/notebook_template.ipynb

fix: auto review

---

notebooks/community/prediction/custom_prediction_routines/SDK_Triton_PyTorch_Local_Prediction.ipynb

samples: Minor fix for CPR existing image use cases.

---

.cloud-build/cleanup/cleanup-requirements.txt

Added missing ratemate dependency.

Added missing dependency

---

.cloud-build/execute_notebook_helper.py

Move download link up to better debug.

Move download link up

---

notebooks/official/pipelines/custom_model_training_and_batch_prediction.ipynb

<br>
changed based on review comments
<br><br><br>

custom_model_training_and_batch_prediction

---

notebooks/official/model_monitoring/model_monitoring.ipynb

<br>
I fixed minor deviations from the notebook template. No substance change otherwise.
<br><br><br>
<br>
<br> …

Model monitoring

---

notebooks/community/ml_ops/stage6/get_started_with_matching_engine_swivel.ipynb

<br>
fix: typo found by user. DELOY_IMAGE -> DEPLOY_IMAGE
<br><br><br>
<br>
<br> …

fix: typo in serving_container_uri parameter

---

notebooks/official/matching_engine/intro-swivel.ipynb

<br>
A CE reported a problem with this notebook. You get an error when the template script stored in GCS bucket, puts tabs instead of spaces in the generated JSON file. A invalid format error then subsequently occurs when the JSON file is ingested. I added a sed command to replace the tabs with spaces.
<br><br><br>
<br>
2. If you are opening a PR …

fix: replace tabs with spaces in JSON template

---

notebooks/official/training/multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb

<br>
Modified notebook multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb
<br><br><br>
<br>

Modified notebook multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb

---

notebooks/community/ml_ops/stage7/model_monitoring_setup.ipynb

<br>
New notebook covering setting up monitoring jobs and administrative tasks.
<br><br><br>
<br>
<br> …

feat: model monitor notebook

---

notebooks/community/prediction/custom_prediction_routines/SDK_Custom_Preprocess.ipynb

This fix was previously made by Yang Pan in https://github.com/googleapis/python-aiplatform/pull/1437 but closed due to the notebook being moved out of the main Vertex SDK repo.
<br>
<br><br><br>
<br> …

chore: fix typo in notebook

---

notebooks/community/ml_ops/stage5/get_started_with_vertex_endpoints.ipynb

<br>
Replace KFP related bug workaround with newest GetVertexModelOp, which does not require the workaround.
<br><br><br>
<br>
<br> …

update: GetVertexModelOp

---

notebooks/community/ml_ops/stage7/model_monitoring_automl.ipynb
notebooks/community/ml_ops/stage7/model_monitoring_custom.ipynb
notebooks/community/ml_ops/stage7/model_monitoring_setup.ipynb

<br>
Add new notebook for model monitoring AutoML models.
Also touch up text blocks of the two previous model monitoring notebook
<br><br><br>
<br>
<br>
3. If you are …

feat: add notebook for MM autoML

---

notebooks/community/ml_ops/stage6/get_started_with_custom_image_model_batch.ipynb

<br>
Added a notebook for doing batch prediction with custom image models
<br><br><br>
<br>
<br> …

feat: notebook for batch prediction with custom image model

---

notebooks/community/ml_ops/stage6/get_started_with_custom_image_model_batch.ipynb

<br>
Add example of batch prediction using File-List format.
<br><br><br>
<br>
<br> …

feat: extend image batch notebook

---

notebooks/community/ml_ops/stage6/get_started_with_tf_serving.ipynb

<br>
Latest TF Serving 2.9 has a regression. Using an earlier pinned version now.
<br><br><br>
<br>
<br> …

fix: tf serving workaround

---

notebooks/community/ml_ops/stage6/get_started_with_custom_image_model_batch.ipynb
notebooks/community/ml_ops/stage6/get_started_with_custom_tabular_model_batch.ipynb

<br>
Add notebook for different ways of doing batch prediction in custom tabular models.
Also an update to remove the 'BLAH' in the custom image model notebook version.
<br><br><br>
<br>
2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/com …

feat: Batch prediction for custom tabular model

---

notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb

<br>
Fixed the download_url in the "Open in Vertex AI Workbench" link
<br><br><br>
<br>
<br> …

fix: correct the download_url

---

notebooks/community/ml_ops/stage6/get_started_with_automl_image_model_batch.ipynb

<br>
Added notebook for AutoML image model batch predict
<br><br><br>
<br>
<br> …

feat: notebook for batch predict for automl image models

---

notebooks/community/ml_ops/stage6/get_started_with_automl_tabular_model_batch.ipynb

<br>
Add notebook to cover input/output formats for batch prediction in AutoML tabular models
<br><br><br>
<br>
<br> …

feat: batch prediction for automl tabular models

---

notebooks/community/ml_ops/stage6/get_started_with_automl_text_model_batch.ipynb

<br>
Added notebook for doing batch prediction with AutoML text models
<br><br><br>
<br>
<br> …

feat: batch prediction for AutoML text models

---

notebooks/community/ml_ops/stage6/get_started_with_automl_image_model_batch.ipynb
notebooks/community/ml_ops/stage6/get_started_with_automl_tabular_model_batch.ipynb
notebooks/community/ml_ops/stage6/get_started_with_automl_text_model_batch.ipynb
notebooks/community/ml_ops/stage6/get_started_with_custom_image_model_batch.ipynb

<br>
Fix grammar/formatting of a few text cells
<br><br><br>
<br>
<br> …

fix: finetuning of batch notebooks

---

notebooks/official/model_monitoring/model_monitoring.ipynb

add back pip install of xai sdk

---

notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb

<br>
Cloud Resource Manager API is required to be enabled in order to get this notebook to work.
<br><br><br>
<br>
<br> …

Enable Cloud Resource Manager API

---

notebooks/official/pipelines/pipelines_intro_kfp.ipynb

<br>
Remove outdated example `create_schedule_from_job_spec` per request
<br><br><br>
<br>
<br> …

Issue 235883443

---

notebooks/community/CODEOWNERS
notebooks/community/matching_engine/stream_update_for_matching_engine.ipynb

<br>
Create this community python notebook to demonstrate StreamUpdate features of Matching Engine to public.
<br><br><br>
<br>
<br> …

Stream Update v2

---

notebooks/notebook_template_review.py

<br>
updated rule for copyright cell detection to cover alternate forms
<br><br><br>
<br>
<br> …

fix: detecting copyright cell

---

notebooks/community/ml_ops/stage2/get_started_automl_training.ipynb

<br>
Add text explanations for all the data item input formats for AutoML Datasets
<br><br><br>
<br>
<br> …

fix: add details on dataset input formats

---

notebooks/community/ml_ops/stage6/get_started_with_automl_image_model_online.ipynb

<br>
Add Get Started notebook for doing online predictions with AutoML image models.
<br><br><br>
<br>
<br> …

feat: notebook for automl image online prediction

---

notebooks/community/ml_ops/stage6/get_started_with_automl_image_model_online.ipynb

<br>
Add deleting the dataset for notebook cleanup
<br><br><br>
<br>
<br> …

fix: missing delete dataset

---

notebooks/community/ml_ops/stage7/get_started_with_model_monitoring_automl.ipynb
notebooks/community/ml_ops/stage7/get_started_with_model_monitoring_custom.ipynb
notebooks/community/ml_ops/stage7/get_started_with_model_monitoring_custom_tf_serving.ipynb
notebooks/community/ml_ops/stage7/get_started_with_model_monitoring_setup.ipynb

<br>
Fix CE reported dependency errors with the pip installs on model monitoring notebooks
<br><br><br>
<br>
<br> …

fix: pip dependency fixes

---

notebooks/official/experiments/comparing_local_trained_models.ipynb
notebooks/official/migration/UJ4 Vertex SDK AutoML Tabular Binary Classification.ipynb

<br>
This PR has the goal to update Vertex AI Experiment notebook based on collected feedback. 
<br><br><br>

Vertex AI Experiments - Comparing local trained models notebook - update

---

notebooks/official/experiments/comparing_local_trained_models.ipynb

<br>
This PR is about fixing some title format issue. 
<br><br><br>

Vertex AI Experiments - Title fix

---

notebooks/official/vizier/gapic-vizier-multi-objective-optimization.ipynb

<br>
Update the vizier sample to replace the gapic library with new Vertex Vizier SDK.
<br><br><br>
<br>
<br> …

Update the vizier sample to replace the gapic library with new Vertex Vizier SDK.

---

notebooks/community/model_monitoring/batch_prediction_model_monitoring.ipynb

<br>
Initial revisions:
1. Replace gcloud with Vertex AI SDK
2. Fix copyright
3. Add missing Open in Workbench
4. Updated installation
<br><br><br>
<br>
5. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
<br>
6. If you …

Model monitor batch

---

notebooks/community/ml_ops/stage2/get_started_vertex_vizier.ipynb

<br>
Replace GAPIC with SDK calls
<br><br><br>
<br>
<br> …

Vizier sdk

---

notebooks/notebook_template_review.py

<br>
Fix not requiring a value for arguments not needing a value.
Add argument and code to parse a list of notebooks specified by a file.
<br><br><br>
<br>
<br>
3. If you …

fix: argument handling improvements

---

notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb

<br>
Add missing service_account=SERVICE_ACCOUNT param to job.run().
<br><br><br>
<br>
<br> …

Issue  937

---

notebooks/notebook_template_review.py

<br>
Add I/O to abbr list
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/ve …

fix: add abbr

---

notebooks/official/experiments/comparing_pipeline_runs.ipynb

<br>
Fix workbench link
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vert …

fix: bad links

---

notebooks/notebook_template_review.py

<br>
Add/improve argument handling
Improve bad link detection
Add generating webdoc format output
<br><br><br>
<br>
<br> …

fix: improve args and add webdoc generation

---

notebooks/curated.csv

Added tags, links to corresponding documentation pages

Added tags, links to corresponding documentation pages

---

notebooks/curated.csv
notebooks/notebook_template_review.py

Fixed line break

---

notebooks/notebook_template_review.py

<br>
Add code to calculate what the links should be for notebooks being checked in the first time -- i.e., don't yet exist in git.
<br><br><br>
<br>
<br>
3. If you are …

feat: calculate links for new notebooks

---

notebooks/notebook_template_review.py

<br>
Per pair programming, now output linkbacks for web output.
<br><br><br>
<br>
<br> …

fix: handling of linkback for web output

---

notebooks/curated.csv
notebooks/notebook_template_review.py

<br>
Fine-tuning of tags for outputting in markdown format
<br><br><br>
<br>
<br> …

Autoreview 10

---

notebooks/official/reduction_server/pytorch_distributed_training_reduction_server.ipynb

<br>
Added a new official notebook to demonstrate how to run a PyTorch distributed training job on Vertex AI Reduction Server.
<br><br><br>
<br>
<br>
3. If you are …

New notebook for PyTorch distributed training on reduction server

---

notebooks/notebook_template_review.py

<br>
Fix bug in code of comparing current tag to last seen tags
<br><br><br>
<br>
<br> …

fix: last tag handling

---

notebooks/notebook_template_review.py
notebooks/official/automl/automl-tabular-classification.ipynb

<br>
Fix handling no tags
Fix objective conformance in notebook
<br><br><br>
<br>
<br> …

fix: tag handling

---

notebooks/official/custom/SDK_Custom_Container_Prediction.ipynb
notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb
notebooks/official/custom/custom_training_tensorboard_profiler.ipynb

<br>
Fix objective conformance
<br><br><br>
<br>
<br> …

Autoreview 17

---

notebooks/official/automl/automl_tabular_on_vertex_pipelines.ipynb
notebooks/official/automl/sdk_automl_tabular_regression_batch_bq.ipynb
notebooks/official/automl/sdk_automl_text_entity_extraction_online.ipynb
notebooks/official/automl/sdk_automl_video_object_tracking_batch.ipynb

<br>
Fix objective section to conform to template
<br><br><br>
<br>
<br> …

fix: objective conformance

---

notebooks/official/explainable_ai/sdk_automl_tabular_classification_online_explain.ipynb
notebooks/official/explainable_ai/sdk_custom_tabular_regression_batch_explain.ipynb

<br>
Update the autogen index after fine tuning of Objective sections
<br><br><br>
<br>
<br> …

feat: update autogen index for official/explainable_ai

---

notebooks/official/explainable_ai/README.md
notebooks/official/explainable_ai/sdk_automl_tabular_classification_online_explain.ipynb
notebooks/official/explainable_ai/sdk_custom_tabular_regression_batch_explain.ipynb

<br>
missed adding the README to PR
<br><br><br>
<br>
<br> …

feat: update autogen index for official/explainable_ai 

---

notebooks/official/automl/README.md
notebooks/official/explainable_ai/README.md
notebooks/official/feature_store/README.md
notebooks/official/matching_engine/README.md
notebooks/official/ml_metadata/README.md
notebooks/official/model-registry/README.md
notebooks/official/model_evaluation/README.md
notebooks/official/model_monitoring/README.md
notebooks/official/pipelines/README.md
notebooks/official/reduction_server/README.md
notebooks/official/sdk/README.md
notebooks/official/structured_data/README.md
notebooks/official/tabnet/README.md
notebooks/official/tabular_workflows/README.md
notebooks/official/tensorboard/README.md
notebooks/official/training/README.md
notebooks/official/vizier/README.md

<br>
Fix git link generated using wrong variable
<br><br><br>
<br>
<br> …

fix: incorrect linking

---

notebooks/official/explainable_ai/sdk_custom_tabular_regression_online_explain.ipynb
notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb
notebooks/official/training/multi_node_ddp_nccl_vertex_training_with_custom_container.ipynb

<br>
Fix remaining notebooks that had some conformance issues with the objective cell
<br><br><br>
<br>
<br> …

fix: loose ends on objective conformance

---

notebooks/notebook_template_review.py

<br>
1. Send errors to stderr
2. Add more branding checks
3. Exit non-zero if errors
<br><br><br>
<br>
<br>
4. If you are opening a PR for `Community Content` under the …

updates: autoreview

---

notebooks/official/reduction_server/README.md
notebooks/official/reduction_server/pytorch_distributed_training_reduction_server.ipynb

<br>
Improved notebook comments and readme
<br><br><br>
<br>
<br> …

fix: improved notebook comments and readme

---

notebooks/official/migration/UJ1 Vertex SDK AutoML Image Classification.ipynb

<br>
Resolved tensor flow library issues. made changes based on template notebook standards.
<br><br><br>
<br>

Vertex SDK AutoML Image Classification

---

notebooks/official/automl/automl_forecasting_bqml_arima_plus_comparison.ipynb

<br>
**Changed made**: Modified file automl_forecasting_bqml_arima_plus_comparison according to notebook template
<br><br><br>
<br>

Modified file automl_forecasting_bqml_arima_plus_comparison

---

notebooks/community/CODEOWNERS
notebooks/official/CODEOWNERS

<br>
Make correction to notebook ownership
<br><br><br>
<br>
<br> …

switch mm ownership to Andy

---

notebooks/notebook_template_review.py

<br>
First round for updating script for formatting requirements:
1. More error codes converted to constants.
2. Some docstrings added
3. Some type hints added
4. Add some text what the rules are.
<br><br><br>
<br>
5. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-sam …

fix: script format

---

notebooks/official/workbench/spark/spark_ml.ipynb

Some clean up / typo fixes / added helper notes to spark_ml notebook.

minor fixes

---

notebooks/community/ml_ops/stage1/get_started_bq_datasets.ipynb

<br>
File got corrupted during merge conflict fix. Trying again.
<br><br><br>
<br>
<br> …

fix: merge corruption

---

notebooks/official/pipelines/google_cloud_pipeline_components_dataproc_tabular.ipynb

<br>
<p>Add gcloud calls to activate services:
<br>• Artifact Registry
<br>• Cloud Build
<br>• Container Registry
<br>• Dataproc
<br>• Vertex AI
</p>
<p>Add missing --quiet flag when using `gcloud artifacts repositories create`, which causes the cell to wait on a prompt.</p>
<p>Changed ${CWD} to {CWD} (removed spurious $ character) in the "Build the model serving container image" step. This causes the `cd` into the scala-sbt source directory to fail. The scala-sbt builder doesn't build, which then causes Cloud Build to not find the scala-sbt builder when trying to build the Spark serving image.</p>
<p>Changed DEPLOY_MODEL …

Bug fixes and automation improvements for google_cloud_pipeline_components_dataproc_tabular.ipynb

---

notebooks/notebook_template_review.py

<br>
Per review:
Change enum ErrorCodes to enum ErrorCode
Change nth to cell_index
<br><br><br>
<br>
<br> …

fix: enum and cell index naming

---

notebooks/notebook_template_review.py

<br>
About 1/2 of parse methods converted to abstract class rules.
2nd round update. Converted all parse methods to abstract class rules.
<br><br><br>
<br>
<br>
3. If you …

fix: working on abstract class

---

notebooks/community/ml_ops/stage1/get_started_bq_datasets.ipynb
notebooks/community/ml_ops/stage1/get_started_dataflow.ipynb
notebooks/community/ml_ops/stage1/get_started_vertex_datasets.ipynb
notebooks/community/ml_ops/stage2/get_started_vertex_hpt_r_kernel.ipynb
notebooks/community/ml_ops/stage2/get_started_vertex_tensorboard.ipynb
notebooks/community/ml_ops/stage2/get_started_vertex_training_lightgbm.ipynb
notebooks/community/ml_ops/stage2/get_started_vertex_training_pytorch.ipynb

<br>
Fixed a few missed bad links
<br><br><br>
<br>
<br> …

fix: missed bad links

---

notebooks/community/ml_ops/stage2/get_started_vertex_training_xgboost.ipynb

<br>
Fix training code to train a multi-class classifier
Updated here/there to conform to template
<br><br><br>
<br>
<br> …

fix: multi-class vs binary classifier

---

notebooks/community/ml_ops/stage3/get_started_vertex_pipelines_sklearn_with_prediction.ipynb

<br>
Add notebook using pipeline to train, deploy a scilearn-model and then do an online prediction
<br><br><br>
<br>
<br> …

feat: add sklearn pipeline notebook

---

notebooks/community/ml_ops/stage6/get_started_with_tf_serving_tabular.ipynb

<br>
Request from CE. Copied existing TF Serving/Vertex notebook that use TF image model and replaced with TF tabular model.
<br><br><br>
<br>
<br>
3. If you are opening …

feat: TF Serving with TF tabular model

---

notebooks/official/training/hyperparameter_tuning_tensorflow.ipynb

fix broken links in hptune sample.

fix broken links in hptune example

---

notebooks/community/ml_ops/stage6/get_started_with_tf_serving_tabular.ipynb

<br>
Text change from aip.AcceleratorType to aip.gapic.AcceleratorType
remove testing code
<br><br><br>
<br>
<br> …

fix: error in text cell

---

notebooks/community/CODEOWNERS
notebooks/community/experiments/vertex_ai_model_experimentation.ipynb

<br>
This PR is about an end-to-end notebook to show main capabilities of Vertex AI Experiments.
<br>
<br>
<br>

Vertex AI Experiments - All-in-one notebook

---

notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb

Linted notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb.

Linted file: notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb

---

notebooks/community/ml_ops/stage2/get_started_with_vertex_experiments_autologging_tf.ipynb

<br>
Correct preamble (replace Model with Dataset)
Add autologging the model size
<br><br><br>
<br>
<br> …

feat: log model size

---

.cloud-build/execute_changed_notebooks_helper.py
.cloud-build/utils/NotebookProcessors.py
.cloud-build/utils/util.py
notebooks/notebook_template.ipynb
notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb

- Reduce boilerplate for custom tabular bq notebook
- Default region to us-central1 to reduce user friction.

Reduce boilerplate for custom tabular bq notebook

---

notebooks/official/tensorboard/tensorboard_vertex_ai_pipelines_integration.ipynb

fix vertex ai pipelines name issue and rename the colab

---

notebooks/community/CODEOWNERS
notebooks/official/CODEOWNERS

<br>
Moves the owners info. from community/CODEOWNERS to official/CODEOWNERS, for the newly merged `SDK_FBProphet_Forecasting_Online.ipynb notebook.`
<br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/community-content) …

moves the owners line from community file to the official file 

---

notebooks/official/custom/custom_training_tensorboard_profiler.ipynb

<br>
1. Used docker image instead of Python package 
2. Updated service account permissions 
3. Handled cloud_profiler.init() error 
4. Used the latest template
5. Addressed review comments from #1266 
<br><br><br>
<br>
2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-a …

fix: updated TensorBoard profiler notebook 2

---

notebooks/official/pipelines/pipelines_intro_kfp.ipynb

Reduced boilerplate in pipelines_intro_kfp.ipynb

pipelines_intro_kfp.ipynb: Reduced boilerplate

---

notebooks/official/matching_engine/sdk_matching_engine_for_indexing.ipynb

Currently the notebook references docs but doesn't link to them.
<br>
<br><br><br>
<br>
<br> …

Adding a link to documentation

---

notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb

custom-tabular-bq-managed-dataset.ipynb: Addressed comments regarding evaluation, normalization and dataset creation

---

.cloud-build/cleanup/cleanup.py
.cloud-build/cleanup/resource_cleanup_manager.py

Added managers to cleanup matching engine resources.

Cleanup Added matching engine resource managers

---

notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb

<br>
Remove obsolete text line on loading mean and stddev
<br><br><br>
<br>
<br> …

fix: rm line about load mean/stddev

---

notebooks/ci_notebook_ingestion.md

<br>
Howtos for CI notebook ingestion admin tasks
<br><br><br>
<br>
<br> …

feat: howto admin

---

notebooks/ci_notebook_ingestion.md

<br>
Updates for review comments
<br><br><br>
<br>
<br> …

Ci admin howto 2

---

notebooks/notebook_template_review.py
notebooks/official.csv

<br>
Moved helper functions into abstract class.
Changed TW rule parsing functions into NotebookRule classes.
Additional changes for TW needs
Potential future code refinements:
1. handling of the two global variables: last_tag and num_errors
2. consolidating error codes and msgs into a dictionary style structure.
3.  undecided on how to or change generating the index -- still a standalone Python function.
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/t …

fix: next round of restructuring.

---

notebooks/community/ml_ops/stage1/README.md
notebooks/community/ml_ops/stage2/README.md
notebooks/community/ml_ops/stage3/README.md
notebooks/community/ml_ops/stage4/README.md
notebooks/community/ml_ops/stage5/README.md
notebooks/community/ml_ops/stage6/README.md
notebooks/community/ml_ops/stage7/README.md
notebooks/notebook_template_review.py

<br>
Update autogeneration of index in README
<br><br><br>
<br>
<br> …

Autoindex 1

---

notebooks/community/ml_ops/stage5/get_started_with_vertex_endpoint_and_shared_vm.ipynb

<br>
Replace using CURL calls with GAPIC methods
<br><br><br>
<br>
<br> …

upgrade: replace CURL with GAPIC

---

notebooks/official/tabular_workflows/tabnet_on_vertex_pipelines.ipynb
notebooks/official/tabular_workflows/wide_and_deep_on_vertex_pipelines.ipynb

<br>
Use sample dataset CSV file from a regional bucket
<br><br><br>

Use sample dataset from regional bucket

---

community-content/pytorch_efficient_training/README.md
community-content/pytorch_efficient_training/resnet_fsdp.py
community-content/pytorch_efficient_training/resnet_fsdp_wds.py

1. Add resnet_fsdp.py - Train ResNet-50 on single node multiple GPUs with `FullyShardedDataParallel` strategy.
2. Add resnet_fsdp_wds.py - Train ResNet-50 on single node multiple GPUs with `FullyShardedDataParallel` strategy and `Webdataset`.
3. Update README.md

Add FSDP examples to PyTorch efficient training

---

.cloud-build/cleanup/cleanup.py
.cloud-build/cleanup/resource_cleanup_manager.py

Removed cleanup changes for testing.

---

.cloud-build/execute_changed_notebooks_helper.py

<br>
Fix for reason notebook ingestion tests timeout after 900 seconds
<br><br><br>
<br>
<br> …

fix: timeout issue for notebook test

---

notebooks/official/tensorboard/tensorboard_profiler_custom_training.ipynb

<br>
Testing that new PRs use the fixed version of .cloud-build
<br><br><br>
<br>
<br> …

debug: force use of newest cloud-build

---

notebooks/notebook_template_review.py
notebooks/official/automl/automl-text-classification.ipynb
notebooks/official/automl/automl_forecasting_bqml_arima_plus_comparison.ipynb
notebooks/official/automl/automl_tabular_on_vertex_pipelines.ipynb
notebooks/official/automl/sdk_automl_tabular_forecasting_batch.ipynb

<br>
Prepping code and notebooks for autogen of webdoc index
<br><br><br>
<br>
<br> …

Autoindex official

---

notebooks/official/tensorboard/tensorboard_profiler_custom_training.ipynb

<br>
1. Moved the profiler minimum version up to 1.20.0
2. Used quotes for the pip install packages
3. Initiated profiler in the beginning of the training script
<br><br><br>
<br>
4. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) …

fix: updated TensorBoard profiler notebooks

---

notebooks/official/datasets/get_started_with_data_labeling.ipynb

<br>
Migrating to official
<br><br><br>
<br>
<br> …

workaround: 900 timeout issue

---

notebooks/official/model_evaluation/README.md

fix: alpha sort

---

notebooks/official/model_evaluation/README.md
notebooks/official/pipelines/README.md

Autoindex official 2

---

notebooks/official/automl/README.md

Fixed link to documentation page

Fixed link to documentation page

---

notebooks/official/automl/automl-tabular-classification.ipynb
notebooks/official/automl/automl-text-classification.ipynb
notebooks/official/automl/automl_forecasting_bqml_arima_plus_comparison.ipynb
notebooks/official/automl/automl_tabular_on_vertex_pipelines.ipynb
notebooks/official/automl/sdk_automl_forecasting_hierarchical_batch.ipynb
notebooks/official/automl/sdk_automl_image_object_detection_batch.ipynb
notebooks/official/automl/sdk_automl_tabular_forecasting_batch.ipynb
notebooks/official/automl/sdk_automl_tabular_regression_batch_bq.ipynb
notebooks/official/automl/sdk_automl_tabular_regression_online_bq.ipynb
notebooks/official/automl/sdk_automl_text_entity_extraction_online.ipynb
notebooks/official/automl/sdk_automl_text_sentiment_analysis_online.ipynb
notebooks/official/automl/sdk_automl_video_action_recognition_batch.ipynb
notebooks/official/automl/sdk_automl_video_classification_batch.ipynb
notebooks/official/automl/sdk_automl_video_object_tracking_batch.ipynb

Fixed links to documentation

---

notebooks/community/model_registry/vertex_ai_model_registry_bqml_custom_model_versioning.ipynb

Without this workaround, the command "from google.cloud import aiplatform as vertex_ai" fails due to the following issue:
https://github.com/googleapis/python-aiplatform/issues/1852
<br>
<br><br><br>
<br> …

Workaround for shapely

---

notebooks/community/pipelines/google_cloud_pipeline_components_bqml_pipeline_anomaly_detection.ipynb

<br>
This notebook is about fixing some minor issues and reviewing the content. 
<br><br><br>

anomaly detection notebook review

---

notebooks/official/tabnet/ai-explanations-tabnet-algorithm.ipynb
notebooks/official/tabnet/tabnet_vertex_tutorial.ipynb
notebooks/official/tabular_workflows/tabnet_on_vertex_pipelines.ipynb
notebooks/official/tabular_workflows/wide_and_deep_on_vertex_pipelines.ipynb

Fixed documentation links

---

notebooks/official/model_monitoring/get_started_with_model_monitoring_setup.ipynb

<br>
Migrate MLops notebook to official
<br><br><br>
<br>
<br> …

migration: MM notebook

---

notebooks/official/bigquery_ml/get_started_with_bqml_training.ipynb

<br>
Migrating MLops notebook to official.
<br><br><br>
<br>
<br> …

migration: bqml

---

notebooks/notebook_template_review.py
notebooks/official/model_registry/bqml_vertexai_model_registry.ipynb

fix: update linkbacks to vertex pages

---

notebooks/official/training/get_started_with_vertex_distributed_training.ipynb

<br>
Migrate notebook from MLops to official
<br><br><br>
<br>
<br> …

migration: distributed training

---

notebooks/official/automl/get_started_automl_training.ipynb

<br>
migrating notebook from MLOps to official
<br><br><br>
<br>
<br> …

migration: automl

---

notebooks/official/automl/README.md
notebooks/official/bigquery_ml/README.md
notebooks/official/experiments/README.md
notebooks/official/model_monitoring/README.md
notebooks/official/model_registry/README.md
notebooks/official/pipelines/README.md
notebooks/official/tabnet/README.md
notebooks/official/tabular_workflows/README.md
notebooks/official/training/README.md
notebooks/official/workbench/README.md

<br>
Revising index for TW review
<br><br><br>
<br>
<br> …

upgrade: revised index

---

.cloud-build/requirements.txt

<br>
SDK Release 1.21 addresses the 900 LRO timeout issue. Removing the mitigation.
<br><br><br>
<br>
<br> …

fix: restore requirements.txt

---

notebooks/community/matching_engine/matching_engine_for_indexing.ipynb

<br>
GCP Customers sometimes have an incorrect configuration which gives them errors such as Error 403 status:14 "failed to connect to all addresses" when their VPC and Matching Engine resources configuration is incorrect. This new section will allow them to troubleshoot their issues without the help from a support agent.
<br><br><br>
<br>
2. If you …

Matching engine tutorial - add networking troubleshooting and updates to notebook

---

notebooks/official/datasets/get_started_with_data_labeling.ipynb

<br>
review for migrated MLOps notebook
<br><br><br>
<br>
<br> …

migration: labeling

---

notebooks/community/pipelines/google_cloud_pipeline_components_bqml_pipeline_demand_forecasting.ipynb

<br>
This PR is about fixing minor issue and releasing a new version of the pipeline.
<br><br><br>
<br>

new demand forecasting pipeline notebook

---

notebooks/official/experiments/get_started_with_vertex_experiments.ipynb

<br>
Migrating from MLops to official
<br><br><br>
<br>
<br> …

migration: experiments

---

notebooks/notebook_template_review.py

<br>
Tune table index from webdoc review
<br><br><br>
<br>
<br> …

fix: TW updates

---

notebooks/official/model_monitoring/get_started_with_model_monitoring_automl.ipynb

<br>
Address code review issues
<br><br><br>
<br>
<br> …

feat: model monitoring

---

.cloud-build/cleanup/resource_cleanup_manager.py

Bug: Index endpoint doesn't undeploy endpoints before deleting itself.

Fixed cleanup code for matching engine index endpoint

---

notebooks/official/pipelines/pipelines_intro_kfp.ipynb

<br>
Fix for issue.
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-a …

fix: issue  263246858

---

notebooks/official/tensorboard/tensorboard_profiler_custom_training_with_prebuilt_container.ipynb

<br>
Enable TensorBoard profiler for custom training with prebuilt container
<br><br><br>
<br>
<br> …

feat: enable TensorBoard profiler for custom training with prebuilt container

---

notebooks/notebook_template_review.py

<br>
Code to properly parse [tag](link) in description section when making web index
Additionally, changes in the table output format.
<br><br><br>
<br>
<br>
3. If you …

fix: missed updates

---

notebooks/official/CODEOWNERS

<br>
Corrected/removed invalid Github usernames in the CODEOWNERS file
<br><br><br>
<br>
<br> …

Corrected/removed invalid Github usernames in the CODEOWNERS file

---

notebooks/notebook_template_review.py

<br>
Add missing code updates
<br><br><br>
<br>
<br> …

fix: lost updates

---

notebooks/notebook_template_review.py

tune: web index

---

notebooks/community/vertex_endpoints/nvidia-triton/get_started_with_triton_ensemble.ipynb

<br>
Add notebook for Triton Ensemble
<br><br><br>
<br>
<br> …

feat: triton ensemble

---

notebooks/official/migration/UJ1 Vertex SDK AutoML Image Classification.ipynb

update tag/linkback #2

---

notebooks/official/migration/UJ15 Vertex SDK AutoML Object Tracking.ipynb

update tag/linkback #4

---

notebooks/official/migration/UJ5 Vertex SDK AutoML Image Object Detection.ipynb

update tag/linkback #5

---

notebooks/official/migration/UJ6 Vertex SDK AutoML Text Classification.ipynb

<br>
update the tag/linkback
<br><br><br>
<br>
<br> …

update tag/linkback #6

---

notebooks/official/migration/UJ7 Vertex SDK AutoML Text Entity Extraction.ipynb

update tag/linkback #7

---

notebooks/official/migration/UJ8 Vertex SDK AutoML Text Sentiment Analysis.ipynb

update tag/linkback #8

---

notebooks/community/vertex_endpoints/torchserve/dreambooth_stablediffusion.ipynb

<br>
Fixed bad links in notebook.
<br><br><br>
<br>
<br> …

fix: bad links in notebook

---

notebooks/notebook_template_writing_guidelines.md

<br>
Add authoring guidelines
<br><br><br>
<br>
<br> …

feat: add authoring guidelines

---

notebooks/official/model_evaluation/automl_tabular_regression_model_evaluation.ipynb

Fixed typo

---

notebooks/official/migration/UJ14 Vertex SDK AutoML Video Classification.ipynb

update tag/linkback #3 AutoML Video

---

notebooks/notebook_template_review.py

<br>
Fine tune web index generation
<br><br><br>
<br>
<br> …

fix: web index tune

---

notebooks/official/automl/get_started_automl_training.ipynb

<br>
Update tag/linkback
<br><br><br>
<br>
<br> …

update tag/linkback #1 AutoML Video

---

notebooks/official/training/pytorch-text-sentiment-classification-custom-train-deploy.ipynb

<br>
Moving notebook to Vertex product specific folder
<br><br><br>
<br>
<br> …

fix: reorg

---

notebooks/official/tabnet/ai-explanations-tabnet-algorithm.ipynb

Fixed typos

---

notebooks/notebook_template_review-sav.py
notebooks/notebook_template_review.py

<br>
Replace GCS and GCP with {{var}}
<br><br><br>
<br>
<br> …

fix: 5 branding bugs

---

notebooks/official/model_evaluation/get_started_with_custom_model_evaluation_import.ipynb

<br>
New notebook for adding a custom evaluation to a model in the Model Registry
<br><br><br>
<br>
<br> …

feat: notebook for custom evaluations

---

notebooks/notebook_template_review.py

<br>
Fix branding issue for Tensorboard (vs TensorBoard)
<br><br><br>
<br>
<br> …

fix: tensorboard branding

---

notebooks/official/explainable_ai/sdk_automl_tabular_classification_online_explain.ipynb

Updated link

---

notebooks/official/migration/UJ14 Vertex SDK AutoML Video Classification.ipynb

Fixed typo and link

---

notebooks/community/prediction/feature_store_integration/prediction_feature_store_integration.ipynb

Notebook user guide for prediction feature store integration experimental feature.

feat: notebook for prediction feature store integration

---

notebooks/official/training/xgboost_data_parallel_training_on_cpu_using_dask.ipynb

<br>
Updated instructions for using Dask with the SDK to allow user to find the dashboard and web access links easily with the SDK. 
<br><br><br>

Update dashboard instructions

---

notebooks/official/pipelines/challenger_vs_blessed_deployment_method.ipynb

<br>
Add notebook to show how to do the challenger vs method model deployment to production in a Vertex AI pipeline
<br><br><br>
<br>
<br> …

feat: challenger vs blessed deployment method

---

notebooks/official/tabular_workflows/prophet_on_vertex_pipelines.ipynb

Added link

---

notebooks/official/migration/UJ11 Vertex SDK Hyperparameter Tuning.ipynb

Fixed title and typos

---

notebooks/official/migration/UJ14 Vertex SDK AutoML Video Classification.ipynb

Fixed title and grammar mistakes

---

notebooks/official/migration/UJ2,12 Vertex SDK Custom Image Classification with pre-built training container.ipynb

…raining container.ipynb
<br>
<br><br><br>
<br>
<br> …

Fixed title

---

notebooks/official/migration/UJ3 Vertex SDK Custom Image Classification with custom training container.ipynb

…g container.ipynb
<br>
<br><br><br>
<br>
<br> …

Fixed title and grammar

---

notebooks/official/CODEOWNERS
notebooks/official/experiments/get_started_with_vertex_experiments_autologging.ipynb

<br>
Adding a notebook about how automate ML experiment tracking with Vertex AI Experiments Autologging. 
<br>

feat: add notebook for experiments autologging

---

notebooks/official/prediction/pytorch_image_classification_with_prebuilt_serving_containers.ipynb

<br>
Add an official notebook sample for PyTorch image models with prebuilt containers
<br><br><br>
<br>
<br> …

feat: add a notebook sample for PyTorch image models with prebuilt containers

---

notebooks/official/model_evaluation/get_started_with_custom_model_evaluation_import.ipynb

<br>
Fix missing linkback
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/ve …

fix: linkback

---

notebooks/official/prediction/pytorch_image_classification_with_prebuilt_serving_containers.ipynb

<br>
Incorporate tech writer's feedback on the PyTorch container notebook.
No code changes.
<br><br><br>
<br>
<br> …

fix: Incorporated Tech Writer's feedback on the PyTorch container notebook

---

notebooks/community/prediction/feature_store_integration/prediction_feature_store_integration.ipynb

<br>
<br><br><br>
<br>
- [ x] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/b …

Add an introduction section and more details to the doc

---

notebooks/official/explainable_ai/sdk_custom_image_classification_online_explain.ipynb

Fixing a typo in the title of this tutorial.
<br>
Update the word "explainabilty" to "explainability"
<br><br><br>
<br>
<br>

Fix typo in title

---

.cloud-build/cleanup/cleanup.py
.cloud-build/cleanup/resource_cleanup_manager.py

<br>
Upgrade resource cleanup
<br><br><br>
<br>
<br> …

fix: add more cleanup

---

CONTRIBUTING.md

<br>
Simplified steps for running linter step
<br><br><br>
<br>
<br> …

fix: simplified linter step

---

notebooks/community/prediction/feature_store_integration/prediction_feature_store_integration.ipynb

modify protobuf docs and add instructions

---

CONTRIBUTING.md

<br>
one notebook per PR rule
<br><br><br>
<br>
<br> …

fix: one notebook rule

---

.cloud-build/execute_changed_notebooks_helper.py

<br>
Lower number of notebooks ran in parallel for weekly regression test. Was getting large number of rate limit quota failures.
<br><br><br>
<br>
<br>
3. If you are …

fix: lower rate limit

---

notebooks/official/pipelines/metrics_viz_run_compare_kfp.ipynb

<br>
replace deprecated package name
<br><br><br>
<br>
<br> …

fix: issue 1251

---

notebooks/official/pipelines/custom_tabular_train_batch_pred_bq_pipeline.ipynb

Fix a typo in the title of this tutorial.
<br>
Update the a misspelled word in the title of this tutorial.
<br><br><br>
<br>
<br>

Fix a typo in the title of the tutorial

---

notebooks/official/pipelines/pipelines_intro_kfp.ipynb

<br>
PROJECT_ID was hardwired in notebook
<br><br><br>
<br>
<br> …

fix: remove hw project id

---

notebooks/official/automl/sdk_automl_forecasting_hierarchical_batch.ipynb

<br>
Corrected steps to be batch (not online) prediction
<br><br><br>
<br>
<br> …

fix: correct the steps

---

notebooks/community/ml_ops/stage3/get_started_vertex_pipelines_xgboost_with_prediction.ipynb

<br>
Setting service account role was missing
<br><br><br>
<br>
<br> …

fix: add missing set sa

---

notebooks/official/matching_engine/sdk_matching_engine_create_text_to_image_embeddings.ipynb

Added explicit image detection using google-cloud-vision safe search API.

Matching engine text-to-image: Added explicit image detection

---

analytics/analytics.ipynb

Checking in this file for testing analytics.

WIP analytics

---

.cloud-build/execute_changed_notebooks_helper.py

<br>
Further reduce rate limit to prevent errors during weekly regression test
<br><br><br>
<br>
<br> …

further lower rate limit

---

notebooks/notebook_template.ipynb

<br>
Test environment does not support --user in install
<br><br><br>
<br>
<br> …

fix --user in template

---

notebooks/official/experiments/comparing_local_trained_models.ipynb

<br>
Fix install for CI/CD test
<br><br><br>
<br>
<br> …

fix install

---

notebooks/official/feature_store/sdk-feature-store.ipynb

<br>
Update notebook sdk-feature-store.ipynb according the template. 
<br><br><br>
<br>
<br> …

chore: update the feature store notebook to the template

---

notebooks/official/workbench/sentiment_analysis/Sentiment_Analysis.ipynb

update tag/linkback #12 b/270404719

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb

**REQUIRED:**
- Add model_garden_pytorch_stable_diffusion.ipynb for stable-diffusion-v1.5 model card.
- Add model_garden_pytorch_stable_diffusion_inpainting.ipynb for stable-diffusion-inpainting model card.
- [ Y] Passes all the required formatting and linting checks. You can locally test with these …

Add stable diffusion notebooks to community model garden

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb

**REQUIRED:** Add instruct-pix2pix notebook to model garden

Add instruct-pix2pix notebook to model garden

---

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb

remove invalid property

---

notebooks/official/automl/automl_image_object_detection_export_edge.ipynb

<br>
migrate community notebook to official to fill feature gap
<br><br><br>
<br>
<br> …

feat: automl object detection edge

---

notebooks/official/training/multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb

<br>
Updated notebook multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb to the latest template
<br><br><br>
<br>
<br> …

chore: cleanup distributed training notebook

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb
notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb

**REQUIRED:** Add controlnet notebook for model garden

Add controlnet notebook for model garden

---

notebooks/official/workbench/exploratory_data_analysis/explore_data_in_bigquery_with_workbench.ipynb

<br>
Updated link with a more relevant page of Vertex AI Workbench docs
<br><br><br>
<br>
<br>

Updated Vertex AI Workbench link

---

notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings.ipynb
notebooks/official/matching_engine/sdk_matching_engine_create_text_to_image_embeddings.ipynb
notebooks/official/matching_engine/sdk_matching_engine_for_indexing.ipynb

Adding tracking pixels for page views.
This is a preliminary test before we try with other notebooks.

Added tracking pixels to matching engine notebooks

---

notebooks/official/automl/automl_text_sentiment_analysis_batch_prediction.ipynb

<br>
Migrating notebook to fill feature gap
<br><br><br>
<br>
<br> …

feat: migrate AutoML TSE for batch

---

notebooks/official/automl/automl_text_entity_extraction_batch_prediction.ipynb

<br>
Migrate notebook to official to cover feature gap
<br><br><br>
<br>
<br> …

feat: migrate AutoML TEE for batch

---

notebooks/official/custom/custom_training_container_and_model_registry.ipynb

<br>
Migrate notebook from community to official to fill feature gap
<br><br><br>
<br>
<br> …

feat: migrate custom train and model registry

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_pytorch_blip_image_captioning.ipynb
notebooks/community/model_garden/model_garden_pytorch_blip_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_vilt_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_vit_gpt2_image_captioning.ipynb

**REQUIRED:** Add image-captioning and vqa notebooks to model garden

Add image-captioning and vqa notebooks to model garden

---

notebooks/official/training/hyperparameter_tuning_xgboost.ipynb

<br>
migrate notebook from community to official to cover feature gap
<br><br><br>
<br>
<br> …

feat: migrate hpt for XGBoost

---

notebooks/community/model_garden/model_garden_pytorch_blip_image_captioning.ipynb
notebooks/community/model_garden/model_garden_pytorch_blip_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_clip.ipynb
notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb
notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb
notebooks/community/model_garden/model_garden_pytorch_layoutml_document_qa.ipynb
notebooks/community/model_garden/model_garden_pytorch_owlvit.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb
notebooks/community/model_garden/model_garden_pytorch_vilt_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_vit_gpt2_image_captioning.ipynb

**REQUIRED:** Fix links for pytorch notebooks

Fix links for pytorch notebooks

---

notebooks/official/workbench/gaming_churn_prediction/churn_prediction_for_game_developers.ipynb

Just a quick update to the BQ ML link so it's more targeted/helpful.

Updated link for BQ ML.

---

notebooks/community/model_garden/model_garden_pytorch_layoutml_document_qa.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb
notebooks/community/model_garden/model_garden_pytorch_vilt_vqa.ipynb

**REQUIRED:** Fix names for pytorch notebooks in model garden

Fix names for pytorch notebooks in model garden

---

notebooks/official/training/distributed_hyperparameter_tuning.ipynb

<br>
migrate community notebook to official to cover feature gap
<br><br><br>
<br>
<br> …

feat: migrate hpt distributed

---

.cloud-build/cleanup/cleanup.py
.cloud-build/cleanup/resource_cleanup_manager.py

<br>
Added removing temporary buckets
<br><br><br>
<br>
<br> …

fix: cleanup buckets

---

notebooks/official/pipelines/get_started_with_hpt_pipeline_components.ipynb

<br>
migrate notebook from community to official to cover feature gap
<br><br><br>
<br>
<br> …

feat: migrate hpt pipeline components

---

notebooks/official/custom/get_started_vertex_training_xgboost.ipynb

<br>
Migrating notebook from community to official to fill feature gap.
<br><br><br>
<br>
<br> …

feat: migrate custom train XGBoost

---

notebooks/official/automl/automl_image_classification_batch_prediction.ipynb

<br>
Fix for resource cleanup of buckets
<br><br><br>
<br>
<br> …

fix: update unique str

---

notebooks/official/automl/automl_image_object_detection_export_edge.ipynb

<br>
Fix unique string for bucket
<br><br><br>
<br>
<br> …

fix: unique str

---

notebooks/notebook_template.ipynb

<br>
Update unique in template
<br><br><br>
<br>
<br> …

fix: fine tune unique

---

.cloud-build/cleanup/resource_cleanup_manager.py

<br>
Fixed missing not in condition.
Was tested by dry_run 
Skipping '<Bucket: sink-storage-1675336852617>' not a Vertex AI notebook bucket
Skipping '<Bucket: staging.python-docs-samples-tests.appspot.com>' not a Vertex AI notebook bucket
Skipping '<Bucket: tmp-07a1019858e24b42a091f43cf2bf1b36>' not a Vertex AI notebook bucket
Skipping '<Bucket: tmp-1d6d323490bb420f963c7aea51b157a5>' not a Vertex AI notebook bucket
Skipping '<Bucket: tmp-31a2de227dd648d881d94d1166b726be>' not a Vertex AI notebook bucket
Skipping '<Bucket: tmp-67be459d8a6c4be2a7f4d8df63c0765e>' not a Vertex AI notebook bucket
Skipping '<Bucket: …

fix: add back missing not

---

notebooks/community/model_garden/model_garden_pytorch_blip_image_captioning.ipynb
notebooks/community/model_garden/model_garden_pytorch_blip_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_clip.ipynb
notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb
notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb
notebooks/community/model_garden/model_garden_pytorch_layoutml_document_qa.ipynb
notebooks/community/model_garden/model_garden_pytorch_owlvit.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb
notebooks/community/model_garden/model_garden_pytorch_vilt_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_vit_gpt2_image_captioning.ipynb

**REQUIRED:** Fix resource clean in pytorch notebooks

Fix resource clean in pytorch notebooks

---

.cloud-build/execute_changed_notebooks_helper.py
.cloud-build/requirements.txt

<br>
2nd try
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-sampl …

update: thread safe limiter

---

notebooks/official/CODEOWNERS
notebooks/official/experiments/delete_outdated_tensorboard_experiments.ipynb

<br>
This notebooks shows how to delete outdated TensorBoard Experiments to avoid unnecessary storage costs.
<br><br><br>

feat: delete outdated tensorboard experiments

---

notebooks/official/tabnet/get_started_with_tabnet.ipynb

<br>
migrate community notebook to official to cover feature gap
<br><br><br>
<br>
<br> …

fix: migrate tabnet

---

notebooks/official/prediction/pytorch_train_deploy_models_with_prebuilt_containers.ipynb

<br>
A new notebook to demonstrate how to train and deploy PyTorch models with pre-built containers on Vertex AI.
<br><br><br>
<br>
<br> …

feat: PyTorch train and deploy E2E with pre-built containers

---

notebooks/community/model_garden/model_garden_pytorch_owlvit.ipynb

**REQUIRED:** Fix owlvit notebook

Fix owlvit notebook

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_pytorch_blip2.ipynb

**REQUIRED:** Add blip2 notebook

Add blip2 notebook

---

notebooks/official/pipelines/automl_tabular_classification_beans.ipynb

<br>
Pin KFP and GCPC versions to < 2.0
<br><br><br>
<br>
<br> …

fix: pin kfp and gcpc < 2.0

---

notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb

**REQUIRED:** Fix controlnet training

Fix controlnet training

---

notebooks/official/migration/sdk-custom-scikit-learn-prebuilt-container.ipynb

<br>
Rename migration notebook
<br><br><br>
<br>
<br> …

fix: rename UJ10

---

notebooks/official/migration/sdk-automl-object-tracking-batch-prediction.ipynb

fix: rename UJ15

---

notebooks/official/migration/sdk-custom-image-classification-prebuilt-container.ipynb

fix: rename UJ2

---

notebooks/official/migration/sdk-custom-image-classification-custom-container.ipynb

fix: rename UJ3

---

notebooks/official/migration/sdk-automl-image-object-detection-batch-online.ipynb

<br>
rename UJ5
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-sa …

fix: rename UJ5

---

notebooks/official/migration/sdk-automl-text-classification-batch-prediction.ipynb

fix: rename UJ6

---

notebooks/official/migration/sdk-automl-text-entity-extraction-batch-prediction.ipynb

fix: rename UJ7

---

notebooks/official/migration/sdk-automl-text-sentiment-analysis-batch-prediction.ipynb

fix: rename UJ8

---

notebooks/official/migration/sdk-custom-xgboost-prebuilt-container.ipynb

fix: rename UJ9

---

notebooks/community/model_garden/model_garden_pytorch_blip2.ipynb
notebooks/community/model_garden/model_garden_pytorch_blip_image_captioning.ipynb
notebooks/community/model_garden/model_garden_pytorch_blip_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_clip.ipynb
notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb
notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb
notebooks/community/model_garden/model_garden_pytorch_layoutml_document_qa.ipynb
notebooks/community/model_garden/model_garden_pytorch_owlvit.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb
notebooks/community/model_garden/model_garden_pytorch_vilt_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_vit_gpt2_image_captioning.ipynb

**REQUIRED:** Add note to BLIP2 notebook

Add note to model garden notebooks

---

notebooks/official/automl/README.md
notebooks/official/custom/README.md
notebooks/official/datasets/README.md
notebooks/official/experiments/README.md
notebooks/official/explainable_ai/README.md
notebooks/official/model_evaluation/README.md
notebooks/official/pipelines/README.md
notebooks/official/prediction/README.md
notebooks/official/tabnet/README.md
notebooks/official/tabular_workflows/README.md
notebooks/official/vizier/README.md

<br>
Updating search indexes
<br><br><br>
<br>
<br> …

update: next round of index

---

notebooks/official/workbench/README.md

<br>
workbench README
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex …

update: searchable index

---

notebooks/community/model_garden/model_garden_pytorch_blip2.ipynb
notebooks/community/model_garden/model_garden_pytorch_blip_image_captioning.ipynb
notebooks/community/model_garden/model_garden_pytorch_blip_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_clip.ipynb
notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb
notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb
notebooks/community/model_garden/model_garden_pytorch_layoutml_document_qa.ipynb
notebooks/community/model_garden/model_garden_pytorch_owlvit.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb
notebooks/community/model_garden/model_garden_pytorch_vilt_vqa.ipynb
notebooks/community/model_garden/model_garden_pytorch_vit_gpt2_image_captioning.ipynb

**REQUIRED:** Fix notes for pytorch notebooks

Fix notes for pytorch notebooks

---

notebooks/community/model_garden/model_garden_pytorch_timm.ipynb

Fix typos and invalid properties in TIMM notebook. It should render on github correctly after this fix.
<br>

Fix typos and invalid properties in TIMM notebook

---

notebooks/community/model_garden/model_garden_pytorch_timm.ipynb

<br>
<br><br><br>
- [x ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/CODEOWNERS) file under the `Community Notebooks` section, pointing to the author or the author's team.
- [x ] Passes all the required formatting and linting checks. You can locally test …

Add 5 additional models to list of verified models.

---

notebooks/official/migration/README.md

update: search index for migration

---

.cloud-build/tests/flaky.py

<br>
Script to split pass and fail notebooks from build log
<br><br><br>
<br>
<br> …

test: flaky script

---

notebooks/official/experiments/get_started_with_vertex_experiments.ipynb

<br>
Fix notebook that failed CI/CD testing
<br><br><br>
<br>
<br> …

improve install

---

.cloud-build/execute_changed_notebooks_cli.py

<br>
First step towards fixing weekly regr flakiness
<br><br><br>
<br>
<br> …

update: test_percent and dry_run for weekly regr

---

notebooks/community/model_garden/model_garden_pytorch_clip.ipynb

**REQUIRED:** Add text/image feature embedding to CLIP notebook

Add text/image feature embedding to CLIP notebook

---

notebooks/official/explainable_ai/xai_text_classification_feature_attributions.ipynb

… sampled shapley
<br>
Added a new notebook for text models for explainable AI feature attribution - sampled shapley method
<br><br><br>
<br>
<br>
3. If you are opening a …

feat: notebook for text models for explainable AI feature attribution - sampled shapley

---

notebooks/official/experiments/delete_outdated_tensorboard_experiments.ipynb

Reverts GoogleCloudPlatform/vertex-ai-samples#1798

Revert "outdated"

---

notebooks/community/ml_ops/stage3/get_started_vertex_pipelines_xgboost_with_prediction.ipynb

there is a regression in later packages

---

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb

**REQUIRED:** Fix stable diffusion serve

Fix model garden stable diffusion serve

---

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb

<br>
Fix format-check and size-check error for stable diffusion inpainting.
<br><br><br>
- [ x] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

Fix format-check and size-check error for stable diffusion inpainting.

---

notebooks/community/model_garden/model_garden_pytorch_detectron2.ipynb

<br>
Fix format-check and size-check error for detectron2.
<br><br><br>
- [x ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
<br>

Fix format-check and size-check error for detectron2.

---

notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb

**REQUIRED:** Fix controlnet serving

Fix controlnet serving

---

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb

Add local inference with Workbench for stable_diffusion.
<br><br><br>
<br>

Update stable_diffusion notebook with steps for local inference.

---

.cloud-build/notebook-execution-test-cloudbuild.yaml

<br>
Adding param to enable test selection based on pass/fail
<br><br><br>
<br>
<br> …

fix: add test percent param

---

notebooks/official/automl/automl_image_classification_online_online_prediction.ipynb

upgrade: boilerplate reduction 3

---

notebooks/official/automl/automl_image_object_detection_export_edge.ipynb

upgrade: boilerplate reduction 4

---

notebooks/official/automl/automl_image_object_detection_online_prediction.ipynb

upgrade: boilerplate reduction 5

---

notebooks/official/automl/automl_image_classification_batch_prediction.ipynb

upgrade: boilerplate reduction 2

---

notebooks/official/automl/automl-tabular-classification.ipynb

upgrade: boilerplate reduction 7

---

notebooks/official/automl/get_started_automl_training.ipynb

update: boiler plate reduction 8

---

notebooks/official/automl/sdk_automl_tabular_forecasting_batch.ipynb

update: boiler plate reduction 9

---

notebooks/official/automl/sdk_automl_text_sentiment_analysis_online.ipynb

update: boilerplate reduction 11

---

notebooks/official/automl/sdk_automl_video_object_tracking_batch.ipynb

update: boilerplate reduction 14

---

notebooks/official/automl/sdk_automl_video_action_recognition_batch.ipynb

update: boilerplate reduction 12

---

notebooks/official/automl/automl_forecasting_bqml_arima_plus_comparison.ipynb

<br>
-Apply boilerplate reduction
<br><br><br>
<br>
<br> …

upgrade: boilerplate reduction #1

---

notebooks/official/automl/sdk_automl_video_classification_batch.ipynb

update: boilerplate reduction 13

---

notebooks/official/automl/automl_tabular_on_vertex_pipelines.ipynb

upgrade: boilerplate reduction 6

---

notebooks/official/bigquery_ml/bqml-online-prediction.ipynb

fix: reduction 15

---

notebooks/community/CODEOWNERS
notebooks/community/ml_ops/stage3/get_started_with_dataflow_flex_template_component.ipynb

<br>
Add Dataflow Flex Template component sample.
This sample should be merged with get_started_with_dataflow_pipeline_components.ipynb when the Dataflow Flex Template component makes it to v1.
<br><br><br>
<br>
2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-sample …

Add Dataflow Flex Template component sample

---

notebooks/official/bigquery_ml/get_started_with_bqml_training.ipynb

fix: reduction 16

---

notebooks/official/custom/get_started_with_vertex_endpoint_and_shared_vm.ipynb

fix: reduction 17

---

notebooks/official/datasets/get_started_bq_datasets.ipynb

fix: boilerplate reduction 20

---

notebooks/community/CODEOWNERS
notebooks/community/generative_ai/text_embedding_api_semantic_search_with_scann.ipynb

Updating the cell moving the pip install to the top.

Text embedding api

---

notebooks/official/experiments/comparing_local_trained_models.ipynb

fix: boilerplate reduction 23

---

notebooks/official/explainable_ai/sdk_custom_tabular_regression_online_explain.ipynb

fix: boilerplate reduction 32

---

notebooks/official/explainable_ai/sdk_custom_tabular_regression_batch_explain.ipynb

<br>
apply boilerplate reduction
<br><br><br>
<br>
<br> …

fix: boilerplate reduction 30

---

notebooks/official/explainable_ai/sdk_automl_tabular_binary_classification_batch_explain.ipynb

fix: boilerplate reduction 26

---

notebooks/official/experiments/get_started_with_vertex_experiments.ipynb

fix: boilerplate reduction 25

---

notebooks/official/experiments/comparing_local_trained_models.ipynb
notebooks/official/experiments/comparing_pipeline_runs.ipynb

Reduction 24

---

notebooks/official/ml_metadata/vertex-pipelines-ml-metadata.ipynb

update: boilerplate reduction 35

---

notebooks/official/model_evaluation/automl_tabular_classification_model_evaluation.ipynb

upgrade: boilerplate reduction 36

---

notebooks/official/model_evaluation/automl_tabular_regression_model_evaluation.ipynb

upgrade: boilerplate reduction 37

---

notebooks/official/model_evaluation/automl_video_classification_model_evaluation.ipynb

fix: bolierplate reduction 39

---

notebooks/official/model_evaluation/custom_tabular_regression_model_evaluation.ipynb

boilerplate reduction 40

---

notebooks/official/model_monitoring/get_started_with_model_monitoring_automl_image_batch.ipynb

fix: boilerplate reduction 42

---

notebooks/official/model_monitoring/get_started_with_model_monitoring_automl.ipynb

fix: boilerplate reduction 44

---

notebooks/official/model_monitoring/get_started_with_model_monitoring_custom_tf_serving.ipynb

fix: boilerplate reduction 45

---

notebooks/official/model_monitoring/get_started_with_model_monitoring_custom.ipynb

fix: boilerplate reduction 46

---

notebooks/official/model_monitoring/get_started_with_model_monitoring_setup.ipynb

fix: boilerplate reduction 47

---

notebooks/official/model_monitoring/get_started_with_model_monitoring_xgboost.ipynb

fix: boilerplate reduction 48

---

notebooks/official/model_registry/bqml_vertexai_model_registry.ipynb

fix: boilerplate reduction 50

---

.cloud-build/execute_changed_notebooks_cli.py
.cloud-build/execute_changed_notebooks_helper.py

<br>
Work for followup PR:
- Replace JSON intermediate storage with serialized/deserialized NetworkExecutionResult.
- Fine-tune the aging algorithm for selecting notebooks.
- Add time window in aging algorithm.
- Read in bulk build_results. **DONE**
<br><br><br>
<br> …

feat: read accumulative result files

---

notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings_palm.ipynb
notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings_vertex.ipynb

Added the "Vertex Text Embedding API" version of Matching Engine notebook.
Done: Fix links in header before submission.

Added Matching Engine + "Vertex Text Embedding API" notebook

---

notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings_vertex.ipynb

Fixed incorrect reference to Sentence T5 model

Fixed incorrect text for StackOverflow notebook

---

notebooks/official/model_monitoring/get_started_with_model_monitoring_automl_image_online.ipynb

fix: boilerplate reduction 43

---

notebooks/official/CODEOWNERS
notebooks/official/experiments/get_started_with_custom_training_autologging_local_script.ipynb

<br>
This notebook shows how to autolog paramenters and metrics of an ML experiment running on Vertex AI training by leveraging the integration with Vertex AI Experiments.
<br><br><br>

feat: Add custom training integration with experiments notebook

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_keras_stable_diffusion.ipynb

**REQUIRED:** Add Keras stable diffusion notebook for model garden.
<br>
Add Keras stable diffusion notebook for model garden
<br><br><br>
- [Y] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/bl …

Add Keras stable diffusion notebook for model garden

---

notebooks/community/model_garden/model_garden_keras_stable_diffusion.ipynb

**REQUIRED:** Update Keras stable diffusion notebooks with cloud notebook template  and fix bugs
<br>
Update Keras stable diffusion notebooks with cloud notebook template  and fix bugs
<br><br><br>
- [Y] Passes all the required formatting and linting checks. You can locally test with these …

Update Keras stable diffusion notebooks with cloud notebook template and fix bugs

---

notebooks/official/bigquery_ml/bqml-online-prediction.ipynb

replace PR 1546
<br>
Replace PR 1546
<br><br><br>
<br>
<br> …

add REGION setting to bqclient

---

notebooks/official/workbench/spark/spark_bigquery.ipynb

Quick update to the Dataproc Serverless link.

Updated link and link text to Dataproc Serverless

---

notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb

Refactor stable diffusion notebook layout for better clarity.
<br><br><br>

Refactor stable diffusion notebook layout

---

notebooks/notebook_template.ipynb

<br>
Fix the rendering issue of notebooks when view by github
<br><br><br>
<br>
<br> …

fix: git rendering issue

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_huggingface_local_inference.ipynb

Add notebook for local huggingface inferences.
<br><br><br>
<br>

Add notebook for local huggingface inferences.

---

.cloud-build/utils/build_results_viewer.py

<br>
Add JSON build results viewer (for Max R)
<br><br><br>
<br>
<br> …

feat: results viewer

---

notebooks/official/pipelines/automl_tabular_classification_beans.ipynb

feat: boiler plate reduction 51

---

notebooks/official/pipelines/control_flow_kfp.ipynb

feat: boiler plate reduction 52

---

notebooks/official/pipelines/custom_model_training_and_batch_prediction.ipynb

feat: boiler plate reduction 53

---

notebooks/official/pipelines/google_cloud_pipeline_components_automl_text.ipynb

feat: boilerplate reduction 57

---

notebooks/community/model_garden/model_garden_huggingface_local_inference.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb

Include selecting `Debian 10` as the operating system for setting up Workbench instance.
<br><br><br>

Add instructions for selecting operating system

---

.cloud-build/execute_changed_notebooks_helper.py
.cloud-build/tests/select_notebooks_test.py

<br>
Add selecting build results by date range
Tune the selection algorithm
Add initial test
<br><br><br>
<br>
<br> …

tune: selecting notebooks

---

notebooks/community/bigquery_ml/README.md
notebooks/community/bigquery_ml/bq_ml_with_vision_translation_nlp.ipynb

<br>
Updated BQML inference notebook and README doc to include link of now published blog
<br><br><br>
- [ Y] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

Updated BQML inference notebook and README to include link of now published blog

---

notebooks/official/pipelines/metrics_viz_run_compare_kfp.ipynb

feat: boilerplate reduction 65

---

notebooks/official/pipelines/google_cloud_pipeline_components_bqml_text.ipynb

<br>
Apply boiler plate reduction to official notebook
<br><br><br>
<br>
<br> …

feat: boilerplate reduction 58

---

notebooks/official/pipelines/google_cloud_pipeline_components_automl_tabular.ipynb

feat: boilerplate reduction 56 

---

.cloud-build/cleanup/cleanup.py
.cloud-build/cleanup/resource_cleanup_manager.py

<br>
cleanup repos
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai …

feat: delete AR repos

---

.cloud-build/cleanup/resource_cleanup_manager.py

tune: AR repeaper

---

notebooks/official/pipelines/get_started_with_machine_management.ipynb

<br>
Fix issue reported by Ze Mao
<br><br><br>
<br>
<br> …

fix: train job not using TRAIN_IMAGE

---

notebooks/official/sdk/SDK_AutoML_Video_Classification.ipynb

fix: boilerplate reduction 68

---

notebooks/official/tabular_workflows/wide_and_deep_on_vertex_pipelines.ipynb

fix: boilerplate reduction 74

---

notebooks/official/training/multi_node_ddp_gloo_vertex_training_with_custom_container.ipynb

<br>
Fix creating AR repo for CI/CD
<br><br><br>
<br>
<br> …

fix: create AR repo

---

notebooks/official/tensorboard/tensorboard_vertex_ai_pipelines_integration.ipynb

fix: boilerplate reduction 78

---

notebooks/official/tensorboard/tensorboard_hyperparameter_tuning_with_hparams.ipynb

fix: boilerplate reduction 77: TF 

---

notebooks/official/training/get_started_with_vertex_distributed_training.ipynb

<br>
Apply notebook reduction to official notebook
<br><br><br>
<br>
<br> …

fix: boilerplate reduction 79

---

notebooks/official/workbench/pricing_optimization/pricing-optimization.ipynb

fix: boilerplate reduction 92

---

notebooks/official/workbench/inventory-prediction/inventory_prediction.ipynb

fix: boilerplate reduction 90

---

notebooks/official/workbench/gaming_churn_prediction/churn_prediction_for_game_developers.ipynb

fix: boilerplate reduction 89

---

notebooks/official/workbench/exploratory_data_analysis/explore_data_in_bigquery_with_workbench.ipynb

fix: boilerplate reduction 87

---

notebooks/official/workbench/demand_forecasting/forecasting-retail-demand.ipynb

<br>
Apply boiler plate reduction to official notebooks
<br><br><br>
<br>
<br> …

fix: boilerplate reduction 86

---

notebooks/official/vizier/gapic-vizier-multi-objective-optimization.ipynb

<br>
Apply boiler plate reduction to official notebook
<br><br><br>
<br>
<br> …

fix: boilerplate reduction 83

---

notebooks/official/training/hyperparameter_tuning_tensorflow.ipynb

fix: boilerplate reduction 80 - AR

---

notebooks/official/training/pytorch-text-sentiment-classification-custom-train-deploy.ipynb

fix: boilerplate reduction 81

---

notebooks/official/workbench/predictive_maintainance/predictive_maintenance_usecase.ipynb

<br>
Apply boilerplate reduction to official notebooks
<br><br><br>
<br>
<br> …

fix: boilerplate reduction 91

---

notebooks/official/workbench/spark/spark_bigquery.ipynb

fix: boilerplate reduction 94

---

notebooks/community/model_garden/model_garden_pytorch_flan_t5_xxl.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb
notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_upscaler.ipynb

**REQUIRED:** Add flan-t5-xxl and stable-diffusion-upscaler notebooks

Add flan-t5-xxl and stable-diffusion-upscaler notebooks

---

notebooks/official/tensorboard/tensorboard_hyperparameter_tuning_with_hparams.ipynb
notebooks/official/workbench/spark/spark_ml.ipynb

fix: boilerplate reduction 95

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_pytorch_bart_large_cnn.ipynb
notebooks/community/model_garden/model_garden_pytorch_dolly_v2.ipynb

<br>
Add Bart-large-cnn and dolly-v2 serving notebooks.
<br><br><br>

Add llm notebooks

---

notebooks/official/explainable_ai/sdk_custom_image_classification_batch_explain.ipynb

<br>
Apply notebook reduction
<br><br><br>
<br>
<br> …

fix: boilerplate reduction 28 - internal error, try again

---

notebooks/official/tabular_workflows/tabnet_on_vertex_pipelines.ipynb

fix: boilerplate reduction 73 - DAG failed

---

.cloud-build/notebook-index-cloudbuild.yaml

<br>
Add cloudbuild script to generate searchable index of official notebooks for the webdocs
<br><br><br>
<br>
<br> …

feat: add build to generate web index of official notebooks

---

notebooks/official/reduction_server/pytorch_distributed_training_reduction_server.ipynb

<br>
Pin transformers version to avoid Pytorch breaking change
<br><br><br>
<br>
<br> …

fix: pin transformers version to avoid Pytorch breaking change

---

notebooks/official/reduction_server/pytorch_distributed_training_reduction_server.ipynb

fix: boilerplate reduction 67 : training pipeline failed

---

notebooks/official/training/multi_node_ddp_nccl_vertex_training_with_custom_container.ipynb

fix: create AR repo > 24hrs

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_pytorch_sam.ipynb

<br>
--- Add Segment Anything model (SAM) to community folder. ---
<br><br><br>

Add Segment Anything (SAM) notebook to model garden community folder.

---

notebooks/community/CODEOWNERS
notebooks/community/model_garden/model_garden_pytorch_text_to_video.ipynb

Add #ModelGarden text-to-video notebook.
<br>
This notebook demonstrates text-to-video OSS checkpoint serving on Vertex AI.
<br><br><br>
<br>

Add #ModelGarden text-to-video notebook.

---

notebooks/official/explainable_ai/sdk_custom_image_classification_online_explain.ipynb

fix: boilerplate reduction 29 - XAI issue

---

notebooks/official/explainable_ai/sdk_custom_tabular_regression_online_explain.ipynb

check if passes

---

notebooks/official/workbench/chicago_taxi_fare_prediction/chicago_taxi_fare_prediction.ipynb

fix: boilerplate reduction 85 - BUCKET_NAME

---

notebooks/official/custom/sdk-custom-image-classification-online.ipynb

Check passes 4

---

notebooks/official/migration/sdk-custom-image-classification-custom-container.ipynb

<br>
Boilerplate reduction of official notebooks
<br><br><br>
<br>
<br> …

boilerplate reduction #97

---

community-content/CODEOWNERS

<br>
Add diffusers train/serve docker files.
<br><br><br>
<br>
<br> …

Add diffusers train/serve docker files.

---

notebooks/official/tensorboard/tensorboard_profiler_custom_training.ipynb

<br>
Fix CI/CD testing
<br><br><br>
<br>
<br>
3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/verte …

fix: check if passes - training failed - no model

---

notebooks/official/matching_engine/sdk_matching_engine_for_indexing.ipynb

Update broken link for data format
