- notebooks/official/automl/automl-text-classification.ipynb
Add authentication similar to https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb
> fix: add authentication

- .github/PULL_REQUEST_TEMPLATE.md
> Added links to locally test for formatting & linting

- notebooks/notebook_template.ipynb
I believe you *can* use a multi-region; it just might not work as well (e.g. for latency, cost) as a regional bucket where you are doing other operations. This removes the inaccurate statement.
> Relax language re: multi-region bucket for training

- .cloud-build/ExecuteChangedNotebooks.py
Fixed the error found here: https://pantheon.corp.google.com/cloud-build/builds/c963bd5b-4db2-45ed-9507-c6726ed35a73?project=python-docs-samples-tests
```
Step #4: 
Step #4: Traceback (most recent call last):
Step #4:   File "/workspace/.cloud-build/ExecuteChangedNotebooks.py", line 396, in <module>
Step #4:     run_changed_notebooks(
Step #4:   File "/workspace/.cloud-build/ExecuteChangedNotebooks.py", line 333, in run_changed_notebooks
Step #4:     total_notebook_duration = functools.reduce(
Step #4: TypeError: reduce() of empty sequence with no initial value
Finished Step #4
```
> Fixed edge case where no notebooks are detected

- notebooks/official/automl/sdk_automl_tabular_forecasting_batch.ipynb
If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/master/notebooks/official) folder, follow this mandatory checklist: a
TODO: Fix the problem with no forecasted data being shown in the Data Studio link.
> Moved forecasting to official folder

- CONTRIBUTING.md
Hi.  I tried to run this all through cloud shell.  pip makes to Python 2.0 there and the command fails.  So, this PR has pip3.
Also, the cloud shell path didn't know about the directory where all this stuff installed, so I've added a command to add it to PATH.
> Improve CONTRIBUTING.md -- Change to pip3 and add to PATH

- CONTRIBUTING.md
The instructions did not work properly because there were two different types of quote marks in one of the commands. This PR fixes the issue.
> docs: Update incorrect quote mark in CONTRIBUTING.md

- .cloud-build/requirements.txt
Relax the ipython requirement as it conflicts with some pre-installed dependencies in the DLVM's.
> Relaxed ipython requirement

- .cloud-build/requirements.txt
DLVM's may require older/newer versions of numpy (and other dependencies), depending on their Python version and other conflicting dependencies.
This frees them up to choose.
> [WIP] Relax requirements for DLVM's

- notebooks/official/pipelines/automl_tabular_classification_beans.ipynb
- notebooks/official/pipelines/google_cloud_pipeline_components_automl_images.ipynb
- notebooks/official/pipelines/google_cloud_pipeline_components_automl_tabular.ipynb
- notebooks/official/pipelines/google_cloud_pipeline_components_automl_text.ipynb
- notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb
This PR fixes the problems with these notebooks being auto-tested. When ran, they leave behind orphaned artifacts and on subsequent runs, the orphan artifacts was causing the pipeline to reuse (cache) past generated resources (endpoint), that have since been deleted. By setting caching to false, it forces all components to be re-ran.
> test: rm caching of components

- notebooks/community/feature_store/sdk-feature-store.ipynb
Moved "Creating BQ dataset" down but need to move `REGION` variable up because previous code cells are dependent.
> moving REGION up

- .github/workflows/ci.yaml
This change only runs the lint job when notebooks are in the PR. However, it doesn't return any status if notebooks aren't found. We may need to look into an alternate approach, such as exiting early with a success code in the workflow if no notebooks are found.
> Revert "ci: Apply filter to format_and_lint_job"

- .github/PULL_REQUEST_TEMPLATE.md
When opening a PR, the CODEOWNERS and instructions hyperlinks throw a 404 error because they point to a URL that has been changed. Fixing these hyperlinks.
> docs: fixing CODEOWNERS and instructions hyperlinks

- .cloud-build/execute_changed_notebooks_helper.py
- .cloud-build/test_folders.txt
Added ability to test a single notebook. The notebook will run directly in the first Cloud Build instead of a child one. This allows the public logs to work for single notebooks, which is the common case.
> Added ability to test a single notebook

- .cloud-build/cleanup/cleanup.py
- .cloud-build/cleanup/resource_cleanup_manager.py
This PR fixes cleanup for Datasets, Endpoints and Models. They were broken due to the following:
- Datasets: `aiplatform.datasets._Dataset.list()` doesn't show any datasets. This may be a bug or by design. See https://github.com/GoogleCloudPlatform/vertex-ai-samples/issues/675
- Endpoints: Deployed models aren't undeployed properly. Details here: https://github.com/googleapis/python-aiplatform/issues/1441
- Models: Due to the Endpoints deletion bug, deployed models block the deletion of models.
> Fixed cleanup scripts

- .cloud-build/execute_changed_notebooks_helper.py
- .cloud-build/notebook-execution-test-cloudbuild.yaml
- .cloud-build/requirements.txt
Currently, the notebook-execution-test tests all notebooks the changed from origin/main.
If the repo's HEAD has moved since the last PR branch rebase, those changed notebooks will be tested as well.
This PR improves the git diff logic by only testing notebooks that changed since the branching point from main, similarly to Github's "Files changed" behaviour.
> Improved git diff logic

- .cloud-build/utils/UpdateNotebookVariables.py
Currently, lines with "==" will have variables replaced:
`'REGION == "[your-region]"  # @param {type:"string"}',` to `'REGION == "us-central1"  # @param {type:"string"}',`
This is usually not intended so this PR fixes it so only assignments are replaced.
> Removed replacement of variable comparisons

- .cloud-build/utils/UpdateNotebookVariables.py
Currently, if the target replacement content starts with a number, the replacement fails.
This PR fixes it and unblocks the service agent injection.
Reference: https://stackoverflow.com/questions/5984633/python-re-sub-group-number-after-number
> Notebook CI: Fixed variable replacement to handle numbers

- .cloud-build/notebook-execution-test-cloudbuild-single.yaml
- .cloud-build/notebook-execution-test-cloudbuild.yaml
The logs shown on Github are long which makes useful information like download links to appear at the very bottom. We changes the yaml files so the commands run in quiet mode which makes the log file shorter.
> Run commands in quiet mode

- .cloud-build/execute_notebook_helper.py
This PR forces papermill to use a specific kernel to run the notebook instead of any defined inside the notebook itself. This avoid errors where the notebook's kernel doesn't exist on the CI.
This reinstates the fix here which was erroneously reverted: https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/497/files
This will unblock this PR: https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/885/checks?check_run_id=7909824488
> fix: Fixed kernel spec by forcing it to use python3

- .github/workflows/linter/Dockerfile
- .github/workflows/linter/run_linter.sh
The linting dependencies that each user needs to install cause a lot of friction for users.
This image makes it easier to run the linter.
```
```
> Added Dockerfile for building a linting image

- notebooks/community/prediction/custom_prediction_routines/SDK_Custom_Predict_SDK_Integration.ipynb
- notebooks/community/prediction/custom_prediction_routines/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb
- notebooks/community/prediction/custom_prediction_routines/SDK_Custom_Preprocess.ipynb
- notebooks/community/prediction/custom_prediction_routines/SDK_Pytorch_Custom_Predict.ipynb
- notebooks/community/prediction/custom_prediction_routines/SDK_Triton_PyTorch_Local_Prediction.ipynb
Remove preview launch state note from CPR notebooks in preparation for GA launch.
> chore: remove preview note from CPR notebooks

- notebooks/official/model_monitoring/model_monitoring.ipynb
The Monitoring Interval is in hours, not seconds.
> Quick typo update in model_monitoring.ipynb

- notebooks/official/model_evaluation/automl_tabular_classification_model_evaluation.ipynb
Hardcoded gcpc version because it fails in newer versions. And this is a request from the model eval SWE team to hardcode the version. Also renamed a variable for consistency! 
> Fix: Hardcode gcpc version in model eval automl classification notebook 

- .cloud-build/execute_changed_notebooks_helper.py
Set timeout value according to correct calculation. Instead of hardcoding (which would be out of date if the desired Cloud Build timeout changes to something larger than 86400), this uses the Cloud Build job's timeout as the request timeout.
> Fixed timeout value in notebook CI

- notebooks/official/model_evaluation/custom_tabular_classification_model_evaluation.ipynb
Hardcode gcpc version and variable renaming.
<br>
> Fix: Hardcode gcpc version in model eval custom classification notebook

- notebooks/official/tabular_workflows/tabnet_on_vertex_pipelines.ipynb
- notebooks/official/tabular_workflows/wide_and_deep_on_vertex_pipelines.ipynb
Update Tabular Workflows notebooks with Feature Transform Engine's new features from GCPC 1.0.31 release
<br>
Update Tabular Workflows notebooks with Feature Transform Engine's new features from GCPC 1.0.31 release, including BigQuery-based dataset-level transformations and feature selection support.
<br><br><br>
> Update Tabular Workflows notebooks with Feature Transform Engine's new features

- community-content/CODEOWNERS
- community-content/pipeline_components/image_ml_model_training/load_image_classification_model/component.yaml
- community-content/pipeline_components/image_ml_model_training/preprocess_image_data/component.yaml
- community-content/pipeline_components/image_ml_model_training/train_image_classification_model/component.yaml
- community-content/pipeline_components/image_ml_model_training/transcode_tfrecord_image_dataset_from_csv/component.yaml
- community-content/pipeline_components/image_ml_model_training/transcode_tfrecord_image_dataset_from_jsonl/component.yaml
<br>
Added image classification pipeline components in support of Ready-to-Go Vertex project.
<br><br><br>
> [Community] Added image classification pipeline components from the Ready-to-Go Vertex project

- .cloud-build/requirements.txt
There is a breaking change with google-api-core that causes early timeouts.
Temporary workaround is to downgrade google-api-core<2.11.0
This should be reverted after google-api-core is fixed.
> Fix google-api-core version to last known working version

- notebooks/official/automl/sdk_automl_tabular_forecasting_batch.ipynb
Fixed misleading comment about GCS output for batch_predict.
Addresses https://github.com/GoogleCloudPlatform/vertex-ai-samples/issues/1482
> notebooks/official/automl/sdk_automl_tabular_forecasting_batch.ipynb: Fixed comment about GCS

- notebooks/official/matching_engine/sdk_matching_engine_for_indexing.ipynb
Fixed typo in notebooks/official/matching_engine/sdk_matching_engine_for_indexing.ipynb which is functionally equivalent but unnecessary.
> Fixed typo in sdk_matching_engine_for_indexing.ipynb

- notebooks/official/training/xgboost_data_parallel_training_on_cpu_using_dask.ipynb
<br>
Added the option for users to specify the enable_dashboard_access and enable_web_access fields when creating a custom Training job with the SDK for Dask. We provide an example for the user to specify these fields using the SDK or using the gcloud command to create the custom Training job, and additionally provide instructions on how to access the dashboard and interactive shell. 
<br><br><br>
> Add SDK support for Dask dashboard to Training

- notebooks/community/prediction/feature_store_integration/prediction_feature_store_integration.ipynb
CPR model server in feature store and prediction integration notebook sample must be copied to the user's project before using with the Prediction service.
> fix: copy CPR model server to users project before using

- notebooks/official/matching_engine/sdk_matching_engine_create_stack_overflow_embeddings.ipynb
- notebooks/official/matching_engine/sdk_matching_engine_create_text_to_image_embeddings.ipynb
Fixed broken markdown in matching engine notebooks in the link to papers.
> Fixed broken markdown in matching engine notebooks

- notebooks/official/prediction/pytorch_image_classification_with_prebuilt_serving_containers.ipynb
<br>
Specifying Python Version and Pinning Dependencies for pytorch_image_classification_with_prebuilt_serving_containers.ipynb
<br><br><br>
> Specifying Python Version and Pinning Dependencies for pytorch_image_classification_with_prebuilt_serving_containers.ipynb

- notebooks/community/model_garden/model_garden_pytorch_blip_image_captioning.ipynb
- notebooks/community/model_garden/model_garden_pytorch_blip_vqa.ipynb
- notebooks/community/model_garden/model_garden_pytorch_clip.ipynb
- notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb
- notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb
- notebooks/community/model_garden/model_garden_pytorch_layoutml_document_qa.ipynb
- notebooks/community/model_garden/model_garden_pytorch_owlvit.ipynb
- notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
- notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb
- notebooks/community/model_garden/model_garden_pytorch_vilt_vqa.ipynb
- notebooks/community/model_garden/model_garden_pytorch_vit_gpt2_image_captioning.ipynb
**REQUIRED:** Fix links for opening notebooks from vertex ai
> Fix links for opening notebooks from vertex ai

- notebooks/community/model_garden/model_garden_tfvision_image_classification.ipynb
This is required due to the inconsistent behavior of `gsutil cp`:
Suppose we have:
```
./a/a/1.txt
```
And we run:
```
gsutil cp -r ./a gs://bucket/dir
```
Then the destination is undeterministic:
- If `gs://bucket/dir` already existed, then 1.txt will be copied to `gs://bucket/dir/a/a/1.txt`.
- If `gs://bucket/dir` does not exist, then 1.txt will be copied to `gs://bucket/dir/a/1.txt`.
By adding a trailing slash to `gs://bucket/dir/`, we enforce the first behavior.
<br><br><br>
> Add a trailing slash to Model Garden ICN notebook checkpoint destination URI

- notebooks/community/model_garden/model_garden_pytorch_blip_image_captioning.ipynb
- notebooks/community/model_garden/model_garden_pytorch_blip_vqa.ipynb
- notebooks/community/model_garden/model_garden_pytorch_clip.ipynb
- notebooks/community/model_garden/model_garden_pytorch_controlnet.ipynb
- notebooks/community/model_garden/model_garden_pytorch_instructpix2pix.ipynb
- notebooks/community/model_garden/model_garden_pytorch_layoutml_document_qa.ipynb
- notebooks/community/model_garden/model_garden_pytorch_owlvit.ipynb
- notebooks/community/model_garden/model_garden_pytorch_stable_diffusion.ipynb
- notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_inpainting.ipynb
- notebooks/community/model_garden/model_garden_pytorch_vilt_vqa.ipynb
- notebooks/community/model_garden/model_garden_pytorch_vit_gpt2_image_captioning.ipynb
**REQUIRED:** Fix docker image urls for pytorch notebooks
> Fix docker image urls for pytorch notebooks

- .cloud-build/execute_changed_notebooks_helper.py
- .cloud-build/requirements.txt
Reverts GoogleCloudPlatform/vertex-ai-samples#1718
I've been trying to get this new rate limiter library to work but it doesn't.
If you measure the actual rate, it doesn't meet expectations.
Recommend going back to ratemate.
> Revert "update: thread safe limiter"

- notebooks/community/model_garden/model_garden_pytorch_timm.ipynb
Add service account config to TIMM notebook to resolve a GCS Fuse issue with the serving docker. Also polished the notebook.
<br><br><br>
<br>
> Add service account config to TIMM notebook

- notebooks/community/model_garden/model_garden_pytorch_timm.ipynb
Add a local inference section to  model_garden_pytorch_timm.ipynb
> Add a local inference section to model_garden_pytorch_timm.ipynb

- notebooks/community/CODEOWNERS
- notebooks/community/model_garden/model_garden_mediapipe_object_detection.ipynb
This adds a new community notebook to train MediaPipe models via Model Maker on Vertex AI
- [ x] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
> Add MediaPipe Object Detection Colab to Model Garden

- notebooks/notebook_template.ipynb
Add extra # character. This enables users to uncomment the whole cell, versus picking just the right lines to uncomment.
> fix: update notebook template comment

- notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
- notebooks/community/model_garden/model_garden_pytorch_openllama_peft.ipynb
**REQUIRED:** Add vLLM support to open-llama and llama2 notebooks
> Add vLLM support to open-llama and llama2 notebooks

- notebooks/community/model_garden/model_garden_mediapipe_image_generation.ipynb
Add Vertex Online Prediction to #ModelGarden #MediaPipe image generation notebook.
Also fixed some issues in the notebook.
<br>
> Add Vertex Online Prediction to #ModelGarden #MediaPipe image generation notebook

- community-content/pipeline_components/image_ml_model_training/load_image_classification_model/component.yaml
- community-content/pipeline_components/image_ml_model_training/preprocess_image_data/component.yaml
- community-content/pipeline_components/image_ml_model_training/train_image_classification_model/component.yaml
- community-content/pipeline_components/image_ml_model_training/transcode_tfrecord_image_dataset_from_csv/component.yaml
- community-content/pipeline_components/image_ml_model_training/transcode_tfrecord_image_dataset_from_jsonl/component.yaml
<br>
The current docker container v0.1 contains some vulnerabilities. v0.2 fixes the most critical of these issues.
<br><br><br>
> Update Image Classification components to use updated v0.2 container (reduced number of vulnerabilities)

- notebooks/official/explainable_ai/sdk_automl_tabular_binary_classification_batch_explain.ipynb
- notebooks/official/explainable_ai/sdk_custom_image_classification_online_explain.ipynb
- notebooks/official/explainable_ai/sdk_custom_tabular_regression_online_explain_get_metadata.ipynb
The module is imported previously, but the Colab instructions restart the kernel losing the import.
Make sure `os` is imported on use.
It's my first PR! 🎉  … I am not sure how to submit the Contributor License Agreement but I believe mine is id 106950177079614963579.
> Add missing 'import os' for notebooks in Colab

- notebooks/official/automl/automl_forecasting_on_vertex_pipelines.ipynb
Fix a typo and add more clarity to sentences.
<be>
1. Typo
**Forecasting** instead of **forecsating**
2. Clarity
**Supported** instead of **support** to explain the the feature has been available
3. Clarity
**More than 3000** instead of **more 3000**
<br><br><be>
Kindly check the files changed for more details of the simple changes :) 
**REQUIRED:** Fill out the below checklists or remove them if irrelevant
<br>
> Fix typos and sentence

- notebooks/community/model_garden/model_garden_tfvision_image_classification.ipynb
- notebooks/community/model_garden/model_garden_tfvision_image_object_detection.ipynb
- notebooks/community/model_garden/model_garden_tfvision_image_segmentation.ipynb
Previously, the model export docker was named `tfvision-serving` which is confusing, since it's not supposed to be used as a serving docker in Vertex online prediction. `tfvision-model-export` is more appropriate. We have verified that the new docker URI is live in the production environment and is safe to switch.
<br>
<br>
> Update #ModelGarden TFVision notebooks model export docker URI.

- notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
Remove extra print statement in LLaMA 2 notebook.
<br>
<br>
> Remove extra print statement in LLaMA 2 notebook.

- notebooks/community/model_garden/model_garden_pytorch_openllama_peft.ipynb
This is a minor patch similar to #2366 .
> Remove misleading prompt output from openllama notebook

- notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
This is an update to an existing notebook: Add documentation for building chat applications using LLaMA 2.
<br>
> Add documentation for building chat applications using LLaMA 2.

- notebooks/official/feature_store/online_feature_serving_and_fetching_bigquery_data_with_feature_store_bigtable.ipynb
<br>
- Uses new v1 SDK for Bigtable serving notebook example.
-  Updates all FS 2 notebooks to use new `data_key` and `data_format` fields.
<br><br><br>
> Update for GA relase, use v1 sdk, and remove known issues

- notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
This is a minor update to an existing notebook: Fix typo in LLaMA 2 instructions.
<br>
> Fix typo in LLaMA 2 instructions.

- notebooks/community/model_garden/model_garden_pytorch_codellama.ipynb
- notebooks/community/model_garden/model_garden_pytorch_llama2_peft.ipynb
- notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb
- notebooks/community/model_garden/model_garden_pytorch_openllama_peft.ipynb
**REQUIRED:** increase max_num_batched_tokens for vllm and remove streaming
1. Increase `--max_num_batched_tokens` to 4096 for longer sequence.
2. Remove streaming mode, it's not supported by Vertex SDK endpoint APIs yet.
3. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
- [ y] Passes all the required formatting and linting checks. You can locally test …
> increase max_num_batched_tokens for vllm and remove streaming

- notebooks/community/model_garden/model_garden_pytorch_timm.ipynb
Update existing timm notebook to use vertex-ai docker link.
<br>
> Update timm notebook to use vertex-ai docker link.

- notebooks/official/model_evaluation/automl_video_classification_model_evaluation.ipynb
Lowercase "video" in the notebook title, plus a small formatting change.
> Fix: update video in workbook title

- notebooks/community/CODEOWNERS
- notebooks/community/model_registry/get_started_with_vertex_ai_deployer.ipynb
<br>
This tutorial demonstrates how to deploy a Vertex AI model to an endpoint using a Cloud Deploy custom target, which allows you to specify a Vertex AI Endpoint as runtime environment into which to deploy your model.
<br>
<br><br>
> feat: adding Vertex AI Deployer notebook

- notebooks/official/workbench/predictive_maintainance/predictive_maintenance_usecase.ipynb
Lowercase "maintenance" in workbook title
> Fix: lowercase maintenance

- notebooks/official/tensorboard/tensorboard_custom_training_with_custom_container.ipynb
Lowercase "custom training" in workbook title
> Fix: lowercase custom training

- notebooks/official/tensorboard/tensorboard_hyperparameter_tuning_with_hparams.ipynb
Lowercase "hyperparameter tuning" in workbook title
> Fix: lowercase hyperparameter tuning

- notebooks/official/generative_ai/rlhf_tune_llm.ipynb
The RLHF tuning notebook states we'll show the user how to tune a bison model, but the large model reference was `t5-xl`. These changes align the `large_model_reference` used in the code example to that of the text.
> fix: Update RLHF large_model_reference to match text.

- notebooks/official/vertex_ai_sdk/remote_training_bigframes_tensorflow.ipynb
<br>
Add custom serializer args (`batch_size` and `target_col`) for bigframes tensorflow
<br><br><br>
> [Vertex AI SDK] Add custom serializer args for bigframes tensorflow

- notebooks/official/generative_ai/rlhf_tune_llm.ipynb
We temporarily disabled this parameter for first-party models, so this will avoid validation errors when running the RLHF tuning notebook in the meantime.
> Remove eval_dataset from RLHF tuning parameters.

- notebooks/official/CODEOWNERS
- notebooks/official/experiments/get_started_with_vertex_experiments.ipynb
<br>
Fix several errors preventing notebook from being run out of the box, namely the custom job container image.
<br><br><br>
> Fix errors in get_started_with_vertex_experiments.ipynb 

- .cloud-build/execute_changed_notebooks_helper.py
Fix b/329846693
Add a fix to properly handle Python versions, otherwise it can't extract versions such as 3.10 or 3.11.
> fix: properly handle python versions

- community-content/vertex_model_garden/model_oss/util/fileutils.py
<br>
In cases where a video file lacks an extension, the filenames generated by `download_video_from_gcs_to_local()` and `get_output_video_file()` functions do not format correctly. For instance, if we work with a video file named `/home/user/video` that does not have an extension, the `replace()` function receives an empty string as its argument. This leads to the replacement of every instance of an empty string in the filename with `_overlay.mp4`, causing an erroneous output like `_overlay.mp4v_overlay.mp4i_overlay.mp4d_overlay.mp4e_overlay.mp4o_overlay.mp4`.
For cases without extensions, we can just append the suffix …
> Fix filename bug by appending suffix directly when a video doesn't have an extension

- notebooks/official/pipelines/google_cloud_pipeline_components_automl_tabular.ipynb
- notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb
A couple of these older notebooks were using a (now-personal) bucket of mine.  I'm belatedly moving the data to 'cloud-samples-data'.  No other changes.
(I'm about to switch the personal bucket to 'requester pays', so once I do that, these notebooks and their tests will break unless this PR is merged in).
> moving some data from personal bucket to 'cloud-samples-data' bucket

- notebooks/official/generative_ai/text_embedding_new_api.ipynb
<br>
Elastic Text-Embedding demo for Google Cloud Next '24 (Apr. 9-11, 2024).
<br><br>
There is another public doc for Cloud Next 24 that shares this colab doc.
<br><br><br>
> feat: Elastic Text-Embedding Model demo.

- notebooks/official/generative_ai/rlhf_tune_llm.ipynb
These changes switch the tuned model from text-bison to llama2. (We'll release an updated notebook with instructions to tune bison in the future.)
We also revised text in some sections to improve clarity.
> Tune llama-2-7b with RLHF.

- notebooks/community/model_garden/model_garden_pytorch_llama3_deployment.ipynb
This PR updates an existing notebook: Update embedded model card link for Llama 3 deployment notebook.
<br>
> Update embedded model card link for Llama 3 deployment notebook.

- notebooks/community/model_garden/model_garden_pytorch_stable_diffusion_finetuning_dreambooth_1_5.ipynb
…tion
<br>
<br><br><br>
<br>
<br> …
> No-code/low-code notebook: fix sd 1.5 dreambooth model deployment section

- notebooks/official/feature_store/online_feature_serving_and_fetching_bigquery_data_with_feature_store_optimized.ipynb
Fx colab parameter usage - the linting/auto-format placed some variables across multiple lines which doesn't work in colab. Also fix some usage for getting FOS - this can be done directly using SDK constructor.
<br>
Uses updated SDK function. Fixes colab forms that nbfmt auto-format broke.
<br><br><br>
_Not relevant_
<br>
2. If you are opening a PR …
> fix: use renamed create_feature_view() function in optimized notebook

- notebooks/community/model_garden/model_garden_jax_paligemma_finetuning.ipynb
Please note that linter fails because Colab Enterprise needs `@param` definition to be in one line even if it is a long line.
> Fix export error

- notebooks/official/ray_on_vertex_ai/ray_cluster_management.ipynb
The [NVIDIA K80 GPUs are no longer supported](https://cloud.google.com/compute/docs/eol/k80-eol). So, the cluster creation step fails.
<br>
1.  Hence, switched to the NVIDIA T4 GPUs. 
2. Cloud Storge bucket is not used anywhere other than at the initialization step (which is optional in this case). Hence, removed the sub-section.
3. Steps are re-organized based on the [new template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb).
4. Updates **Google Cloud ML** to **Vertex AI**.
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/offi …
> fix, refactor(egen): Replaces K80 with T4 GPUs, corrections from template

- notebooks/official/prediction/get_started_with_tf_serving.ipynb
<br>
The docker tag command fails to run when the existing tag is not provided in Colab. The fix resolves it by considering the image name along with the tag from the arguments. 
Additionally, this PR includes the following updates:
1. Adds collapsed license comment.
2. Adds a link for Colab enterprise.
3. Replaces aip with aiplatform, Cloud ML with Vertex AI, & REGION with LOCATION (as per the template).
4. Reduces the future tense usage.
5. Heading style corrections.
6. Removes IS_TESTING from the cleaning up section.
7. Replaces K80 with T4 in the explanation about GPUs.
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-sample …
> chore, fix(egen): corrections from template, guidelines, & fixes docker tag command

- notebooks/official/vector_search/README.md
- notebooks/official/vector_search/sdk_vector_search_create_multimodal_embeddings.ipynb
- notebooks/official/vector_search/sdk_vector_search_create_stack_overflow_embeddings.ipynb
- notebooks/official/vector_search/sdk_vector_search_create_stack_overflow_embeddings_vertex.ipynb
- notebooks/official/vector_search/sdk_vector_search_for_indexing.ipynb
<br>
1. Replace "matching_engine" with "vector_search"
2. Replace "Matching Engine with "Vector Search"
<br><br><br>
<br>
> chore(egen): Replace matching-engine with vector search

- notebooks/official/explainable_ai/xai_image_classification_feature_attributions.ipynb
<br>
The notebook `xai_image_classification_feature_attributions.ipynb` uses the latest version of tensorflow every time. The current version, however, doesn't support some features of the code. Besides, this notebook follows an old version of the notebook-template.
1. Fixes the TF version to 2.15.1.
2. Adds Colab Enterprise link and other structural changes from the new template.
3. Removes IS_TESTING from the cleaning up section.
4. Adds comments for cells needed.
5. Removes unnecessary imports.
6. Includes a dependency(matplotlib) in the installation.
<br><br><br> …
> fix, refactor, chore(egen): Fix TF version support, template format

- notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb
Add HuggingFace tokens to Mistral example colab. HuggingFace now requires an access token to fetch the Mistral models.
<br><br><br>
Test mode: false
Checking for changed notebooked using git
Checking notebook: notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb
Running black...
All done! ✨ 🍰 ✨
1 file left unchanged.
Running pyupgrade...
WARNING: pyupgrade will default to --py3-plus in 3.x
Running isort...
Running nbfmt...
Format notebook: notebooks/community/model_garden/model_garden_pytorch_mistral.ipynb
Running flake8...
Notebook lint finished with return code = 0
All tests finished. Exiting …
> Add hugging face token to mixtral example colab.

- notebooks/community/model_garden/model_garden_movinet_action_recognition.ipynb
- notebooks/community/model_garden/model_garden_movinet_clip_classification.ipynb
<br>
Switch movinet serving notebooks to use port 8080
<br><br><br>
<br>
> Switch movinet serving notebooks to use port 8080

- notebooks/official/model_evaluation/get_started_with_custom_model_evaluation_import.ipynb
1. Fixes the TF version to 2.15.1.
2. Adds Colab Enterprise link and other structural changes from the new template.
3. Changes REGION variable name to LOCATION.
4. Replaces K80 GPU with T4 GPU (as K80 is deprecated).
5. Removes IS_TESTING from the cleaning up section.
6. Adds comments for cells needed.
7. Removes the usage of future tense.
8. Contracts words like is not, do not, You are, etc
> chore, refactor(egen): hardcodes TF version to 2.15.1, refactors code as per template, changes future to present tense

- notebooks/official/pipelines/pipelines_intro_kfp.ipynb
<br>
This PR includes the following updates to the `pipeline_intro_kfp.ipynb` notebook:
- Refactors code to use KFP v2.
- Fixes the REST API request payload for pipeline job creation.
- Updates the cleaning up section: include local files, remove pipeline jobs (not needed).
- Adds Colab authentication and kernal restart steps.
- Adds colab enterprise logo with link.
- Makes Heading changes according to template guidelines.
- Remove duplicate sentences / explanation.
- Fix unnecessary "``" code highlight usage.
- Replace REGION with LOCATION.
- Removes IS_TESTING condition.
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples …
> fix, chore, refactor(egen): REST api fixes, KFP v2 refactor, new template

- notebooks/notebook_template.ipynb
> fix: remove --user from package install

- notebooks/official/migration/sdk-automl-text-classification-batch-prediction.ipynb
This PR, adds a note to the deprecated notebooks and performs linter test.
> chore(egen) : Adds the note to the deprecation of notebook and performs linter test

- notebooks/official/pipelines/custom_model_training_and_batch_prediction.ipynb
<br>
This PR consists of the following updates to the `custom_model_training_and_batch_prediction.ipynb` notebook:
- Changed REGION variable name to LOCATION.
- Replaced aip with aiplatform.
- Replaced K80 GPU with T4 GPU (as K80 is deprecated).
- Replaced version 2-5 with version 2-13 in both training and deployment images and  and also changed the path of images.
- Replaced base_image tensorflow latest version with tensorflow 2.13.0 version in the component
- Added .keras extension when saving and uploading the model.
- Replaced imageuri 2-3 version with 2-13 version in import model step in pipeline and also changed the path of imageuri.
- Removed IS_TESTING from the cleaning up section.
- Removed import statement of os module.
- Added colab enterprise logo with link 
- Heading changes …
> chore, fix, refactor(egen): minor updates to custom model training and batch prediction notebook

- notebooks/official/model_evaluation/automl_tabular_classification_model_evaluation.ipynb
1. Removes the version for google-cloud-pipeline-components package.
2. Removes IS_TESTING from the cleaning up section.
3. Replaces REGION variable with LOCATION.
4. Removes import statement of os module.
5. Adds Colab Enterprise link and other structural changes from the new template.
6. Heading changes according to template guidelines.
7. Contracts words like is not, do not, You are, etc.
8.  Adds comments for cells needed.
> chore,refactor(egen): minor updates to Automl Tabular Classification Model Evaluation Notebook

- notebooks/official/ml_metadata/sdk-metric-parameter-tracking-for-custom-jobs.ipynb
This PR includes 
1.changed REGION to LOCATION
2.removed os module
3.removed os.env(IS_TESTING) in cleanup section
4. performed linter test
5. followed template guidelines
> refactor,chore(egen) : refactored code as per template guidelines , performed linter test

- notebooks/official/pipelines/challenger_vs_blessed_deployment_method.ipynb
<br>
This PR includes the following updates to the `challenger_vs_blessed_deployment_method.ipynb` notebook:
- Change REGION to LOCATION
- Remove IS_TESTING condition at cleaning step
- Adds IS_COLAB in the service account setup
- Removes USER in the installation
- Moves the deletion of local files to the cleaning up section
- Add Colab Enterprise link and other updates from new template.
- Reorganizes the heading styles to match the steps.
- Removes unnecessary code highlights
- Removes future tense 
- Contracts words like "do not" --> "don't"
- Update K80 GPU with T4 GPU
<br><br><br>
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples …
> chore, fix(egen): follows new template, markdown updates and fixes

- notebooks/official/ml_metadata/get_started_with_google_artifact_registry.ipynb
This PR includes 
1. changed REGION variable to LOCATION
2. added colab enterprise link
3. performed linter test
4. removed contradiction words 
> refcator, chore(egen) : refactored code according to template guidelines , performed linter test

- notebooks/official/ml_metadata/sdk-metric-parameter-tracking-for-locally-trained-models.ipynb
changed variable REGION to LOCATION
added matplotlib and pandas in installation section
added delete experiment code in cleanup section
performed linter test
followed template guidelines
> refactor,chore(egen) : added delete experiment code in cleanup section and required packages in installation section 

- notebooks/official/bigquery_ml/get_started_with_bqml_training.ipynb
This PR includes the following updates to the `get_started_with_bqml_training.ipynb` notebook:
1.Replace REGION with LOCATION.
2.Removes IS_TESTING condition.
3.Adds colab enterprise logo with link.
4.Makes Heading changes according to template guidelines.
5.Fix unnecessary "``" code highlight usage.
6.Adds Colab authentication and kernal restart steps.
7.removed unnecessary code 
> refactor,chore(egen) : refactored code according to template guidelines

- notebooks/official/training/pytorch_gcs_data_training.ipynb
Fixed typo: runing --> running
> Fix typo in pytorch_gcs_data_training.ipynb

- notebooks/official/experiments/get_started_with_custom_training_autologging_local_script.ipynb
Fixed typo: paramenters --> parameters
> Fix typo in get_started_with_custom_training_autologging_local_script.ipynb

- notebooks/official/feature_store/offline_feature_serving_from_bigquery_with_feature_registry.ipynb
<br>
feat: add fetch historical feature values notebook
<br><br><br>
<br>
<br> …
> feat: add fetch historical feature values notebook

- notebooks/official/feature_store/online_feature_serving_fetching_multiple_entities.ipynb
<br>
add online serving w/multiple entities notebook - introduces StreamingFetchFeatureValues API
<br><br><br>
<br>
<br> …
> feat: add online serving w/multiple entities notebook

- notebooks/community/model_garden/model_garden_pytorch_llama3_1_deployment.ipynb
Fix request format in model_garden_pytorch_llama3_1_deployment
> Fix request format in model_garden_pytorch_llama3_1_deployment

- notebooks/official/explainable_ai/xai_image_classification_feature_attributions.ipynb
<br>
The notebook `xai_image_classification_feature_attributions.ipynb`'s Colab enterprise link missed "notebooks/" in its path. This PR adds "notebooks/" to the path in the link.
<br><br><br>
<br>
> fix(egen): fixes the path in the colab enterprise link

- notebooks/community/model_garden/model_garden_pytorch_llama3_1_deployment.ipynb
Add variant in Llama 3.1 deployment notebook.
<br>
> Add variant in Llama 3.1 deployment notebook.

- notebooks/community/model_garden/model_garden_pytorch_llama3_1_deployment.ipynb
Fix machine_type in model_garden_pytorch_llama3_1_deployment
> Fix machine_type in model_garden_pytorch_llama3_1_deployment

- community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
Update new job name creation format
This change allows us to use the job name directly for pushing the updates to tensorboard without making any formatting changes in the notebook.
> Update new job name creation format

- community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
Add resize image function to common util
> feat: add resize image function to common util

- notebooks/official/datasets/get_started_with_data_labeling.ipynb
<br>
Vertex ai data lebeling job is now [Deprecated](https://cloud.google.com/vertex-ai/docs/datasets/data-labeling-job). This PR includes a caution note at the top of the notebook.
<br><br><br>
<br>
> chore(Egen): Adds a deprecation note

- notebooks/official/model_monitoring/model_monitoring.ipynb
- refactors based on template
- adds bucket delete
<br>
<br>
> chore, refactor (egen): refactors and edits model_monitoring.ipynb notebook

- notebooks/community/CODEOWNERS
Add codeowners for gemma2 finetuning
Notebook added in https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/3444
> add codeowners for gemma2 finetuning

- notebooks/official/tabnet/ai-explanations-tabnet-algorithm.ipynb
1. Currently the colab enterprise link of this notebook is failing, this pr fixes that.
> fix(egen): fixed the colab enterprise link

- community-content/vertex_model_garden/model_oss/peft/causal_language_modeling_lora.py
- community-content/vertex_model_garden/model_oss/peft/instruct_lora.py
- community-content/vertex_model_garden/model_oss/peft/main.py
- community-content/vertex_model_garden/model_oss/util/constants.py
This PR extends the Vertex Model Garden's PEFT examples to allow passing in a list of Target Modules when running the Causal Language Modeling LoRA Fine Tuning Scripts or the Instruct LoRa Fine Tuning Scripts. The scripts currently allow passing several flags, however, the target modules are hard-coded in each script, which limits what layers we can affect during LoRA training. This PR adds the `target_modules` flag as a CSV list flag, to allow the user to pass in whichever target modules they would like to train for various models. This allows the user greater flexibility in their training cycles.
> Add Target Modules flag to allow passing in the target modules to the LoRa Fine Tuning

- community-content/vertex_model_garden/model_oss/peft/train/vmg/dockerfile/requirements.txt
Reverts GoogleCloudPlatform/vertex-ai-samples#3658
It breaks the model garden docker images.
> Revert "Bump deepspeed from 0.14.4 to 0.15.1 in /community-content/vertex_model_garden/model_oss/peft/train/vmg/dockerfile"

- notebooks/community/CODEOWNERS
- notebooks/community/generative_ai/backoff_and_retry_for_LLMs.ipynb
**Summary:**
I added a new notebook titled "backoff_and_retry_for_LLMs.ipynb" to the /notebooks/community/generative_ai/ directory.
<br>This notebook demonstrates how to trigger and handle 429 Quota exceeded errors using backoff and retry strategies with Dynamic shared quota. The notebook includes the accompanying code for an upcoming blog post on the same topic.
<br>
PR is for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
<br>
> Added notebook titled "backoff_and_retry_for_LLMs.ipynb" to the /notebooks/community/generative_ai/ directory

- community-content/vertex_model_garden/model_oss/util/commons.py
- community-content/vertex_model_garden/model_oss/util/constants.py
- community-content/vertex_model_garden/model_oss/util/fileutils.py
- community-content/vertex_model_garden/model_oss/util/hypertune_utils.py
Currently `community-content/vertex_model_garden/model_oss/peft/train/vmg/dockerfile/train.Dockerfile` docker is failing to run. It is giving errors because the util files does not have the necessary code to run the peft docker. Recent commits has only made updates to `community-content/vertex_model_garden/model_oss/peft` but `community-content/vertex_model_garden/model_oss/util` directory still contains old changes. So This PR is adding relevant changes in `community-content/vertex_model_garden/model_oss/util` which are necessary to run peft docker.
<br>
Fix model_oss peft docker.
<br><br><br>
> Peft docker fix

- notebooks/official/feature_store/feature_monitoring_with_feature_registry.ipynb
<br>
Add FeatureStore Feature Monitoring Notebook
<br><br><br>
> Created using Colab

- community-content/vertex_cpr_samples/torch/predictor_resnet.py
This example uses aiplatform and torch library to provide a ResNet predictor.
> Upload a ResNet predictor example

- notebooks/official/pipelines/kfp2_pipeline.ipynb
<br>
The current version was causing a the below error when executing on xgboost_training component on vertex.
```
numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
Updating the pandas version as shown [here](https://github.com/numpy/numpy/issues/26710) resolved the issue.
<br><br><br>
> Update pandas version on xgboost_training component in kfp2_pipeline

- community-content/vertex_model_garden/model_oss/notebook_util/common_util.py
Add optional support for dedicated endpoint
> Add optional support for dedicated endpoint

- .cloud-build/execute_changed_notebooks_helper.py
- .cloud-build/test_notebook_vm.txt
- notebooks/official/custom/custom-tabular-bq-managed-dataset.ipynb
Use raw string in the regex for the python version
> refactor: Use raw string in regex

- notebooks/official/custom/sdk-custom-image-classification-online.ipynb
- notebooks/official/generative_ai/anthropic_claude_3_intro.ipynb
- notebooks/official/generative_ai/text_embedding_new_api.ipynb
- notebooks/official/model_monitoring/model_monitoring.ipynb
- notebooks/official/pipelines/pipelines_intro_kfp.ipynb
- notebooks/official/ray_on_vertex_ai/get_started_with_pytorch_rov.ipynb
Remove runtime reboot from some notebooks to support automated tests.
Using %pip install instead to install libraries on the current kernel.
> refactor: remove runtime reboot

- notebooks/official/CODEOWNERS
- notebooks/official/prediction/get_started_with_dedicated_endpoint.ipynb
> feat: Add prediction dedicated endpoint colab sample
